### ISSUE TITLE
Additional networks?

### ISSUE THREAD

**Issue by featurecat** [lightvector/KataGo#1]
Is there a place we can download g1 through g65 networks? I am interested in running some experiments with them.

**Comment by lightvector** [comment]
Glad you're interested! I'm assuming you mean the data and network history for the main training run. Once I can get some logistical details solved (e.g. hosting, license), I plan to upload the full network history of KataGo's main run ("g65") and training data, rather than only the strongest network of each size. Likely mid next week, but stay tuned.

"g65" is just an internal identifier for my own personal recordkeeping where these identifiers correspond to whole test runs rather than specific networks. Many of these runs were very short, had bugs, or were from discarded branches of development that were never merged or are now incompatible with the current code, so these aren't being released.

**Comment by featurecat** [comment]
Yes that's what I mean! Thank you

**Comment by lightvector** [comment]
You can download it here now: [katago-public](https://d3dndmfyhecmj0.cloudfront.net/).
Enjoy!
