### ISSUE TITLE
Add standard config and neural net locations

### ISSUE THREAD

**Issue by dwt** [lightvector/KataGo#111]
Hi there,

it would be really nice if there where a standard location in the filesystem ( e.g. ~/.katago/config.cfg, ~/.katago/network.txt.gz) that is used if the respective parameters are not given.

Also being able to specify the location of the used neural network in the configuration file would be really nice.

What I want to do with this: I would really like to provide a default config and network together with the katago home-brew package I'm currently working on, to make it easier for people not so knowledgeable (e.g. my go teacher) to install and use katago successfully.

I'm not yet completely sure where those files would have to be, probably homebrew would want me to install those inside the home-brew directory tree, so it might be necessary to provide these locations at compile time.

So, how about it? Would you be fine with that? Would you take pull requests for that?

**Comment by dwt** [comment]
Home-brew package I'm currently working on is at https://github.com/dwt/homebrew-core/tree/katago

**Comment by lightvector** [comment]
I'm reluctant to do this, because KataGo doesn't have a great automated method quite yet of configuring a few parameters like the number of threads, the batch size to use for the GPU, the cache size (greatly affects how much of the system memory KataGo will consume) and stuff like that. So improving all of that seems like a prerequisite to a fair degree.

Additionally, KataGo is in the middle of a major new run and has been improving about 100 Elo per week (although that may slow down soon). So picking any fixed neural net model right now to package up seems not a good idea - it will quickly become out of date. 

What do you think?

**Comment by dwt** [comment]
Well, regarding the network, I would be fine releasing a new version of the package just as you release new neural nets here. I think that it would actually be a great way to get these out to people that are not quite as technical.

Regarding the configuration options: I think having a standard location in the file system to put these files would make it much easier for users to have their own 'major' config file. Right now I tend to just use one of the example configs (when helping other people setting up katago) and they are always very  content that it runs at all, so arguably I would say that the default provided is surely not optimal - but way better than not having katago run at all.

Being able to pick reasonable defaults for those values in the future would be much better of course. But I  think, that it is good enough for now if the defaults actually work, and are set in a way that allows users to override them with a custom value if they actually know that that value is better, and allows katago to provide a better default in the future as soon as one is available.

Does that make sense?

**Comment by dwt** [comment]
Maybe as an additional data point regarding defaults in the config file. Right now there are some values where you are reluctant to define defaults because you think that you have no good way to define them right now.

I would advise against this way of thinking, as there is a default configuration file (gtp_example.cfg) that effectively defines these defaults and is good enough for people to actually run katago - even though it is not as strong as it could be.  So. effectively. this file defines the defaults.

What I would advise is that it is better to have these defaults in code than in the example config file, as it is much easier to change them with new versions of katago if they are managed in code.

Having the option for power users to customise them to their liking is great and very advisable, but you already have that.

What do you think?

**Comment by lightvector** [comment]
Already moving in that direction of moving defaults out of config and into code, as you may seen with the v1.3.1 release. :)

Making more of them like this would be good, probably. I'm worried that trying to "hide" the config in some default location without doing more of this first will be a mistake, because then future upgrades will have a much harder time to override an old bad value in the config that is in the place the user doesn't even know it exists and never meant to set in the first place.

**Comment by lightvector** [comment]
I think this is addressed by the v1.3.4 release, just now, which incorporates most of your pull request as well on this topic. So I consider this to be handled, let me know if you think there is more to do! :)

**Comment by dwt** [comment]
> Am 29.03.2020 um 22:36 schrieb lightvector <notifications@github.com>:
> 
> 
> I think this is addressed by the v1.3.4 release, just now, which incorporates most of your pull request as well on this topic. So I consider this to be handled, let me know if you think there is more to do! :)
> 

I think I can now modify the package to update a link to a standard network in the home folder if it currently points to the previous releases neural network.

I would like to add a ‚promote network‘ subcommand that creates the symlink for you, but I have to admit that I don’t have the time right now, as I’m burning my free time to help implement https://github.com/ito-org/STRICT <https://github.com/ito-org/STRICT>

I’ll see that I get back to this as soon as stuff gets less hectic with the Covid pandemic.

Until then: stay healthy. :-)

Best regards,
Martin Häcker
