### ISSUE TITLE
Packaging katago for Homebrew

### ISSUE THREAD

**Issue by dwt** [lightvector/KataGo#112]
Hi there,

as I'm currently working on packaging katago for home-brew here <https://github.com/dwt/homebrew-core/tree/katago>, I'm running into a bit of difficulties providing the test part off that package description.

It seems that `katago runtests` is a good fit, but that always fails for me with

```
Running rng and hash tests
Running fancy math tests
Expect test failure!
Elo test 3
Expected===============================================================

Iteration 0 maxEloDiff = 110
Iteration 50 maxEloDiff = 1.25965
Iteration 100 maxEloDiff = 0.0198339
Iteration 150 maxEloDiff = 0.000429407
Elo 0 = -266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
Elo 1 = 266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
Elo 2 = 7.36479e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05

Got====================================================================
Iteration 0 maxEloDiff = 110
Iteration 50 maxEloDiff = 1.25965
Iteration 100 maxEloDiff = 0.0198339
Iteration 150 maxEloDiff = 0.000429407
Elo 0 = -266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
Elo 1 = 266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
Elo 2 = 7.32244e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05

=======================================================================
First line different (0-indexed) = 6
Actual  : Elo 2 = 7.32244e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05
Expected: Elo 2 = 7.36479e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05
Char 11 differs
```

The output seems a bit unclear wether this is an expected failure or a bug that makes the test suite stop. Is this test supposed to fail? If so, what parts of that output are expected to be stable, so I can use that to formulate a test for the package? Or is one of the other tests better suited to check the integrity of the packaged code?

Best Regards,
Martin Häcker

**Comment by lightvector** [comment]
Sorry, yeah, the tests are not necessarily cross-platform stable. They're *extremely* useful for me to debug when I make changes on my own, but since I only develop on Linux, I haven't paid attention to such stability yet.

Probably what's happening here is that on your system, things like "exp" and "log" return different answers - transcendental functions are allowed to vary slightly between systems.

Given that a lot of KataGo uses such operations, and that differences in those can sometimes butterfly-effect up to causing much larger differences just by random chance, I think it's not easy to develop cross-platform-stable tests for large chunks of KataGo's engine.

Thoughts?

**Comment by dwt** [comment]
Well, writing unit tests for code is bread and butter for me. I can take a look and see if I can recommend some ways in which you can make these more cross platform stable.

In general, when I write tests with float / double values, I pick an epsilon that the computed value can diverge from the expected value and usually have a stable unit test. Not sure what the problem is with your tests in this regard yet.

But aside from that: Is the test-suite actually fast enough to be used in this regard? Many minutes of runtime would probably not be acceptable by the homebrew guys.

**Comment by dwt** [comment]
Well having a look at your unit tests, I must say that I'm having a slightly hard time coming up with a simple idea how to make them more portable.

The way you build string output and then compare that is not so easy to customise.

What I am seeing is that surprisingly, its seems to be only this change that makes the standard test-suite run through (and it's quite fast, pretty much good enough

```diff
diff --git a/cpp/core/elo.cpp b/cpp/core/elo.cpp
index 1e80ae8..72c377f 100644
--- a/cpp/core/elo.cpp
+++ b/cpp/core/elo.cpp
@@ -456,7 +456,7 @@ Iteration 100 maxEloDiff = 0.0198339
 Iteration 150 maxEloDiff = 0.000429407
 Elo 0 = -266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
 Elo 1 = 266.471 stdev 234.178 2nd der -2.99835e-05 approx -2.99835e-05
-Elo 2 = 7.36479e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05
+Elo 2 = 7.32244e-07 stdev 128.942 2nd der -5.96894e-05 approx -5.96895e-05
 )%%";
 
     printEloStuff(elos,winMatrix,numPlayers,priorWL);
```

So the question would be - does that difference actually indicate a problem? For me it is quite hard to say what that test actually tests. :/

**Comment by lightvector** [comment]
Thanks. I can fix that one and make it more robust. It's mostly intended to catch anything that might break the behavior of that algorithm by accident.

Regarding sufficient tests:
`./katago runtests` tests a lot of basic foundational code - rules, making moves, scoring, parsing, RNG, etc. Most of it is the sort of stuff that if it breaks, indicates that there's some non-portability, a bug due to switching compilers etc, etc. However there are several MAJOR parts that are not covered by just these tests - namely, the entire search algorithm (MCTS), the neural net computation, and the selfplay logic used for training.

`./katago runnnlayertests` runs some basic tests for individual layers of the neural net implementation to make sure they work. This test *is* robust to floating point errors, and should work across different GPUs - it explicitly allows for floating point tolerance in things. If you find it fails, but the error is very small, the tolerance could be increased a little more.

`./runOutputTests.sh` does a lot of end-to-endish testing of the search and some of the selfplay logic, as much as can be tested without actually having a true neural net. Instead, it uses a random number generator with fixed seed. The way this test works right now is a bit hacky - is simply by running a ton of things, dumping output to a file that overwrites it. If after running, there is any diff whatsoever ("git diff" is nonempty) then this indicates that some behavior has changed. Because this test is fully end-to-end for a lot of things, it's not trivial to make it robust to tiny floating point differences in things like exp and log. But dumping a ton of output and diffing is very, very good though at catching any bugs I introduce when adding features to the search.

`./runsearchtests.sh` runs a large suite of tests that all depend on having the neural net to actually use in conjunction with the search. It works the same as runOutputTests.sh - it overwrites a bunch of files and if this results in diffs, there is something to investigate. This test is definitely not stable, as it's also very end-to-end - switching to different machines with different GPUs will change the numbers and the behavior, but usually the differences are "small", e.g. just some slight change in the reported score or evaluation, or occasionally one less playout searched on this move, one more playout on this other move here. But watching for diffs here is also very very good at catching accidental new bugs, a few of which no other test can easily catch - because some of the logic depends on having a neural net. This test also works only on CUDA.

In the coming release I'm also pushing a separate script like this that runs only a subset of these tests that works on OpenCL too. Not really intended as part of the release, it's just that I'm working on a lot of OpenCL stuff and needed a script for my own purposes at least to test it better).

Yes, the manner of testing here is a little hacky. That's definitely true. :)

**Comment by lightvector** [comment]
Elo test should now be float-robust as of latest release https://github.com/lightvector/KataGo/releases/tag/v1.3.2 now. Other tests are still about the same as they were, described above. Poke me if you have thoughts on how to proceed, or if you have questions - hopefully the above explanation was helpful?

**Comment by dwt** [comment]
Yes, your explanation is extremely helpful. Thanks!

I'll be packaging up the latest release tonight, and if I can get the test to run, I'm pretty sure the home-brew guys will pick it up gladly.

**Comment by dwt** [comment]
And it is in. :-) https://github.com/Homebrew/homebrew-core/commit/cb72a5e03e871f7864790b32d48966abb8e35793

**Comment by dwt** [comment]
And some added documentation: https://github.com/lightvector/KataGo/pull/130
