### ISSUE TITLE
Will KataGo use 40b in the future?

### ISSUE THREAD

**Issue by zhanzhenzhen** [lightvector/KataGo#119]
I've heard that KataGo is still behind Leela Zero, because it's 20b. If it's upgraded to 40b, how much more time it will take than training a 20b network?

**Comment by lightvector** [comment]
I'll upgrade to a larger network soon. But why do you think KataGo is still behind Leela Zero? As of the latest 20b and v1.3.2 release just last weekend, most people seem to be reporting that it's either equal or already ahead now at numbers of playouts that are reasonable on their systems. For example: the most recent posts from this thread on Life in 19: https://lifein19x19.com/viewtopic.php?f=18&t=17195&start=40 or some tests in the Leela Zero Discord in the last few days by users who tried some larger numbers of playouts or visits than on the Life in 19 post: https://discord.gg/wrnERjQ

It definitely depends on your settings and hardware - because the two have different implementations that behave differently on different hardware so the relative difference between them will vary... so its certainly possible that an individual might still find something different, but it overall looks like on average for most users KataGo is already either caught up or past. :)

**Comment by hwata3535** [comment]
KataGo 20b =  very nice  
Thank you
