### ISSUE TITLE
Can I use your TensorFlow model?

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#12]
Hi.

Thank you for your nice research!

I cloned this repository and downloaded b15c192-s279618816-d16499002.zip.
And I tried to use play.py etc. in python directory but failed.

Here is an error I got:

    Traceback (most recent call last):
      File "play.py", line 833, in <module>
        saver.restore(session, modelpath)
      File "/Users/yuji/.virtualenvs/python-6ZMcOZYe/lib/python3.6/site- packages/tensorflow/python/training/saver.py", line 1268, in restore
    + compat.as_text(save_path))
    ValueError: The passed save_path is not a valid checkpoint: ../models/b15c192-s279618816-d164990022/

I took a look at the expanded directory of b15c192-s279618816-d16499002.zip and added 'saved_model/variables/variables' to modelpath in the line of 'saver.restore(session, modelpath)' but did not succeeded.
The cause maybe be the lack of .meta file of checkpoint in saved_model directory.

I have no idea how to generate .meta file.
Can I use your TensorFlow model?

Thank you.

**Comment by lightvector** [comment]
Thanks, I'll take a look at this this evening.

**Comment by lightvector** [comment]
Looked at this. Yeah, the interface is a little unclear. 

I don't believe you need any ".meta" file. It works for me as is. Instead, you do need to pass "../models/b15c192-s279618816-d164990022/saved_model/variables/variables" like you did. If the next error you ran into was that it couldn't find some of the variables it was looking up in the file, recall that as stated in the readme, you need to pass in "-name-scope swa_model" because the model due to how the SWA processing was implemented, the model variables were all built under that namespace when saved.

I'm pushing some changes to master now to clean up and uniformize the model loading between all scripts, which changes the semantics a little from the version you have right now. You will be able to specify

    -model-variables-prefix ../models/b15c192-s279618816-d164990022/saved_model/variables/variables -model-config-json ../models/b15c192-s279618816-d164990022/model.config.json

to explicitly give the path to the variables file Tensorflow produced as well as the model.config.json that builds the model. Or, you will be able to specify simply

    -saved-model-dir ../models/b15c192-s279618816-d164990022/saved_model

so long as the 'saved_model' itself also contains the model.config.json. Currently, in all the downloads I'm providing, the model.config.json is in the wrong place, but I'm fixing that right now.

Let me know if after specifying the correct paths and using -name-scope swa_model you still encounter errors.

**Comment by lightvector** [comment]
Or to summarize simply, in case that was wordy and confusing:

* In your current version, you had the right when "saved_model/variables/variables" to the path, but you probably forgot "-name-scope swa_model", so try that and report any errors if you still have trouble.
* If you pull again from master, you should be able to run the first usage I wrote in my previous post using "-model-variables-prefix" and "-model-config-json" pointing directly to files. You still also need "-name-scope swa_model".

**Comment by y-ich** [comment]
@lightvector san,

I have succeeded in both manners.
Thank you for your explanation!
