### ISSUE TITLE
Where are G170 training games?

### ISSUE THREAD

**Issue by Grant-Tao** [lightvector/KataGo#127]
Here :  https://d3dndmfyhecmj0.cloudfront.net/g170/index.html, I can only find networks, but no data of games;
But for g104: https://d3dndmfyhecmj0.cloudfront.net/g104/index.html, data of games, networks and training are all there.

@lightvector You have done something magic for the OpenCL of version 1.3.2, the speed is just terrific. KataGo must be the strongest Go Bot now.

Could you publish your g170 selfplay games?  if it is convenient.
  
BTW, what is the meaning of the four number tuple followed each move?, like : 
      B[cq]C[0.40 0.60 0.00 -3.7];

**Comment by lightvector** [comment]
Thanks for the compliment! :)

There's a bunch of processing I need to do on the selfplay data - to download it all from the cloud, clean up identifying system logs, zip it all, re-upload it to the S3 file server, and regenerate the index pages on the file server so that you can actually see the links to download. It's all manual to do that right now so I'll just do it once at the end of the run, it's a lot simpler for me that way.

The tuple should be predicted win, loss, noresult, scoreMeanSelfplay. From white's perspective, I believe.

**Comment by alphaladder** [comment]
> Thanks for the compliment! :)
> 
> There's a bunch of processing I need to do on the selfplay data - to download it all from the cloud, clean up identifying system logs, zip it all, re-upload it to the S3 file server, and regenerate the index pages on the file server so that you can actually see the links to download. It's all manual to do that right now so I'll just do it once at the end of the run, it's a lot simpler for me that way.
> 
> The tuple should be predicted win, loss, noresult, scoreMeanSelfplay. From white's perspective, I believe.

@lightvector  From now on, most of the go-fans is only focus on the weights itself. Only special company is more interested in the games ! If those game released , they will use it right away to produce their copy (low quality but in high price)for their own commercial interest without any appreciation . Ironically, they will even claimed that lightvecter/katago had used their unique technique to explain why katago is so similar to their product.

**Comment by lightvector** [comment]
@alphaladder - as I understand it, whether any particular company is copying open source bots or data for their own products, nobody can prove - such things are currently just rumors. Furthermore, if someone did want to make use of publicly available data to help develop a strong Go AI, that is not against any rules. KataGo itself has considered the possibility of using outside data (pro games, strong player games including bot games, bot v bot match games, etc) and might do so in the future, although for now KataGo remains entirely "zero" with respect to outside data.

It is not surprising at all if there are some similarities between different bots. KataGo is not even the first to experiment with some of the ideas it uses to improve training. For example, earlier work involving [multi-step prediction](https://github.com/facebookresearch/darkforestGo) or [multi-output value training](https://arxiv.org/ftp/arxiv/papers/1705/1705.10701.pdf) was influential in developing KataGo, as were some of the other papers you can see cited back as it started out as https://github.com/lightvector/GoNN. And when I Google online I can find other random cool experiments by other users like https://github.com/TheDuck314/go-NN and https://github.com/jmgilmer/GoCNN and https://www.reddit.com/r/cbaduk/comments/ad1w30/using_leela_zero_to_generate_influence/, some all the way back in 2016. Many ideas are pretty natural to independently think of and re-explore.

Having publicly available data helps people to continue to do such experiments. Whether it's to explore bot-v-bot opening statistics (https://cloudygo.com/), or to train new hybrid nets, such as the fascinating and interesting Leela "Master" nets at https://github.com/pangafu/LeelaMasterWeight. Refraining from releasing data would hurt such experiments. It would also not stop anyone determined - for a few 100K USD anyone could simply play enough self-play games to effectively re-create much of the data for any of Leela Zero or KataGo or whatever, and for many corporations, a few 100K USD is mere pocket change. Even so, your request to avoid releasing the data is one that I have received from other people too and I will consider it.

**Anyways, if you would like to discuss/argue/reply about this topic further, rather than replying back here, please just message me privately.** For example, you can find me hanging out in the Leela Zero Discord (https://discord.gg/AjTPFpN) and you can send me a private message from there. There are already plenty of other venues and chat groups where you can discuss such things, so I would appreciate if you did not discuss such rumors further on this GitHub.

I love to research and develop game AI and improve things like KataGo, and therefore rather than getting involved in any sort of online drama, I would like to keep this GitHub focused on cool directions for research or experimentation, feature requests and issues, casual user discussions and ideas, and results in real games or tests. These things are much more productive and fun for everyone. :)

**Comment by Grant-Tao** [comment]
@lightvector Hi, haven't finished the bunch of processings? I am waiting your games for comparing the difference between those with leela zero's . 

If you do not have time, maybe I can give your a hand.

**Comment by lightvector** [comment]
> so I'll just do it once **at the end of the run**, it's a lot simpler for me that way.
It's not the end of the run yet. :)
It will be a month or two, the current run is still ongoing.

**Comment by Grant-Tao** [comment]
Amazing! that means there still is some space for improving. congrats!

**Comment by Grant-Tao** [comment]
@lightvector Congrats, finally finished this round of training?

**Comment by lightvector** [comment]
g170 games are indeed published now https://d3dndmfyhecmj0.cloudfront.net/
