### ISSUE TITLE
We are very opposed to publicly publishing katago's self-playing game records.

### ISSUE THREAD

**Issue by luckyangman** [lightvector/KataGo#137]
Dear katago author
       I represent the QQ group of many of our Go friends.
       We are very much against the public announcement of Katago's self-playing game. This will benefit a small company that has repeatedly downgraded leelaz and katago.
       We have no objection to using Go services to make money. But acknowledge and respect the use of open source resources! We are against deprecating open source Go while using the resources of open source Go AI to make money. This has seriously hurt the hearts of many enthusiasts who are enthusiastic in supporting and caring for leelaz and katago.
       This little company's defamation of katago made us very angry. What is "Katago's experimental data is not enough, the level of writing the paper is far worse than deepmind. The model is not scientifically designed." Katago's method was proposed by this small company long ago. and many more. No more examples. The abominable behavior of this small company against leelazero will not be elaborated here.
       Facts have proved that katago is the best Go AI in Go today. Not only is Go Go great. Make the Handicap better. Multiple Go rules are also supported. And you can use different Go boards to play Go. It will soon become the strongest Go AI.
       We don't want this to affect your mood. Believe it or not. Because you are a bright and enthusiastic scholar. Little suggestion. Urge to adopt. Thank you!

**Comment by luckyangman** [comment]
尊敬的katago作者
       我代表我们众多围棋朋友QQ群：
       我们非常反对将 katago 的自我对弈的棋谱公开发表。这样会让曾经多次贬低 leelaz 和 katago 的某个小公司从中获利。
       我们不反对利用围棋服务挣钱。但是使用了开源资源就要承认并尊重！ 我们反对贬低开源围棋的同时利用开源围棋AI的资源来赚钱。这已经严重伤害了众多热心支持和关心leelaz和katago的棋友的心。
       这个小公司对katago的诽谤让我们感到很气愤。什么“katago实验数据做得并不充分，写论文的水平比deepmind差得挺远。模型设计得也不科学。”katago的方法是这个小公司早就提出来的。等等。不再多举例了。对leelaz的可恶行为就不再这里细说了。
       事实证明katago是当今围棋第一优秀的围棋AI.不但分先围棋厉害。让子更加优秀。还支持多种围棋规则。并可以使用不同路围棋盘下围棋。很快将成为棋力最强的围棋AI。
       我们不希望这件事情影响到你的心情。相信也不会。因为你是个聪慧热情的学者。小小建议。恳请采纳。谢谢！

**Comment by kennychenfs** [comment]
What did those companies do with self play games?

**Comment by pangafu** [comment]
They use the self-play game to find opening weak from short game, then use RL to strengthen it.

The RL result is that they can use 1*2080ti to beat 4*v100 at low PO, but if avoid the opening, the result will be reversed.

With these result, they announce they has the most powerful AI, also said the open-source AI is bubbish.

**Comment by lightvector** [comment]
@luckyangman - Thanks for your thoughts.  Regardless of who is saying what about KataGo, I prefer to not get involved in to online issues like this, so I'm going to close this thread. I prefer to just focus on doing cool research and on making a free Go engine that people find fun and useful. :)

Please don't get too ahead of things and claim that KataGo will surely be the strongest or whatever. If it reached that point, that would be great, but also it is still of course experimental - maybe the current run stalls and new ideas will be necessary to make progress. Or maybe not, maybe it goes very far. Maybe we reach the limit of what pure self-play with no external help can achieve, and then it will need a lot more work either fully giving up on "zero" or trying to find a fundamental new breakthrough. All of these we don't know yet, it's not finished - so of course neither I nor anyone else can promise any particular result.

And that that uncertainty is part of why this is exciting - for some of these ideas, it's the first time anyone in the open community has tried them on such a scale. So let's discover what happens. :)

Anyways, I acknowledge your concern. I was planning to release the data from this run once my budget had exhausted and this run reached its end. I still expect I will release a lot of the data at that point. But anyways, that's in the future - when that time comes, I will decide what to do.

**Comment by PJTraill** [comment]
I wish I knew what this was all about:
* What is a QQ group?
* What is this small company and what does it do?
* How has it denigrated KataGo?
* How would it actually benefit from the self-playing records?
* Where did it propose KataGo’s method?

**Comment by lightvector** [comment]
@PJTraill - please don't stir anything up here, but I'll give a summary. :)

QQ refers to some Chinese internet/social media platform. The small company is Golaxy, who in their quest to commercially promote themselves has said negative things about both KataGo and Leela Zero and other open source programs. Some of the things they said in the past were provocative and gave an impression that would be misleading. This is understandable, because they are trying to make a profit off of their product and advertise themselves. Some of its users/supporters, naturally, believed those misleading things. For example - regarding what they contributed to Go AI research* (I'm not sure they've published research papers or released code) versus the tools and level of AI *available to customers*. People excited about KataGo and/or open-source supporters "fought back", with escalating conspiracy theories developed on both sides, and whole flame wars happened on Chinese social media all the while you and me and everyone actually involved in the development open source Go programs that were supposedly being defended were pretty much unaware of it. (heh)

This thread was closed because it is a tip of an iceberg that distracts from the task of real research and software development. I think it's better to treat everyone, even the projects and people you think are your competitors, with courtesy and respect. In Go, your opponents are also your partners or at least your friendly rivals, and it seems this whole thing started because people forgot this. I'm far from perfect myself, but when I mess up I try to  recognize and correct it because that helps the community grow and be a fun place to hang out.

Anyways, for those who received notifications about this thread, please let's not reopen this. If you want to discuss further, please take it elsewhere, thanks.
