### ISSUE TITLE
 What's the difference between whiteScoreMean  and whiteLead?

### ISSUE THREAD

**Issue by yzyray** [lightvector/KataGo#139]
I tried recently updated gtp command kata-raw-nn,but get confused about whiteScoreMean  and whiteLead,what's the difference?

**Comment by kennychenfs** [comment]
KataGo used to report an estimate of the selfplay average score - the average score that it would achieve if it self-played from a position. So for example, if black were to get an extra stone for free then older KataGo nets might report for example +20, even though the stone should be worth only fair_komi * 2 ~= 14 points. Why? Because KataGo correctly predicted that in self-play, the side that was behind might give up 6 more points on average over the entire rest of the game by taking additional risks to try to swing the game back. These new neural nets are also now trained to estimate the lead - the number of points needed to make the game fair, in this case 14. By default now, KataGo with the latest neural nets will show the estimated lead rather than the estimated selfplay average score - which should be much less confusing.

**Comment by yzyray** [comment]
Thanks for the detailed explanation.

**Comment by lightvector** [comment]
Since it's only been a few hours, before anyone comes to rely on the names, I pushed a change in master to update the names to be better, and improved the docs: https://github.com/lightvector/KataGo/commit/5b6a182a9cd0edd2b4ac75a8cdfaebdfa43171a0

**Comment by lightvector** [comment]
I'm going to close this, since it seems handled. Let me know if you feel otherwise, thanks!
