### ISSUE TITLE
(Question) Why does the result of dynamic PDA cannot reach the maximum limit of the fixed PDA

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#143]
The current maximum limit of fixed PDA is 3.0.
I try to enable the dynamic PDA and set it to a high value in a high handicap game (ex. dynamic PDA=0.10 in a 9-handicap game), and I find that the actual result of PDA can only reach 2.75 at most.

**Comment by lightvector** [comment]
At the most extreme values, I hadn't tested it very much, and anecdotally I felt there were some cases where either it didn't learn well or it played certain kinds of overplays that would not actually work well against dan players of reasonable level.

This might be just paranoia. The cap was actually 2.5 originally, until someone persuaded me to expand it a little. I could be persuaded to remove the cap entirely, since it's actually such a small difference at this point, particularly if someone was able to test and verify that even the maximally extreme value of 3.0 behaves well and in fact does better against opponents of the appropriate strength in very high handicap games (perhaps, one try would be some earlier software, like CrazyStone or Zen set to lower levels?).

**Comment by sbbdms** [comment]
Thanks for your answering.
It is fine when I make sure that it is not a mistake... ;)
