### ISSUE TITLE
how to convert txt format net file to bin?

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#146]
are there any commands or scripts for doing that?

**Comment by lightvector** [comment]
Not quite, but you can convert a Tensorflow SavedModel (which is produced during the training process) to either a .txt or a .bin. This is how you get either of them in the first place. The script for doing that is https://github.com/lightvector/KataGo/blob/master/python/export_model.py

**Comment by l1t1** [comment]
thanks

**Comment by Grant-Tao** [comment]
DOes not work! @lightvector  error message:
Not found: Key conv1/w not found in checkpoint. 
Any suggestion?

**Comment by lightvector** [comment]
Take a look how `python/selfplay/export_model_for_selfplay.sh` calls it. You probably need to pass `-name-scope swa_model` since KataGo uses SWA, and SWA averaging is currently done in that separate name scope instead of the default one.

Also, if you're trying to convert old g104 models, it won't work. The model architecture has changed in between then and now.

**Comment by Grant-Tao** [comment]
Thank you very much for the swift hint. Mission done.
