### ISSUE TITLE
Conform to Sabaki's analyze command standards

### ISSUE THREAD

**Issue by benjaminvdb** [lightvector/KataGo#159]
I requested a feature (see SabakiHQ/Sabaki#640) for Sabaki to support KataGo's territory ownership feature. However, since KataGo's kata-analyze command doesn't conform to Sabaki's [analyze command standards](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/engine-analysis-integration.md) this is not possible at the moment (see [this comment](https://github.com/SabakiHQ/Sabaki/issues/619#issuecomment-593095843)).

Would it be possible for KataGo to conform to Sabaki's analyze command standards? I can image this would make integrating said features in other tools easier as well.

**Comment by lightvector** [comment]
Except for the very fact of including more values to report, in what way does it not conform right now? 

Is it the fact that winrate is reported as a float rather than multiplied by 100 and rounded to an integer? That's the only difference I can think of right now and it seems like a rather trivial one, so maybe I'm missing something obvious.

**Comment by benjaminvdb** [comment]
Hi @lightvector, thank you for your quick response. To be honest, I'm not really sure why KataGo doesn't conform to it at the moment, I'm just propagating [what one of Sabaki's author said](https://github.com/SabakiHQ/Sabaki/issues/619#issuecomment-593095843). Perhaps it would be best to discuss this there?

**Comment by lightvector** [comment]
Released v1.3.4 with changes discussed in that thread. Yay.

**Comment by benjaminvdb** [comment]
@lightvector I had no idea my request would lead to such a long discussion! Thanks for all your hard work 🙏
