### ISSUE TITLE
Can I start 9x9 directly?

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#171]
In my environment, `./katago gtp -model kata_128x10.bin.gz -config gtp.cfg` takes 6.6 sec until "GTP ready" message, and `boardsize 9` takes another 6.7 sec after it. This seems redundant. Can I start 9x9 directly? For my purpose, command line options are preferable to config files because I will use various sizes (19x19, 13x13, 9x9, ...).

(Background)
My GUI has multiple boards like tabs in web browsers. As `boardsize XX` takes a long time, I am trying to assign an individual engine process to each board size so that I can switch them quickly. It works fine once the engines finish their initialization. But the start of 9x9 engine is twice as slow as that of 19x19 as mentioned above. +6.7 sec is large for UI.

**Comment by lightvector** [comment]
I'll implement a way to do this for next release. Thanks!

**Comment by lightvector** [comment]
Done and pushed to the current tip of master.
https://github.com/lightvector/KataGo/commit/8fbf36253461b005de49d1bce1bf5af192f4fe93

Implemented as a config option `defaultBoardSize`. However, all config options for the `gtp` command are also addable or settable on the command line by specifying `-override-config KEY=VALUE,KEY=VALUE,...` which was a feature that has present now since the 1.3.3 release, not too long ago. So you can use the command line too if you want, like `-override-config defaultBoardSize=9`.

**Comment by kaorahi** [comment]
The start of 9x9 is shorten from 13.5 sec to 6.9 sec. Thanks!
