### ISSUE TITLE
Self-play on a GPU cluster

### ISSUE THREAD

**Issue by mjyeh** [lightvector/KataGo#174]
Hi! I'm trying to run self-play on a GPU cluster and had a few questions.
When doing self-play on multiple GPUs, does each GPU play games independently of the others, or can multiple GPUs work on the same game, sharing information with each other? If the latter is true, can self-play be easily configured for GPUs that are distributed among multiple nodes?

**Comment by lightvector** [comment]
Each GPU plays games independently. So no, self-play across multiple nodes is not supported.

In fact, each GPU plays hundreds of separate games simultaneously, with each game on its own being single-threaded. This is how self-play achieves extremely large batch sizes for good GPU throughput but without degrading the strength, since multithreaded search with many threads harms the strength.

**Comment by lightvector** [comment]
Anyways, I don't really see why one would want self-play training games to be shared across machines. Maybe cross-machine distributed search it would be useful for tournament games or something, but training is far better with massive game parallelization as currently implemented, so closing this issue. Thanks!
