### ISSUE TITLE
[Question] Difference of scoreLeads between genmove and kata-analyze for handicap games

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#177]
Hi.
Thank you for your great project!
I have a question for you.

When you run `genmove white` for two-stone game with `ogsChatToStderr = true`, you get information like below.

    CHAT:Visits 7 Winrate 3.34% ScoreLead -14.6 ScoreStdev 20.3 (PDA 0.62) PV D4

And when you run `kata-analyze 100` for the same position, you get information like below.

    info move R16 visits 4 utility -1.03709 winrate 0.0154439 scoreMean -18.9914 scoreStdev 20.6618 scoreLead -18.9914 scoreSelfplay -23.5262 prior 0.0663551 lcb -0.0878823 utilityLcb -1.3264 order 0 pv R16 C4 E3

What is the difference between ScoreLead( -14.6) by genmove and scoreLead(-18.9914) by kata-analyze?
This difference seems to occur only for handicap games.

Thanks.

**Comment by lightvector** [comment]
When playing handicap games by default (but NOT when analyzing them), KataGo tries to keep the position such that the weaker player will make more mistakes. Some self-play games are played with asymmetric numbers of visits on each side, so it learns what kinds of positions benefit the stronger player more than the weaker player (e.g. complex, unsettled positions). Then, when playing a real game, the neural net can be told to produce winrates and scores taking into account the fact that one player is stronger than the other, and therefore the search will prefer lines that lead to more complex positions for the strong side because those have higher winrates, and try to limit the weaker side's ability to simplify the position.

The important part is the "PDA 0.62". This tells the neural net to behave as if white has 2^0.62 ~= 1.53 times as many visits as black does. The winrate and score are the expected winrate and score that would occur in selfplay assuming that this is true.

**Comment by y-ich** [comment]
I see!

Thank you for your explanation!
