### ISSUE TITLE
analysis engine query priority

### ISSUE THREAD

**Issue by sanderland** [lightvector/KataGo#179]
Suggestion: in the json analysis program, allow a signed integer option 'priority'. Queries will be processed in order of highest priority first, tie breaking on submission order.

This is a feature suggestion that would help my program. This will help the where an SGF is submitted for analysis, and the user wants to explore variations while the program is analyzing the game. Currently you would only get feedback on these after the entire game is done analyzing, which is not ideal.

I've looked into how to add this, but would like to run it by you to get your thoughts before I put too much time into it.

* make a variant of threadsafe queue which is a priority queue
* add some counter variable which is incremented each query
* store things in the queue with key priority - epsilon*counter (or negative if it's a min-heap)
* done?

**Comment by lightvector** [comment]
I think we probably just want a similar kind of thread-safe class that is built around this as the core data structure then:
https://en.cppreference.com/w/cpp/container/priority_queue

so that the ordering can be by an arbitrary type. Then we can use a tuple as the type, with the user priority being primary, and an int64 counter as the second - which would be little more "proper". :)

Otherwise, seems like a good idea. Did you want to implement it?

**Comment by sanderland** [comment]
yep, that's what I meant by variant of the threadsafe queue. 
I'll give it a try, and will try to be proper. ;)

**Comment by lightvector** [comment]
All done, thanks!
