### ISSUE TITLE
glibc version mismatch

### ISSUE THREAD

**Issue by tasuki** [lightvector/KataGo#188]
Trying to run KataGo on Ubuntu 16.04:
```
$ ./katago                
./katago: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./katago)
./katago: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./katago)
```

Halp please? Fyi:
```
$ ldd --version           
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23
Copyright © 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by lightvector** [comment]
Are you able to update your version of glibc via `apt`?

**Comment by lightvector** [comment]
Just poking back in here. Searching online it seems this is actually a bit tricky. So possibly your best bet is to compile yourself. Which, if you have a recent enough version of cmake, usually is not hard at all on Linux, since you can just `sudo apt install` most of the the missing dependencies you need instead of having to painstakingly track them down and build them. 

Instructions here:
https://github.com/lightvector/KataGo#compiling-katago

**Comment by tasuki** [comment]
@lightvector thank you for your quick reply - sorry missed the notification...

I'll try compiling! (probably already have most of the dependencies since I compiled Leela Zero)
