### ISSUE TITLE
SGF files of KataGo training set and evaluations

### ISSUE THREAD

**Issue by SHKD13** [lightvector/KataGo#19]
Hi :) First of all, thanks for an intriguing experiment with alternative way of training the Go bot! It looks very promisingly.
My issue is simple. Do you have a plans to publish the sgf's with the freshest selfplay and/or evaluation games?
Would be great to take a look at KataGo's full strength evaluation games for study its opening ideas, compare it with the ones from Leela Zero and MiniGo.
I can use my own storage for saving these games to save the harddisk space for you.

**Comment by lightvector** [comment]
I'll try to get something out this weekend. Thanks!

**Comment by SHKD13** [comment]
@lightvector
Thanks to you! I've got over 1 tb of free disk space you can count on, so any amount of evaluations or selfplays is not a problem. You'll be able to free your own storages or hdd's when it's needed.

**Comment by lightvector** [comment]
Update: have been working on this. Storage space should not be a problem, but downloading/uploading the data, as well as trying to get organized for a new release and is taking some time. Should be out soon though.

**Comment by lightvector** [comment]
Everything is out! New models, training data, and self-play games are all uploaded to here: https://d3dndmfyhecmj0.cloudfront.net/
New release of the code and convenience downloads of the top models here: https://github.com/lightvector/KataGo/releases

**Comment by SHKD13** [comment]
@lightvector 
Thanks!! :) Sorry my ignorance, can you hint me how to extract the sgf's from files like **B7DC7BC1102160B8.sgfs** inside zips? My 7-Zip can't do that.
And are all the files inside the selfplays or there are any evaluation games?

**Comment by Friday9i** [comment]
I took a look at these .sgfs files: when you rename them in .txt, you see all the games one after the other, beginning with "(;FF[4]GM[1]..." and finishing with "])", before the next one (beginning with another "(;FF[4]GM[1]...")
So you can select a game, copy and paste it in another .txt file, then rename it with a .sgf
This approach is not very efficient but at least it works : -)

**Comment by SHKD13** [comment]
@Friday9i 
Thanks! I think it is good for an overview of some games.
I hope there is one more way to extract the sgf files for trying them as a game base))

**Comment by lightvector** [comment]
@Friday9i @SHKD13 

For splitting the files, if you're on Linux, just do something like this:
https://stackoverflow.com/a/37319710/9300125

Or here for Windows:
https://stackoverflow.com/questions/31786287/how-to-split-large-text-file-in-windows/52007759

Similarly, if you're trying to filter games with board sizes that are smaller than 19x19, then you can grep only for lines with the string "SZ[19]", which is how the SGF format specifies the board size. Hope that helps!

**Comment by lightvector** [comment]
Also, don't forget the readme in https://d3dndmfyhecmj0.cloudfront.net/g104/ - it should hopefully answer some other questions about the data format.

Some undocumented details: If you look at the start of the SGF, the first move should contain a comment like "startTurnIdx=14,mode=0,modeM1=0,modeM2=0". startTurnIdx is when the "real" self-play starts, before that, moves are generated with heavier randomization and sometimes outright bad/experimental moves to ensure some wacky opening diversity. Additionally, "modeM2=1" indicates that one or more of the moves in the game, potentially much later in the game, was deliberately randomized and highly experimental. If you filter to only games with startTurnIdx=0, and "modeM2=0", you should get games where none of the moves have had explicit high randomization. There is some randomization still, because KataGo plays *all* games with a nonzero temperature, including gating games, and it is heavier around the start of the game, but it should not be too bad.

Yes, the games uploaded are only the self-play games, I have not tried to organize and upload the games for gating. If you mind the above details though, the self-play games you filter down to should be not much less high-quality than the gating games - KataGo also uses temperature for randomization in gating games too and does *not* play them with particularly high visits either.

**Comment by SHKD13** [comment]
@lightvector 
Thanks, that works! May I ask few things about the arguments for Git Bash? Cannot get the clue with the arguments for:
**a)** setting the filename extension for all the files extracted by Git. They all are nameless. I'd like to set the **.sgf** extension default for all of them.
**b)** extract plus filter the games: **19x19** games only and the ones with **modeM2=0**. Cannot set the right arguments in Git.

I'd be very grateful for help! :)

**Comment by lightvector** [comment]
Quick reply from email here - I'm assuming Git Bash is a wrapper around the
linux Bash shell that Git provides and has made work on Windows. I've never
used it myself. But if that's the case... for #a have you investigated the
other thread I linked you about how to do it in Linux? One of the answers
specifies an argument you can pass to split to specify an additional
extension to append.

For #b, try seeing if you have the "grep" command. If you do, then the next
thing would be to Google for an online tutorial on how to use Linux grep.
Grep is an extremely useful command line tool. :)

Other alternatives would be to use something like Windows Powershell (which
I'm sure is also capable of doing the job, I just don't know how to use it)
or even something silly like writing a python script to loop over all files
and save each line to a new file, checking if the string contains the
appropriate SZ[19] and such. If you do know how to code python but all this
Bash stuff still isn't working for you.

**Comment by SHKD13** [comment]
I've got Windows 10, not Linux, that's what i did not check it :) I'll try everything you advise me, tnx one more time! 
I can see that Windows PowerShell has analog of Linux grep command: https://www.itechtics.com/using-findstr-windows/
I'll check it out too. Unfortunately, I can't "speak" python yet))

**Comment by SHKD13** [comment]
@lightvector 
I'm beginning to feel myself as a real wildman :) Now I can give the extension to the extracted files and filter them by Windows PowerShell **findstr** command. 

![Screenshot_25](https://user-images.githubusercontent.com/39368053/59760235-84ac1600-929a-11e9-9b86-9a1d4362cd7a.jpg)
![Screenshot_26](https://user-images.githubusercontent.com/39368053/59760515-2fbccf80-929b-11e9-90d0-71c53981057c.jpg)

But **I can't separate these filtered files to another folder** by the command line :( They all still staying unfiltered at current folder. _Is it possible at all?_ Even Google can't help my ignorance.
Sorry for being such a noob! I'm trying to educate myself in this new computer science area)) Hope, in a close future I'll be able to help the KataGo project more significatly than by the storage place and these questions :)

**Comment by lightvector** [comment]
Sounds like you want to learn how to use pipes: https://helpdeskgeek.com/how-to/redirect-output-from-command-line-to-text-file/
So presumably you would run findstr in the mode where it outputs the actual matching lines (rather than only listing files that match) BEFORE you've split out into separate files, and redirect its output to a new file, so the new file only contains the filtered games, and then split the new file into separate files.

Alternatively, you can learn how to for-loop over files in a given directory: https://stackoverflow.com/questions/138497/iterate-all-files-in-a-directory-using-a-for-loop
This will let you specify a series of commands that will get executed *separately, once for every file in the loop*. And those commands can do whatever you want - move the file, rename it.

I'm not familiar with all the ways you do this in Windows command line, since I don't use it a lot. I am very familiar with how you do it in Bash, it's completely basic shell scripting skills. If Git Bash is a sufficiently large subset of Bash and associated Linux shell utilities that it allows all of these things, it would look something like:

`
OUTPUT_DIR="path/to/where/you/want/the/results"
mkdir -p "$OUTPUT_DIR"
for FILE in path/to/the/sgfs/files/*.sgfs
do
   echo Processing "$FILE"
   #Filter and split into sgf files and dump them into the CURRENT directory
   grep 'SZ\[19\]' "$FILE" | grep 'modeM2=0' | split -l 1 --additional-suffix "-$FILE".sgf
   #Move the results into the desired output directory
   mv *-"$FILE".sgfs "$OUTPUT_DIR"/
done
`
I have not tested this script, there may be typos and bugs making it not work, this is just me writing it off the top of my head.

**Comment by SHKD13** [comment]
Unfortunately, none of first two options not working for me. The files I redirected from findstr contain only the text like "**C:\Users\Ruslan\Desktop\Ruslan\xaa.sgf**" inside instead of moves.
And I cannot run the script with Git Bash.

![Screenshot_30](https://user-images.githubusercontent.com/39368053/59927323-dee8da80-9444-11e9-8ff2-f32e47df59e7.jpg)

Probably I'm just not good enough in computer science to have a chance to create a database with KataGo 19x19 games and study its Opening ideas :( Definitely, I picked the wrong profession!

**Comment by lightvector** [comment]
For findstr, are you still providing the "/M" argument? According to
https://en.wikipedia.org/wiki/Findstr the "/M" argument makes it so that it
prints the filename instead of the line that matched. So if that's what
you're doing, your redirected files would of course only contain filenames
instead of sgf lines.

**Comment by SHKD13** [comment]
@lightvector 
Thank you very much! Finally I made it work with your help :) Here is the final loop for filter the goban size + redirect the output: **findstr "SZ\[19\]" "C:\Users\Ruslan\Desktop\Ruslan\*" > C:\Users\Ruslan\Desktop\Lord\Ruslan.sgfs**
Now the road for fuseki comparison is open))

By the way, may I ask how you evaluate the KataGo game strength relatively to other open source AI? Do you play test matches against ELF, Leela Zero and MiniGo, or you are able to rely on Elo rating assessment?

**Comment by lightvector** [comment]
Yay, glad you figured how to make it work.

I play games between a wide range of different versions including both LZ and ELF and KataGo itself, with different random pairings between all those versions, and then feed all the game results into a Bayesian maximum likelihood Elo solver. Here's an example tool that does it, although I don't actually use this one myself: https://www.remi-coulom.fr/Bayesian-Elo/. The Elo values generated are usually quite reliable because they are based around games against a wide range of opponents and between widely separated neural net versions. 

When you say "Rely on Elo rating assessment" I think your understanding of things is incorrect. 

Elo is NOT an alternative choice to doing test matches. You ALWAYS have to have test matches, there's not really a such thing as "doing Elo ratings _instead_ of test matches", because test matches are the only good way to measure strength. **Elo is simply a mathematical way to summarize the result of those test matches**.

The key thing to understand is that **because Elo ratings are a summary of test matches, they are only as good as the quality of the test matches**.

You can decide that your "test matches" are the same matches that you use for gating. But those matches are very biased for measuring the strength of the neural net versions that you kept because those matches were how you selected the neural net versions to keep in the first place. And they include no matches between widely separated versions or against other opponents. Therefore, Elos using those matches will be very biased and bad at measuring strength between widely separated versions or other opponents.

Or you can run fresh unbiased test matches against opponents like ELF and LZ and also include lots of matches between widely separated versions. Then, Elo ratings using those matches will be unbiased and be good at measuring strength against those opponents and against widely separated versions.

Does that make sense?

**Comment by SHKD13** [comment]
Absolutely does! I meant Elo rsting based on selfplay games only, like Leela Zero's one. I can see thar my understanding of this subject was not clear enough))

Is it possible to take a look at these KataGo test games versus LZ and ELF? Or maybe just the stats, if the games itself takes too much of your time))

**Comment by Friday9i** [comment]
I'm currently running some test matches of LZ vs KataGo, and I intend to play more of them ; -)
My first results are comparable to those of @lightvector : KataGo is ~ LZ200 strength at equal 1600 visits _when using 16 threads_. When using 1 thread (numSearchThreads = 1), it's ~8x slower but significantly stronger, with these parameters KataGo is ~LZ229 strength (which is ~150 stronger than LZ200).
From now, I'll keep numSearchThreads = 16, which is a good compromise between speed and strength on my RTX2080 GPU.
I did not test KataGo vs ELF yet.
And I tested KataGo vs LZ229 at lower visits: it seems that LZ suffers much more from frequent failed ladders, but no quantitative results yet, just a feeling. I'll publish results when they are well established.

**Comment by hubusha** [comment]
What is the computational amount of its self-games?  What are the quality of sgfs compared with LEELA's?

**Comment by lightvector** [comment]
@hubusha - I forget exactly, something like 4 million games (including a mix of many smaller board sizes, 19x19 is only a fraction of the games). Quality, I have no idea, except for the fact that they were enough to train KataGo to the level it's at now. Re-posting link from above, all the training games are available here for you to check out and see for yourself:
https://d3dndmfyhecmj0.cloudfront.net/g104/index.html

**Comment by lightvector** [comment]
Closing this thread since it looks like this is handled. Feel free to open another one if there are further questions.
