### ISSUE TITLE
Clarification of the KataGo behavior after reading SGF file

### ISSUE THREAD

**Issue by smolendawid** [lightvector/KataGo#198]
I've got a non-typical usage of KataGo. I'd like to 
- analyze the photo of Go game
- create some sensible guess of the current game state
- generate the proper SGF file
- pass it to KataGo and get the best move for the given color.

To do it, as far as I understand, I need to take care of the last few moves, to generate them properly in SGF file. 

1. Assuming I'm able to restore the correct SGF file, should it be enough for KataGo to generate a good move? 
2. Can I generate a move for both black and white despite of SGF state?
3. What are the risks if I restore a wrong SGF (e.g. switch first black move with the last for some reason)?
4. If I input 'pass' move in any moment of the game in SGF, does it impact KataGo in some bad way?

Thank you

**Comment by lightvector** [comment]
Why do you want to generate an SGF file for KataGo at all? How about taking a look at this:
https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

You can specify an `initialStones` and `initialPlayer` and leave `moves` as an empty array, so you don't have to make up a fake and probably bad move history.

If you still want to SGF, then I would expect your photo analysis to also behave simply construct an initial position with the stones on the board without making up a move history. You should use the [AB](https://www.red-bean.com/sgf/properties.html#AB) and [AW](https://www.red-bean.com/sgf/properties.html#AW) tags to construct the position, and use [PL](https://www.red-bean.com/sgf/properties.html#PL) to set the initial player, all within root node of the SGF, with no passes or any other moves aside from this initial setup. Making up a fake move history would be silly.

**Comment by smolendawid** [comment]
Thanks! I think Anaysis Engine would be a good solution, but I'd like to stick with GTP right now. 

Because of lockdown in my country, I just started to work on my project that allows playing with KataGo on a real board:

https://github.com/smolendawid/Gomrade

It's an early version but I hope to finish the draft in a few days.

I'm not familiar with Go programming world yet, therefore I missed AB and AW somehow. I think it will help me, maybe that's what I'm looking for.

Nevertheless,  I'm still not how to do it in the best way. 

At the moment there are some mistakes in the real games I play. I'm working on a tool that will be able to track the game state, but it's not that easy. (When the interpretation of the board stones is mistaken, the bad move is generated, and then we want to undo it and understand it's undo) And the most important fact is that I'd like my project to "allow" illegal moves - it's a real physical board and we're not able to stop the cheating I think.

Considering the details above, would you please share your thoughts?

**Comment by lightvector** [comment]
KataGo's GTP engine obeys the GTP specification, so if you are using GTP you must provide legal SGF files or sequences of moves, including not providing illegal moves, such as placing stones where stones already exist, or failing to remove stones when they rightfully should be captured, or things like that.

If you think you can _accurately_ track the move history, then by all means, do that. If your vision and camera system is unable to do that and can only tell what the current game state is but cannot necessarily determine history as stones are added/captured, then you of course you should not attempt to make up a fake history (like playing all black stones first, then playing all white stones) - instead you should use the AB and AW properties to simply specify a position in a history-less way on each new turn, and use PL to say which player should play next.

Making up a fake history will affect KataGo's output, since it does take into account the previous moves, and in all of its training all such history moves were always the correct previous moves, rather than illegal or out of order. Probably the effect will be not too large, particularly with high playouts, but if using only low playouts (such as on weaker hardware) there is no firm guarantee that the net behaves well, so why take the risk? Just specify the position in a historyless way if you think you can't be accurate or if you want your system to be able to tolerate literally impossible game histories - such as if the players rearrange the stones mid-game and then continue playing from there, or if they forget to capture stones, or if an illegal ko takeback occurs, etc.

**Comment by lightvector** [comment]
Also note that the "correct" behavior is sort of undefined if you attempt to use AB and AW to specify a position where there are zero liberties on a group sitting on the board. If you want to be robust should probably have your own board representation, separate from KataGo, where you do a check that all groups parsed by your camera have at least one liberty, and if this is false, then you probably want to report a human-friendly error and refuse to attempt to feed the position to any bot, since there is no definite guarantee on what any bot will do faced with such a situation.

Everything that I've said applies in general to GTP bots by the way. GTP is indeed a pretty sensible way to try to work things, and if you're going that way, I see no reason why you should want to depend on any KataGo-specific behavior here - just follow good practices like above where you validate what you're about to provide to the bot, and provide a move history only when you can guarantee its legality and accuracy and then it has nothing to do with KataGo - you could swap out to any other properly-implemented GTP bot and have it work just as well.

**Comment by smolendawid** [comment]
Thank you a lot @lightvector. I really appreciate your help, you clarified a lot to me. I will work with GTP, and for corner cases, I'll try to prioritize the requirements of KataGo, because I think it's the greatest engine right now.
