### ISSUE TITLE
Difference between cuda version and opencl version

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#205]
Sorry for the elementary question.

Is the difference between cuda version and opencl version of katago only in terms of search speed?
In other words, if you set an upper limit on the number of searches and set the time to exhaust the number of searches, will both be the same strength?

Around me, I've heard many people say that the opencl version is stronger, so I asked such a question.

**Comment by lightvector** [comment]
Yes, if CUDA is also using FP32, then the only difference is speed. The two of them compute identical values out to the 7th or 8th decimal place. If the winrate or policy differs by 0.0000001 that will obviously make no practical difference, so they are the same. On most GPUs if you only have FP32, then OpenCL is faster so no reason to use CUDA.

If CUDA is using FP16 tensor cores (tensor cores can be used on RTX 2080 or similar super-top nvidia gpus) then it will be roughly a doubling of speed compared to CUDA FP32. Then since it's only using 16-bit floats, the neural net evaluations and policy will be a bit more noisy since they have lower precision. So there is a difference besides speed here, but it should be very small, and FP16 being faster than FP32 should more than make up for it by being twice as fast and being able to do more visits or playouts if you are using fixed time instead of fixed visits or playouts.

One other major detail: for any fixed number of visits or playouts, the more **threads** you use, the weaker the strength. Unlike all the above, threads have a major impact on strength, they are the second most important thing, right after playouts or visits. This is why you should always report the number of threads you use in any test - it affects the strength even if visits or playouts are constant.

Example: if you have RTX2080 and you do 1000 playouts OpenCL with 32 threads against 1000 playouts CUDA FP16 with 128 threads, for example, then the OpenCL will win more often. This is not because of any difference between OpenCL and CUDA, and and mostly not because of FP16 either. It's because of **32 vs 128 threads**. Presumably the reason you use 128 threads with FP16 (or whatever the benchmark tool tells you is optimal threads) is because 128 threads gets you better performance - the 1000 playouts would much faster so if you were using fixed time instead, you could get much more than 1000 in the same time, so it would be stronger, but fixed at only 1000 it will be weaker. You could always make the threads match, disable FP16, and then you lose all performance benefits, but now they are equal again.

Does that make sense?

**Comment by hope366** [comment]
Thank you for your prompt and kind support.

I am using RTX 2060. CUDA is much faster than OpenCL. I evaluated only the visits / s number, and was indifferent to the number of threads. In the benchmark test, if the numbers of visits / s are minute, the smaller the number of threads, the stronger.


numSearchThreads =  1: 10 / 10 positions, visits/s = 239.37 nnEvals/s = 216.75 nnBatches/s = 216.75 avgBatchSize = 1.00 (33.4 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 247.77 nnEvals/s = 225.56 nnBatches/s = 224.33 avgBatchSize = 1.01 (32.3 secs) (EloDiff +7)
numSearchThreads =  4: 10 / 10 positions, visits/s = 483.01 nnEvals/s = 431.82 nnBatches/s = 216.54 avgBatchSize = 1.99 (16.6 secs) (EloDiff +244)
numSearchThreads =  6: 10 / 10 positions, visits/s = 713.65 nnEvals/s = 621.28 nnBatches/s = 208.51 avgBatchSize = 2.98 (11.3 secs) (EloDiff +382)
numSearchThreads =  8: 10 / 10 positions, visits/s = 697.92 nnEvals/s = 621.64 nnBatches/s = 156.71 avgBatchSize = 3.97 (11.6 secs) (EloDiff +368)
numSearchThreads = 12: 10 / 10 positions, visits/s = 872.42 nnEvals/s = 784.75 nnBatches/s = 132.42 avgBatchSize = 5.93 (9.3 secs) (EloDiff +441)
numSearchThreads = 16: 10 / 10 positions, visits/s = 1010.92 nnEvals/s = 911.44 nnBatches/s = 115.60 avgBatchSize = 7.88 (8.1 secs) (EloDiff +488)
numSearchThreads = 24: 10 / 10 positions, visits/s = 1095.29 nnEvals/s = 1003.46 nnBatches/s = 78.65 avgBatchSize = 12.76 (7.5 secs) (EloDiff +502)
numSearchThreads = 36: 10 / 10 positions, visits/s = 1185.07 nnEvals/s = 1103.04 nnBatches/s = 51.52 avgBatchSize = 21.41 (7.0 secs) (EloDiff baseline)
numSearchThreads = 48: 10 / 10 positions, visits/s = 1213.29 nnEvals/s = 1152.70 nnBatches/s = 40.68 avgBatchSize = 28.33 (7.0 secs) (EloDiff -15)
numSearchThreads = 60: 10 / 10 positions, visits/s = 1224.52 nnEvals/s = 1181.04 nnBatches/s = 34.21 avgBatchSize = 34.52 (7.0 secs) (EloDiff -35)
numSearchThreads = 132: 10 / 10 positions, visits/s = 1233.60 nnEvals/s = 1219.56 nnBatches/s = 21.33 avgBatchSize = 57.17 (7.5 secs) (EloDiff -176)


The katago-cuda benchmark test looks like this. Threads larger than 132 are similar numbers so I usually use 132.

If you only want to search for the same time, do you feel that 16 to 36 is the strongest?

Else, nnMaxBatchSize = 132
nnCacheSizePowerOfTwo = 20
nnMutexPoolSizePowerOfTwo = 16
# mutexPoolSize = 16384
You have set it like this. Is there anything you need to improve regarding strength?

**Comment by lightvector** [comment]
On your hardware, 132 threads does look like it's too much. 36 or 48 has almost the same performance, but will be stronger due to using fewer threads.

It looks like you pasted two different benchmark runs together so the "EloDiff" numbers between them are inconsistent because they are two different baselines. But the entire point of the "EloDiff" numbers in the benchmark is that they are an estimate of the total impact on strength of both speed and threads together.

Try running
`./katago benchmark -model YOUR_MODEL.bin.gz -config YOUR_CONFIG.cfg -tune -time TIME -v 3000`
where `TIME` is the number of seconds you want KataGo to be strongest for, such as the number of seconds you often wait for during analysis or in matches (this is used in the estimation of the negative impact of threads - high threads is most harmful for very short searches)

For example, 5 or 10 seconds would be a good general-purpose number:
`./katago benchmark -model YOUR_MODEL.bin.gz -config YOUR_CONFIG.cfg -tune -time 5 -v 3000`

And then with the `tune` flag it will automatically suggest the number of threads to use that balances better speed with not having too many threads.

**Comment by lightvector** [comment]
And please help other people you come across know that threads matter, they are the immediate next thing you should think of after raw performance or playouts or visits.

It's silly for people to be fussing over CUDA vs OpenCL if they are mis-tuning this huge other major factor. :)

**Comment by lightvector** [comment]
> It's silly for people to be fussing over CUDA vs OpenCL if they are mis-tuning this huge other major factor. :)

That is, aside from seeing which has the better performance and simply picking the one that works better with their GPU (choosing between the two *can* be a big speed difference), fussing about if there is some other phantom difference between the two _besides speed_ while ignoring the major impact of threads.

**Comment by hope366** [comment]
I've put together the execution from 1 to 24 and the execution from 36 to 132. Sorry for making it hard to see.

./katago benchmark -model YOUR_MODEL.bin.gz -config YOUR_CONFIG.cfg -tune -time 5 -v 3000

I tried to run.

C:\baduk\lizzie>katago benchmark -model 20x256.bin.gz -config gtp.cfg -tune -time 5 -v 3000
2020-04-21 01:02:10+0900: Loading model and initializing benchmark...
WARNING: Your nnMaxBatchSize is hardcoded to 16, ignoring it and assuming it is >= threads, for this benchmark.
2020-04-21 01:02:10+0900: nnRandSeed0 = 8569346161061287098
2020-04-21 01:02:10+0900: After dedups: nnModelFile0 = 20x256.bin.gz useFP16 auto useNHWC auto
2020-04-21 01:02:10+0900: Cuda backend: Found GPU GeForce RTX 2060 memory 6442450944 compute capability major 7 minor 5
2020-04-21 01:02:10+0900: Cuda backend: Model version 8 useFP16 = true useNHWC = true
2020-04-21 01:02:10+0900: Cuda backend: Model name: g170-b20c256x2-s3761649408-d809581368

2020-04-21 01:02:12+0900: Loaded config gtp.cfg
2020-04-21 01:02:12+0900: Loaded model 20x256.bin.gz

Testing using 3000 visits.

Your GTP config is currently set to cudaUseFP16 = auto and cudaUseNHWC = auto

Your GTP config is currently set to use numSearchThreads = 16
Automatically trying different numbers of threads to home in on the best:

2020-04-21 01:02:12+0900: nnRandSeed0 = 12548376389706790299
2020-04-21 01:02:12+0900: After dedups: nnModelFile0 = 20x256.bin.gz useFP16 auto useNHWC auto
2020-04-21 01:02:13+0900: Cuda backend: Found GPU GeForce RTX 2060 memory 6442450944 compute capability major 7 minor 5
2020-04-21 01:02:13+0900: Cuda backend: Model version 8 useFP16 = true useNHWC = true
2020-04-21 01:02:13+0900: Cuda backend: Model name: g170-b20c256x2-s3761649408-d809581368


Possible numbers of threads to test: 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32,

numSearchThreads =  5: 10 / 10 positions, visits/s = 627.47 nnEvals/s = 534.96 nnBatches/s = 214.45 avgBatchSize = 2.49 (47.9 secs)
numSearchThreads = 12: 10 / 10 positions, visits/s = 977.72 nnEvals/s = 829.95 nnBatches/s = 139.11 avgBatchSize = 5.97 (30.8 secs)
numSearchThreads = 10: 10 / 10 positions, visits/s = 886.20 nnEvals/s = 759.50 nnBatches/s = 152.71 avgBatchSize = 4.97 (34.0 secs)
numSearchThreads = 20: 10 / 10 positions, visits/s = 1133.26 nnEvals/s = 953.53 nnBatches/s = 95.20 avgBatchSize = 10.02 (26.6 secs)
numSearchThreads = 16: 10 / 10 positions, visits/s = 1058.94 nnEvals/s = 902.96 nnBatches/s = 113.41 avgBatchSize = 7.96 (28.5 secs)
numSearchThreads = 24: 10 / 10 positions, visits/s = 1153.60 nnEvals/s = 987.22 nnBatches/s = 78.73 avgBatchSize = 12.54 (26.2 secs)
numSearchThreads = 32: 10 / 10 positions, visits/s = 1235.53 nnEvals/s = 1064.41 nnBatches/s = 55.36 avgBatchSize = 19.23 (24.5 secs)


Optimal number of threads is fairly high, tripling the search limit and trying again.

2020-04-21 01:05:53+0900: nnRandSeed0 = 11385891603708524264
2020-04-21 01:05:53+0900: After dedups: nnModelFile0 = 20x256.bin.gz useFP16 auto useNHWC auto
2020-04-21 01:05:54+0900: Cuda backend: Found GPU GeForce RTX 2060 memory 6442450944 compute capability major 7 minor 5
2020-04-21 01:05:54+0900: Cuda backend: Model version 8 useFP16 = true useNHWC = true
2020-04-21 01:05:54+0900: Cuda backend: Model name: g170-b20c256x2-s3761649408-d809581368


Possible numbers of threads to test: 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 96,

numSearchThreads =  6: 10 / 10 positions, visits/s = 722.72 nnEvals/s = 614.44 nnBatches/s = 205.46 avgBatchSize = 2.99 (41.6 secs)
numSearchThreads = 48: 10 / 10 positions, visits/s = 1286.36 nnEvals/s = 1127.92 nnBatches/s = 36.14 avgBatchSize = 31.21 (23.7 secs)
numSearchThreads = 64: 10 / 10 positions, visits/s = 1313.92 nnEvals/s = 1149.19 nnBatches/s = 29.86 avgBatchSize = 38.49 (23.3 secs)
numSearchThreads = 40: 10 / 10 positions, visits/s = 1281.14 nnEvals/s = 1090.55 nnBatches/s = 41.86 avgBatchSize = 26.05 (23.7 secs)


Ordered summary of results:

numSearchThreads =  5: 10 / 10 positions, visits/s = 627.47 nnEvals/s = 534.96 nnBatches/s = 214.45 avgBatchSize = 2.49 (47.9 secs) (EloDiff baseline)
numSearchThreads =  6: 10 / 10 positions, visits/s = 722.72 nnEvals/s = 614.44 nnBatches/s = 205.46 avgBatchSize = 2.99 (41.6 secs) (EloDiff +50)
numSearchThreads = 10: 10 / 10 positions, visits/s = 886.20 nnEvals/s = 759.50 nnBatches/s = 152.71 avgBatchSize = 4.97 (34.0 secs) (EloDiff +115)
numSearchThreads = 12: 10 / 10 positions, visits/s = 977.72 nnEvals/s = 829.95 nnBatches/s = 139.11 avgBatchSize = 5.97 (30.8 secs) (EloDiff +148)
numSearchThreads = 16: 10 / 10 positions, visits/s = 1058.94 nnEvals/s = 902.96 nnBatches/s = 113.41 avgBatchSize = 7.96 (28.5 secs) (EloDiff +169)
numSearchThreads = 20: 10 / 10 positions, visits/s = 1133.26 nnEvals/s = 953.53 nnBatches/s = 95.20 avgBatchSize = 10.02 (26.6 secs) (EloDiff +187)
numSearchThreads = 24: 10 / 10 positions, visits/s = 1153.60 nnEvals/s = 987.22 nnBatches/s = 78.73 avgBatchSize = 12.54 (26.2 secs) (EloDiff +185)
numSearchThreads = 32: 10 / 10 positions, visits/s = 1235.53 nnEvals/s = 1064.41 nnBatches/s = 55.36 avgBatchSize = 19.23 (24.5 secs) (EloDiff +197)
numSearchThreads = 40: 10 / 10 positions, visits/s = 1281.14 nnEvals/s = 1090.55 nnBatches/s = 41.86 avgBatchSize = 26.05 (23.7 secs) (EloDiff +196)
numSearchThreads = 48: 10 / 10 positions, visits/s = 1286.36 nnEvals/s = 1127.92 nnBatches/s = 36.14 avgBatchSize = 31.21 (23.7 secs) (EloDiff +182)
numSearchThreads = 64: 10 / 10 positions, visits/s = 1313.92 nnEvals/s = 1149.19 nnBatches/s = 29.86 avgBatchSize = 38.49 (23.3 secs) (EloDiff +161)


Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search:
numSearchThreads =  5: (baseline)
numSearchThreads =  6:   +50 Elo
numSearchThreads = 10:  +115 Elo
numSearchThreads = 12:  +148 Elo
numSearchThreads = 16:  +169 Elo
numSearchThreads = 20:  +187 Elo
numSearchThreads = 24:  +185 Elo
numSearchThreads = 32:  +197 Elo (recommended)
numSearchThreads = 40:  +196 Elo
numSearchThreads = 48:  +182 Elo
numSearchThreads = 64:  +161 Elo

If you care about performance, you may want to edit numSearchThreads in gtp.cfg based on the above results!
WARNING: Your nnMaxBatchSize is hardcoded to 16, recommend deleting it and using the default (which this benchmark assumes)
If you intend to do much longer searches, configure the seconds per game move you expect with the '-time' flag and benchmark again.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp.cfg

From this result, 32 threads seems to be the most balanced number, so I will apply 32 threads.

Thank you for telling me something important.

**Comment by lightvector** [comment]
No prob, hope that helped. Please also notice this message in the output:

**WARNING: Your nnMaxBatchSize is hardcoded to 16, recommend deleting it and using the default (which this benchmark assumes)**

You shouldn't need to be specifying this parameter, unless you're your own careful testing separate from that benchmark.

**Comment by hope366** [comment]
I tested it with 16 threads and nnMaxBatchSize = 16, but 32 threads was optimal, so I changed both to 32.

We sincerely apologize to the developers for making this connection.

**Comment by lightvector** [comment]
Again no problem, glad to help. :)

**Comment by hope366** [comment]
For now, close it.
We would like to express our deep gratitude to lightvector.
