### ISSUE TITLE
Startup message

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#21]
How about writing a startup message to STDERR after initialization so that GUIs know when to begin sending GTP commands? Though I couldn't reproduce the problem by myself, GUIs may need to wait for initialization of the engine in a certain situation (https://github.com/kaorahi/lizgoban/issues/4).

In addition, Leela Zero shows the network size in initialization. It is also convenient for GUIs.

**Comment by lightvector** [comment]
Thanks for the suggestion! 
Waiting for a stderr to know when to begin sending commands is a bit strange and nonstandard, and I'd strongly recommend GUIs not do this - for example even GnuGo doesn't print anything to stderr when you start it up with GTP. More reliable would be to do something like a "protocol_version" or "name" to see if the engine will respond.

Nonetheless, since it's nice at least for testing GTP on the command line, I went ahead and pushed an updated version that will display a startup message, which can also be enabled/disabled in the gtp config. Hope that helps! (both opencl and master branches and the v1.1 release should now be updated)

**Comment by lightvector** [comment]
For reference: https://github.com/lightvector/KataGo/commit/e37daf3d05bed481b8f1f1b7ecd051719ba03caa
