### ISSUE TITLE
How do I evaluate relative competitiveness of two configurations?

### ISSUE THREAD

**Issue by uduse** [lightvector/KataGo#214]
I am implementing a different searching algorithm for KataGo and I want to know if it actually has a better performance given the same model. In other words, I will have two copies of KataGo source code, one modified, one original, and I want to know which one is better. It seems that the current `katago match` does not support this. What's the best way to achieve this? Maybe I have to modify the same copy but toggle different algorithms with some configuration parameter?

**Comment by lightvector** [comment]
You could do this, but if the algorithm you are testing has a substantial effect on the way the search works, or on the performance or threading, then you might prefer to have two entirely separate processes so that they also don't share neural net cache or symmetries or threads.

In that case, you should just run them as completely independent GTP bots and do the same thing as if it were two entirely independently written Go bots - use any normal external match or tournament script that works with GTP.

**Comment by uduse** [comment]
@lightvector Thank you for your quick reply. I agree that it might be better for me to modify a separate codebase. I poked around a bit and didn't find any good choice for a tournament manager. Do you have any recommendations?

**Comment by lightvector** [comment]
gogui-twogtp and gomill/ringmaster are the two normal options I know of.

**Comment by lightvector** [comment]
Closing this for now. Let me know if you have any other questions!

**Comment by uduse** [comment]
Yeah I've been using gotui-twogtp now, thanks a lot!
