### ISSUE TITLE
Strange behaviour from kata-genmove_analyze

### ISSUE THREAD

**Issue by bernds** [lightvector/KataGo#216]
The current behaviour of kata-genmove_analyze, printing "=" immediately to signal that the command completed, seems strange (bordering on broken). It differs from all normal GTP commands that produce a response, and it means that you can't just substitute this command for a normal genmove.
The following seems to both simplify things and improve the behavior. This is what I would want to use the command in q5go - are there any other tools that already rely on current behaviour?

```
diff --git a/cpp/command/gtp.cpp b/cpp/command/gtp.cpp
index 05688c7..08bd5f4 100644
--- a/cpp/command/gtp.cpp
+++ b/cpp/command/gtp.cpp
@@ -728,7 +728,7 @@ struct GTPEngine {
     bool isLegal = bot->isLegalStrict(moveLoc,pla);
     if(moveLoc == Board::NULL_LOC || !isLegal) {
       responseIsError = true;
-      response = "genmove returned null location or illegal move";
+      response = "resign";
       ostringstream sout;
       sout << "genmove null location or illegal move!?!" << "\n";
       sout << bot->getRootBoard() << "\n";
@@ -833,9 +833,6 @@ struct GTPEngine {
       maybeStartPondering = true;
     }
 
-    if(args.analyzing) {
-      response = "play " + response;
-    }
     return;
   }
 
@@ -1887,11 +1884,6 @@ int MainCmds::gtp(int argc, const char* const* argv) {
         bool debug = false;
         bool playChosenMove = true;
 
-        //Make sure the "equals" for GTP is printed out prior to the first analyze line, regardless of thread racing
-        if(hasId)
-          cout << "=" << Global::intToString(id) << endl;
-        else
-          cout << "=" << endl;
         engine->genMove(
           pla,
           logger,searchFactorWhenWinningThreshold,searchFactorWhenWinning,
@@ -1901,17 +1893,6 @@ int MainCmds::gtp(int argc, const char* const* argv) {
           response,responseIsError,maybeStartPondering,
           args
         );
-        //And manually handle the result as well. In case of error, don't report any play.
-        suppressResponse = true;
-        if(!responseIsError) {
-          cout << response << endl;
-          cout << endl;
-        }
-        else {
-          cout << endl;
-          if(!loggingToStderr)
-            cerr << response << endl;
-        }
       }
     }


```

**Comment by lightvector** [comment]
I think the current behavior is correct, unless you're finding it behaves even yet differently than I intended it to. But I think nothing you've said so far is unintended. See [Sabaki docs](https://github.com/SabakiHQ/Sabaki/blob/master/docs/guides/engine-analysis-integration.md) for the origin of this class of commands.

The [KataGo GTP documentation](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md) was also written with the current behavior  in mind as the expected behavior. I should improve the wording to be much more precise though - I'll push some clarifications.

To elaborate:

Like lz-analyze or kata-analyze:
* It will immediately output an equals sign followed by periodic information at approximately the interval that you have specified, as the search is ongoing.

Unlike lz-analyze or kata-analyze, it behaves like any other normal synchronous commands that any GTP controller should be capable of handling:
* Further controller input has no effect until the command completes, the behavior does not vary in response to new input.
* The command will terminate on its own like any normal command, instead of requiring additional asynchronous interaction from the controller to cause it to terminate.
* It only pauses in ways that any standard GTP controller should already be able to tolerate.

To elaborate on the last bullet - in GTP, the equals sign does NOT signal that a response is complete. Rather, it is the double newline that completes a response. Additionally, see section 2.8 in the [GTP spec](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00036000000000000000) - engines are explicitly allowed to pause "while sending a response". So for example, it should be allowed for an engine to write the equals sign and part of a response, pause for a while, and then write the rest of the response, and only finally write the double newline that when actual completion is achieved.

From this perspective, this command is no different than any other multi-line-output command that might pause in the middle, and therefore unlike lz-analyze or kata-analyze it can be considered an entirely normal GTP command that conforms to the protocol. A controller that waits for a double newline before attempting to parse any of the response will have no trouble.

*Optionally* of course, a controller may attempt to start parsing the response before seeing the double newline that signals that the response is complete. So a cleverly-written controller can also display analysis stats about the bot's current thinking in an ongoing way while the bot is thinking. But this is entirely up to the controller.

**Comment by lightvector** [comment]
And I guess, to be a bit more explicit - the last bit, where a cleverly written controller can display live analysis stats while the bot is thinking - is presumably the reason for the design of the command to work this way, and KataGo's "kata-" version of the command simply follows the same semantics. I don't know who originally designed these semantics, but It's actually quite clever the way it enables live-update of stats using only a single command, but is still compatible with vanilla GTP.

Does that help? Definitely happy to fix things if you notice a way it's behaving that differs even the intention above, let me know. :)

**Comment by bernds** [comment]
I didn't know about the double-newline convention. I figured the "info" dumps were just OOB information that a program using analyze or similar commands would know to interpret, especially since the analyze command gives the appearance of having completed after the "=" (given that the program reacts to new input).
I guess this can be closed.
