### ISSUE TITLE
model found unsupported version 8

### ISSUE THREAD

**Issue by kingvagabond** [lightvector/KataGo#217]
I tried the latest weight files (all three) but met this error:

C:\Users\Administrator\Desktop\Lizzie>.\katago\katago.exe gtp -model katanetwork.gz -config katago-gtp10.cfg
KataGo v1.2
Uncaught exception: Error loading or parsing model file katanetwork.gz: g170-b20c256x2-s3761649408-d809581368: **model found unsupported version 8**

How to solve this issue please?

**Comment by lightvector** [comment]
The version of KataGo that ships with Lizzie is extremely outdated. Lizzie development has been stalled for a while, so sadly nobody has the ability to update it within Lizzie. You should download the newest release of KataGo manually from the KataGo's [releases page]( https://github.com/lightvector/KataGo/releases) which I presume is where you downloaded those model files from as well.

**Comment by lightvector** [comment]
Any updates? Did this fix it for you?

**Comment by lightvector** [comment]
Lizzie has since been updated with new versions of things, so I presume everything should work now even if you haven't worked out how to set up KataGo separately. 
https://github.com/featurecat/lizzie/releases

Hop into the discord chat and ask for help in #help if you want more help setting things up:
https://discord.gg/bqkZAz3
