### ISSUE TITLE
About the Handicap Game

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#226]
Hello, I have a question about the handicap game.

DynamicPlayoutDoublingAdvantageCapPerOppLead = 0.04
playoutDoublingAdvantagePla = WHITE

This item has been added since v1.3 and was uncommented until v1.3.5, but since v1.4.0 it has been uncommented and the number has been changed from 0.04 to 0.045.

I think the setting is about whether or not you play offensively in a handicap game.

Why did you make the change from v1.4.0?

**Comment by lightvector** [comment]
Thanks, I forgot to put release notes for that, I'll do so shortly.

The reason is to simplify the configuration for users. You can comment out or delete all of those values from your config now, and KataGo will simply go with default behavior - which is to play a bit more aggressively in handicap games. I changed it up to 0.045 simultaneously with a change that KataGo made internally on how it evaluates how much handicap stones are worth, so 0.045 is now the default value if you don't specify. You can specify it and explicitly set to 0 if you don't want it though.

**Comment by lightvector** [comment]
The change internally made KataGo value handicap stones slightly less in some cases for the purpose of adjusting its aggression, so the change from 0.04 to 0.045 as default was partially to compensate that, but also just because I thought maybe that would be a little better. Of course, I could always be convinced to change that default value (or any other default values!) if you have strong test data showing that a different value is more effective!

**Comment by hope366** [comment]
Thank you for your quick response.
DynamicPlayingDownloadAdvantagePer OppLead = 0.045
We want to adjust this value to see how katago behaves.
But katago is too strong and it may be difficult to feel the change but I'll try.
Thank you very much.
I'd like to close the issue.
