### ISSUE TITLE
Cuda 10.2 not supported?

### ISSUE THREAD

**Issue by lj739** [lightvector/KataGo#235]
I can't run katago on a machine with cuda10.2, any ideas?

**Comment by lightvector** [comment]
Obviously, it's very hard to give ideas when there is no other information about the error message, operating system, hardware, etc...

Cuda 10.2 should be perfectly fine if you compile KataGo on your own. Otherwise, you might try downgrading CUDA, or having multiple CUDA installations, or using the OpenCL verison, which should be faster on everything anyways except super top-end GPUs with tensor cores.

**Comment by lightvector** [comment]
Do any of these help? Are you precisely in the case where you have a tensor-core GPU and therefore specifically want to use the CUDA version rather than OpenCL?

**Comment by lightvector** [comment]
Actually, next release, I might go ahead and try upgrading to CUDA 10.2, if that helps. Assuming that works, you can also try sitting tight and waiting for the next release. But also I strongly recommend the OpenCL version if you don't have a top-end GPU, there's a good chance it works already (and even performs better!).

**Comment by lj739** [comment]
Thanks for the upgrading plan. I already retrieve to cuda10.1, I don't have a tensor core GPU , but I always prefer to use cuda version which seems a little of stronger.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightvector"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 凌晨1:48
收件人:&nbsp;"lightvector/KataGo"<KataGo@noreply.github.com&gt;;
抄送:&nbsp;"费而隐"<909417887@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lightvector/KataGo] Cuda 10.2 not supported? (#235)





 
Actually, next release, I might go ahead and try upgrading to CUDA 10.2, if that helps. Assuming that works, you can also try sitting tight and waiting for the next release. But also I strongly recommend the OpenCL version if you don't have a top-end GPU, there's a good chance it works already (and even performs better!).

**Comment by lightvector** [comment]
Okay cool.

What do you mean by "seems" stronger?

The stronger of OpenCL and CUDA shoul be whichever gives you the better performance when you run it in the benchmark, which is easily precisely measurable - just run the benchmark! There should be no strength difference between them except for what is caused by being faster/slower and searching more/fewer playouts per second, because both OpenCL and CUDA compute numerically identical results out to 6 or 7 decimal places (unless your GPU is buggy for one of them).

**Comment by nicewk** [comment]
@lj739  katago 1.4.2 works fine with coda10.2 on my computer . You just need to check your PATH setting of your machine. If you don't find cuda path there, you have to add one yourself. Something like 'PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;'.

**Comment by lightvector** [comment]
The latest version (1.4.4) is compiled on cuda 10.2 now. Enjoy!

But also please mind what I said earlier - **the only difference between OpenCL and CUDA is speed/performance. Whichever one is faster for you is the one you should use.**. There is no other magical "seems stronger/weaker" difference between the two.

**Comment by lj739** [comment]
Thanks a lot.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lightvector"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月15日(星期一) 凌晨1:28
收件人:&nbsp;"lightvector/KataGo"<KataGo@noreply.github.com&gt;;
抄送:&nbsp;"费而隐"<909417887@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lightvector/KataGo] Cuda 10.2 not supported? (#235)





 
The latest version (1.4.4) is compiled on cuda 10.2 now. Enjoy!
 
But also please mind what I said earlier - the only difference between OpenCL and CUDA is speed/performance. Whichever one is faster for you is the one you should use.. There is no other magical "seems stronger/weaker" difference between the two.
