### ISSUE TITLE
Questions about passes in self-play

### ISSUE THREAD

**Issue by isseebx123** [lightvector/KataGo#236]
I've run katago's self-play once and got curious about the pass move.
I don't know if it is correct, but it seems that even if there are many visits to pass move, it does not always pass. Or even with two passes, it looks like katago playing the game further. Could you please explain how to handle pass move in self-play?

Thank you.

**Comment by lightvector** [comment]
It might not pass even if pass is the max-visits move due to LCB or due to temperature. This is normal.

It's also normal for the game not to end after two passes under self-play Japanese rules, since there needs to be some cleanup phases to resolve dead stones. See https://lightvector.github.io/KataGo/rules.html

**Comment by isseebx123** [comment]
Thank you for answer. I'm going to find some code related to LCB and temperature.

Sorry, I have additional questions. Could you please tell me about ownership_target_weight? I know this is set to a value of 0 or 1, but I am wondering when this value is set to 0. 
And does KataGo allow pass moves to be all pass-alive? 

Thank you.

**Comment by lightvector** [comment]
It's set to 0 when there is no ownership data on a given row. Some proportion of data comes from brief forks on alternative moves that are not continued to the actual end of the game - so since the game was not played out, there is no ownership target.

I don't understand your question about pass moves. "Pass moves" cannot be pass-alive because being pass-alive or not is a property of stones on the board, rather than a property of moves.

KataGo in self-play does allow omitting cleanup of stones if those stones are _pass-dead_, if that's what you're asking.

**Comment by isseebx123** [comment]
> I don't understand your question about pass moves. "Pass moves" cannot be pass-alive because being pass-alive or not is a property of stones on the board, rather than a property of moves.

Yes. I agree with you. I am sorry that my English is not good.

In my opinion, katago can see if the current board state is all pass-alive. In that case, isn't it correct to allow pass move in MCTS only when it is all pass-alive? So I was wondering if it actually does.

If the current board state is not all pass-alive, it seems that katago doesn't need to consider pass move. This is because attacking the opponent's stone or defending it is better than pass move.

Thank you.

**Comment by lightvector** [comment]
No, you are mistaken. There are many reasons:

* Sometimes there is a seki, and then the board will not be all pass-alive, but considering passing is absolutely necessary because if you can't pass, then eventually you must suicide in the seki, which would be terrible.
* If passing were banned and you were forced to add extra stones into the opponent's territory for them to capture, that would prolong many games with lots of useless moves because the game lasts longer if you keep adding more stones to the opponent's territory that they then have to capture. This would waste a lot of computation power and also produce a lot of meaningless non-useful training data, making the neural net training weaker.
* Under Japanese rules, you obviously have to pass before everything is pass-alive. You don't want to lose points filling your own territory.
* When playing with human players, it's desirable to pass once all dead stones are captured, even if things are not pass-alive. It's annoying and impolite if a bot fails to do this. KataGo currently behaves not perfectly, but fairly well - see for example [this game](https://online-go.com/game/24421474) where it captures black's stones in a very orderly fashion, with only a few other connecting moves, and then passes, even both lots of its own stones and lots of the opponent stones are not pass alive. This is pretty good, and it's much easier to obtain if this is already the neural net's instinct for how to play. But the only way it can become the neural net's instinct is if it is allowed to practice this way of playing in training, which means passing should be allowed during training. 

If you spent some time to think about it, maybe you might also be able to think of even more reasons that I missed. I'm not confident that the above is all the reasons. :)

**Comment by isseebx123** [comment]
Thanks for the detailed answer. I understood it perfectly.
