### ISSUE TITLE
training in traditional Chinese rule

### ISSUE THREAD

**Issue by gowayeasy** [lightvector/KataGo#253]
Would like to know if you have any plan to train a network with Traditional Chinese Rule? Somehow i feel this can also help to identify what network differences between 2 rules so helpful from AI technology perspective. On the other hand, help people better understand ancient plays capability and  level.

**Comment by lightvector** [comment]
Already supported. See https://lightvector.github.io/KataGo/rules.html for supported rules - in particular, take a look at the "TaxRule = All".

Multiple people have asked me to train a net that supports these rules, so I did, and then I never heard anyone do anything with these rules or use them for analysis. Does anyone actually care, or is this something that people ask for and then don't actually use once it exists? :)

**Comment by lightvector** [comment]
I assume, of course, by "Traditional" you're referring to the penalizing of each living group by 2 points (relative to modern ways of counting) due to its necessary 2 eyes. If you're referring to something else, let me know.

All recent KataGo nets support (almost all) permutations of the rules on that webpage. You can choose whatever combination you like of all of the options and set them in KataGo's config, and it will use that combination. If you know how GTP works, you can also specify the combination using some GTP extension described here https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md and that document also describes some predefined combinations like "chinese" and "japanese" and "aga" and "stone-scoring" and such.

Have fun! Let me know if you find anything interesting with those rules.

**Comment by gowayeasy** [comment]
Thanks. In fact, one of Katago's advantages is that it can adopts to many rules and we did use it to run ancient Chinese games and discovered players like Huang Longshi, Fan Xiping and Shi Xiangxia were very strong, especially in middle game. One of the observations also is that complexity of their games are very high, some even 40-50 and normal professional games are only 20-30. did not see many higher than 30 and very rare to 40, for modern games. 
There are some special moves in Ancient games, for example, 九三(nigh-three) points were well used and emphasized, so far current Katago did not look it special. we are thinking maybe it due to Katago was not particularly trained based on ancient rule. So if possible, we want to see a network only trained from Chinese ancient rule, ie have 4 fixed stones at 4 corners at beginning and deduct 2 eyes for each standalone piece.

**Comment by lightvector** [comment]
> so far current Katago did not look it special. we are thinking maybe it due to Katago was not particularly trained based on ancient rule. So if possible, we want to see a network only trained from Chinese ancient rule, ie have 4 fixed stones at 4 corners at beginning and deduct 2 eyes for each standalone piece.

No, I would think that you can trust KataGo on "ancient rules" about as much as you can trust it in regular games. An entire *twenty percent* of self-play games are played using the two-point group tax! Plus KataGo likes the 4-4 point and almost surely also has plenty of experience with diagonal openings too due to randomness in self-play. 

Therefore, if KataGo strongly dislikes a move in an ancient Chinese game when its rules are set appropriately, then you can probably trust it a similar amount to if it strongly disagrees with a pro move in a modern game. In other words - it could be that KataGo is misevaluating something or has a blind spot. But if you play around with it in Lizzie or other analysis tool and you find no blind spot and KataGo's evaluation seems persistent and clear and its response to the move makes sense, then perhaps this is simply KataGo refuting that move, the same way that bots have greatly changed pro understanding of modern rules and caused pros to greatly re-evaluate certain former joseki moves (for example, the "a" move https://senseis.xmp.net/?34PointHighApproachTwoSpaceHighPincerOgeima).

**Comment by gowayeasy** [comment]
Thanks a lot. I appreciate your clear explanation. Now I even like Katago more. One more question, what do you think any connection between index "complexity" and the player's level?

**Comment by lightvector** [comment]
I don't think it has much connection. It probably is more related to the style of play than to strength. You can have some players who like to fight and escalate a lot, versus other players that often prefer calm efficient moves and are very good at making positional judgments, and even though two fighting players may give you a very different game than two calm players, that does not tell you which one is stronger - both could be equal overall, or either one could be stronger.
