### ISSUE TITLE
Katago never produces a move

### ISSUE THREAD

**Issue by ghistes** [lightvector/KataGo#262]
Hi,

I am completely new to katago, so sorry if I am missing something obvious.

I have a pretty old system (Phenom II x6) with a GT 1030 running Debian testing.

I have downloaded the current katago opencl-version (1.4.5) and the net g170e-b20c256x2-s5303129600-d1228401921.bin.gz.

With these I was able generate a config via "genconfig" using my GPU as opencl-device.

I am now trying to play against katago via sabaki.

I have configured katago as engine and it starts (I can see the process), however it never seems to produce a move.

This is the tail of the sabaki-katago interaction:

> komi 6.5
= 
> boardsize 19
= 
> clear_board 
= 
○ > play B Q16
= 
● > kata-genmove_analyze W 50
= info move (…)

And that seems to be it. katago sitting there pondering it's first move forever....

Anything I could try?

Many thanks!

**Comment by lightvector** [comment]
When you generated a config, did you specify a limit on the number of visits, playouts, or time? If you didn't, you should have seen the following message in the output:

`NOTE: No limits configured for KataGo. KataGo will obey time controls provided by the GUI or server or match script but if they don't specify any, when playing games KataGo may think forever without moving. (press enter to continue)`

KataGo will think as long as it has time, which might be forever if Sabaki hasn't specified a time limit and you didn't put one in the config!

Alternatively, there could be an OpenCL issue, but I presume that when you generated the config, there was a part at the end where it tuned itself and selected a number of threads? If so, then that part should be working.

**Comment by ghistes** [comment]
I did not specify any limits (as far as I can remember), I simply chose japanese rules and then accepted all the defaults.

I can't really find a way within sabaki to specify time limits (I am however new to that as well) so do I need to generate a new config?

I don't really want to play against it (I want to use it for analysis) so the whole point for me is really to make sure that katago is working with my new GPU (I could not make it work with only a CPU).

Is there a better way to verify that katago works?

And what net would you use for a weak CPU and weak GPU?

Many thanks!

**Comment by lightvector** [comment]
Yep, sounds like that's the problem then. You didn't tell KataGo any limits, and Sabaki didn't tell KataGo any limits, so KataGo does an unlimited search. :P Many match scripts and/or GUIs will have a way of specifying time controls to the bot (e.g. this is an X minutes game with whatever overtime periods) but sounds like Sabaki might be a GUI that doesn't have any.

Try generating the config again but this time when it asks you if you want to specify a limit for the bot, say yes and specify, for example, an appropriate number of seconds that you would like KataGo to think before making each move in a real game. If you are using it for live analysis (rather than playing a game against you) this limit should be irrelevant, but it will apply (or not apply, as you discovered) if you attempt to play a game.

Using the 20 block net is good. You could use a smaller net to try to get faster search on a weak GPU, but the 20 block net is so vastly superior in strength that it's probably better even on weak hardware.

**Comment by ghistes** [comment]
Ok, I'll try with a new config.

And it's a bit off-topic, but I don't really understand what is referred to when you talk about a "20 block net".

Could you point me to a ressouce that explains these concepts?

Many thanks!

**Comment by ghistes** [comment]
Ok. specifying a time-limit in the config solves this issue.

Many thanks.

**Comment by lightvector** [comment]
Glad to help. 

Blocks are indicating different sizes of neural net. See here for info about what net to use:
https://github.com/lightvector/KataGo#other-questions

Ask for help in here if you want to ask some beginner on a block actually is, in understanding the neural net's architecture:
https://discord.gg/bqkZAz3
