### ISSUE TITLE
cudaDeviceToUse does not work as expected in Windows

### ISSUE THREAD

**Issue by chncwang** [lightvector/KataGo#270]
I am using katago in Windows. My computer has two GPUs, where device 0 is Intel and device 1 is Nvidia rtx2060. Thus I set cudaDeviceToUse as 1, but the task manager shows that device 0 is busy. I am sure that the config file path is set correctly in KataTrain.

**Comment by chncwang** [comment]
I can't wait to use KataGo to beat leela zero and enjoy the game process...

**Comment by lightvector** [comment]
Are you sure you're using the cuda version of KataGo? Perhaps you're using the OpenCL version?

**Comment by chncwang** [comment]
Yes, I am quite sure.  I download the version which uses cuda 10.2. At first, it cannot work. After I installed cuda 10.2 and cudnn, katago works well except uses device 0.

**Comment by chncwang** [comment]
Well, I see. katago will do some finetune at the first running. It was based on opencl since I didn't install cuda 10.2. I have deleted related folders and it should be OK.

**Comment by chncwang** [comment]
though I use the cuda version, it still generates opencl tuning folder, I don't know why...

**Comment by chncwang** [comment]
maybe the cuda version in the latest release page, is actually the opencl version?

**Comment by chncwang** [comment]
even i set openclDeviceToUse to 1, it still uses device 0......

**Comment by lightvector** [comment]
I checked right now and the versions are all the correct versions on the release page. The CUDA version is the CUDA version and the OpenCL version is the OpenCL version, for both Windows and Linux.

If it generates an OpenCL tuning folder for you and it does tuning at the startup, then it's the OpenCL version. So it sounds to me like the entire time, you thought you were using the CUDA version, but actually you're still using the OpenCL version.

Here's my guess: Perhaps KaTrain doesn't work the way you expect. Maybe you *did* download the CUDA version, but you misunderstand how to set up paths for KaTrain, so secretly the entire time KaTrain uses a different executable than the one you downloaded, and secretly the entire time it uses a different config than the one you modified yourself to set cudaDeviceToUse or openclDeviceToUse.

If that's the case, it sounds like you should open an issue here: https://github.com/sanderland/katrain/issues/
Everything in KataGo looks like it's working to me, so the problem may be your setting up of file paths and figuring out how to configure KaTrain, rather than anything to do with KataGo directly. When you open an issue there, you will probably need to be a bit more verbose to receive useful help - explain where you downloaded what, explain what file paths you configured, etc. You can also check the log file, of course, to see what device KataGo is using.

**Comment by chncwang** [comment]
I have definitely  set the two paths, namely katago and the model path correctly

**Comment by chncwang** [comment]
plus with the default config path

**Comment by lightvector** [comment]
If you really have installed the CUDA version, it should be *incapable* of even seeing or using the "intel" device. Because CUDA is NVIDIA's GPU compute language, and it only works on NVIDIA GPUs.

I can't tell if you're misunderstanding something or you have something set up incorrectly, or if there really is some bug. I recommend you ask for help in the #help channel of the discord chat where LZ and KataGo and other bot devs and users hang out: https://discord.gg/bqkZAz3

It's not *super* active in there, but there should be a few people there (including me, sometimes) who can help you debug your configuration, and if you can be online at the same time as one of them, it should be much easier to talk back and forth and interactively debug what's going on than on a Github issue page.

**Comment by chncwang** [comment]
Thank you! I have joined in. I have also tried the latest lizzie, remaining the opencl version and set the opencl device to 1, and turned out to run device 0 again...

**Comment by hhb** [comment]
@chncwang I'm having the same issue. May I know how did you solve it later?
