### ISSUE TITLE
Has anyone gotten this to work with Unreal Engine?

### ISSUE THREAD

**Issue by AscendChina** [lightvector/KataGo#273]
On Steam there is a game called Ancient Go which was written in either Unity or Unreal. But its been abandoned and no longer supported nor developed and author/dev is gone... 

Has anyone been able to integrate katago with Unreal engine or have published anything like that to the Unreal marketplace?

**Comment by lightvector** [comment]
I guess the radio silence means that nobody has. :)

But anyways, if someone wanted to create and market a steam game that uses KataGo as an underlying engine for some of its features, I'd have no objections. Indeed it looks like someone *is* trying to do that: https://store.steampowered.com/app/1264970/The_Conquest_of_Go/ and it looks pretty exciting.

Going ahead and closing this since as an issue for KataGo itself, I think isn't anything particular to do here, and there is also already plenty of free software in the form of Go GUIs and such. Thanks!
