### ISSUE TITLE
How to set faster?

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#28]
numSearchThreads is limitted by CPU or GPU？
nnMaxBatchSize should be equal to numSearchThreads?
Others?

**Comment by lightvector** [comment]
numSearchThreads is the number of CPU threads to use. If your GPU is powerful, it can actually be much *higher* than the number of CPU cores on your system because you will need many threads in order to feed large enough batches to the GPU to get good GPU use.

nnMaxBatchSize should be be around the number of CPU threads you are using, yes, but how large it needs to be can vary if you are using multiple GPUs instead of 1 GPU.

You will want to use cudaUseFP16 and cudaUseNHWC if your GPU has FP16 tensor cores.

If you are doing long searches with large numbers of visits, and you don't mind using more RAM on your machine, nnCacheSizePowerOfTwo can be increased, and also nnMutexPoolSizePowerOfTwo. I think the config comes with nnCacheSizePowerOfTwo = 18 meaning that it will cache 2^18 = 262144 neural net results, but due to birthday paradox you may start getting some noticeable cache losses once you start searching in the high thousands of visits.

Thanks for the question, hope that helps. I'll add some more documentation about various parameters to the README or otherwise within the release itself before too long, I just haven't done it yet.

**Comment by ivysrono** [comment]
Thank you very much.

**Comment by ivysrono** [comment]
#29
