### ISSUE TITLE
How to use external data to initialize self-play training?

### ISSUE THREAD

**Issue by Dreamkeeper66666** [lightvector/KataGo#294]
Hi, I am very interested in the work on Igo 120 and the experimentally-trained neural nets. So I am wondering which part of the training code/config file I should change if I just want to do some more training based on the previous work. Thanks a lot!!!

**Comment by lightvector** [comment]
Not sure why you closed this just now, but I'll say that revisiting igoh120 is something that is already being considered by me and one or two collaborators. I didn't reply here since that's still a bit in flux and maybe is already being handled soon. :)

Generally if you want to do training for any idea of your own, I recommend you look at the code for what the different parameters you see in the config file do, and then once you have more specific questions, ask. (Obviously, even before you try to do anything special, should try to get basic training working on your own, like for 9x9, if you haven't yet).
