### ISSUE TITLE
Error when compile eigen backend on MSVC

### ISSUE THREAD

**Issue by yzyray** [lightvector/KataGo#296]
I can complie kaorahi's borrow_tensorflow branch with newest eigen3 or 1.50 release tag with eigen3.3.7 release
but compile current master branch,i get this error
![微信截图_20200813145908](https://user-images.githubusercontent.com/49384584/90103732-93df0480-dd75-11ea-9fd0-af668c1ec966.png)
I have tired eigen3.3.7 and newest eigen3,both get this error.
	C2664	“void Eigen::Tensor<float,2,0,Eigen::DenseIndex>::resize(void)”: Cannot convert “const std::array<int,2>”to “__int64”	katago	C:\Program Files (x86)\Eigen3.7\include\eigen3\unsupported\Eigen\CXX11\src\Tensor\Tensor.h	416

**Comment by lightvector** [comment]
Thanks for the report. I'm not really sure why this issue comes up, but I'll investigate it when I get the chance, unless you can already trace where the problem occurs? 

If you have an understanding of what causes the issue, that would be a great help. Maybe there is a mismatch between the version of Eigen required, or there is some operation that MSVC compiles differently and more strictly than g++ does that needs to be tweaked? Is the error really in the header file itself, or does it only appear that way and in fact can be traced to a specific bad line in cpp/neuralnet/eigenbackend.cpp (e.g. there is a specific line that if commented out, the error goes away, so that we know what line needs to be fixed).

**Comment by samecos** [comment]
I checked the output log to locate the problematic code  in file "eigenbackend.cpp" line: 369
`    else {
      numTilesX = 0; //not used in this branch
      numTilesY = 0; //not used in this branch
      inTileXYSize = 0; //not used in this branch
      outTileXYSize = 0; //not used in this branch

      TENSOR4 kernel = TensorMap<const Tensor<const SCALAR, 4>>(desc.weights.data(), convXSize, convYSize, inChannels, outChannels);
      imagePatchSize = convXSize * convYSize * inChannels;
      Eigen::array<int, 4> dimensionPermutatation({3, 2, 0, 1});
      Eigen::array<int, 2> newShape({outChannels, imagePatchSize});
      **imagePatchKernel = kernel.shuffle(dimensionPermutatation).reshape(newShape);**`

**Comment by yzyray** [comment]
> numTilesX = 0
I tried commented out this line,then compile successfully, no previous  error
![TIM图片20200817082246](https://user-images.githubusercontent.com/49384584/90347412-e87acc00-e062-11ea-87b6-4b61bd761021.png)

**Comment by sanderland** [comment]
After fixing cmake's failure to find eigen by replacing `find_package(Eigen3 REQUIRED)`
with `set(EIGEN3_INCLUDE_DIRS "<path>")` I also get this error

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void Eigen::Tensor<float,2,0,Eigen::DenseIndex>::resize(void)': cannot convert argument 1 from 'const std::array<int,2>' to 'const std::array<__int64,2> &'	
```

**Comment by lightvector** [comment]
I think this should be fixed now at tip of master, using a slightly different compile fix than sander tried, but hopefully actually works a bit more widely.

Eigen3's "integration" with cmake is pretty arcane on Windows. I finally figured out the "intended" way, which is undocumented, but consists of making a "build" folder after you download the source, cd into it, run `cmake .. -DCMAKE_INSTALL_PREFIX=whatever_desired_install_directory` then open up Eigen3.sln in MSVC, scroll down in MSVC to only the "INSTALL" project and build that one (don't build anything else, it will take forever). Then, specify Eigen3_DIR for cmake as `whatever_desired_install_directory\share\eigen3\cmake`.

Careful not to move anything around or specify a directory that's too shallow, since Eigen3 hardcodes the cmakefile inside of that to look for "..\..\..\include", which will end up mapping to `whatever_desired_install_directory\include`, but if you're too shallow, then what may happen is that cmake still finds something but ends up hitting the wrong path after the sequence of "..", or something of that sort, and then fails to find the includes.

Bleh.

**Comment by yzyray** [comment]
I see the fix commits,have tried and compiled success,thanks very much
