### ISSUE TITLE
Paper: questions and ideas

### ISSUE THREAD

**Issue by alreadydone** [lightvector/KataGo#3]
First of all, thank you for the experiments and the release of a paper with dazzling variety of methods and details!

> This fact is ambiguous in DeepMind’s published papers due to ambiguity about whether a [-1,1] or [0,1] scale was used, and was only clarified much later by an individual researcher in a forum post here: http://talkchess.com/forum3/viewtopic.php?f=2&t=69175&start=70#p781765

If you are referring to Matthew Lai, he's a research engineer at DeepMind involved in the development of AlphaZero ...

![image](https://user-images.githubusercontent.com/3064145/53623687-d174bf80-3bcb-11e9-9209-bf30bb592080.png)
Is a square root missing here?

Regarding one network for different sizes of boards: I am curious how your net perform against the 13x13 net converted from a 19x19 LZ 40b net (available at https://github.com/leela-zero/leela-zero/issues/2240). Though it hasn't been trained on 13x13 games, it's the currently strongest 13x13 net available, and said to be of superhuman strength. Your 15b net achieves potentially superhuman strength on 19x19 as estimated in the paper, and though it hasn't been trained on as many 13x13 games, 13x13 should be easier to master due to smaller board size, so I think it would be a good matchup.

I am curious what you find about fair komi on even-sized boards. Are they usually closer to 4 or 6? (I guess the latter.)

The same method should allow the net to play on rectangular boards or disjoint unions of boards. If the two boards are identical the second player has a perfect mirroring strategy, which can only be broken by superko rules, I think. (I can imagine a double ko situation.)

**Comment by Marcin1960** [comment]
Just do not let be persuaded to move to a huge net like 40 blocks or more. It would kill your project.

**Comment by lightvector** [comment]
Hi @alreadydone - thanks. Yes, I'm aware that he was a researcher at DeepMind, that was presumably why he was one of the individuals able to clarify things ambiguous in the publication.

Yes, a square root is missing there, I will correct that shortly along with a few other minor errors and typos that have been discovered. Thanks for pointing it out!

I have not done a detailed investigation of komi on even boards, but once you get the code working, you're very welcome to investigate! :)

It would be hard to extend my code to handle disjoint unions of boards, but rectangular boards would be straightforward, I might do that in a future run. Almost all of the code is theoretically written to support rectangular size, just some of the highest-level parts are not, in part because for some strange reason neither GTP nor SGF files have any support for it?

**Comment by lightvector** [comment]
I could run a test versus 13x13. Do you need to do something special when compiling for LZ to play on 13x13, or does it work out of the box if you just give it the adjusted network?

**Comment by bernds** [comment]
You need to adjust this in src/config.h
```
/*
 * BOARD_SIZE: Define size of the board to compile Leela with, must be an odd
   number due to winograd tiles
 */
static constexpr auto BOARD_SIZE = 19;

```

**Comment by alreadydone** [comment]
In a QQ group, N.O.V.A. proposed that [group tax](https://senseis.xmp.net/?GroupTax) could be implemented as an alternative rule in the KataGo engine/NN. This rule is in the "original" rule of Go and was in use in China even during the Qing dynasty (1644-1912) before the back-influence from Japan (Dohei Takabe, 1909, cf. http://www.guoxue.com/book/wqsh/0030.htm). The idea is that only stones on the board count towards the player's score). Since a group needs to eyes to live which can't be filled, if a group of yours is split into two you effectively loses two points. This rule likely contributed to the combative style in ancient Chinese Go, and likely reduces the favorability of 3-3 invasions.

It would be a great addition to your engine: no AI to this date, even Golaxy, claims to support analysis under this rule, though it's pretty in demand to analyze ancient games and determine the level of play. An inconvenience is that one now needs to fill in all except two points in each of one's area to get the accurate score (with normal Tromp-Taylor rules you just need to remove the opponent's dead stones), especially in your setting, where all games are not resigned, but since you already have Benson's algorithm implemented to determine live groups and remove dead stones, it shouldn't take much more time to train under this rule. Hope to see this in a future run!

**Comment by alreadydone** [comment]
Though unlikely to happen in real play, there actually exist positions, under the situational/positional superko rules, in which one side must fill in all (but one) of the eyes in a *pass-alive group* (to be captured by the opponent) in order to *win*. An example is presented in https://tieba.baidu.com/p/1287975900.

**Comment by lightvector** [comment]
Yep. You can make much simpler positions too that have this property, see https://senseis.xmp.net/?1EyeFlaw.  The training I implemented I believe makes no assumptions about this, although probably the neural net wouldn't get it right anyways given that they already fail on much simpler things.

But it it always safe to assume that your pass-alive groups and their single-eye-points - and, if the rules let you claim opponent stones that are pass-dead as pass-dead without physically capturing them during normal play, also your pass-alive territories that are larger than single eyes - together give a _lower bound_ on your score under optimal play, even if you might choose to sacrifice them to do better.

You can also construct rules beast positions where it's not possible to capture stones that are pass-dead and remove them from the board due to superko considerations, so even though they are surrounded by pass alive groups and themselves being pass-dead can never even possibly become "alive". Under Tromp-Taylor, you would then have to leave them uncaptured, unable to claim the points for killing them, which maybe could prevent you from winning. I've mostly chosen to ignore this issue, since it's not as if Tromp-Taylor is a standard ruleset that human games use in practice either. I imagine if such a situation occurred in a real and/or important game, the rules argumentation would be very interesting.

**Comment by poptangtwe** [comment]
I'm N.O.V.A. in the QQ group for Leela. Thanks for introducing the group tax, one of the simplification and prejudgment methods for the original rule of Go in Ancient China, in English.@alreadydone 
To make a long story short, the original rule of Go only count stones alive in the end of game, each group alive should have 2 eyes, these eyes are not counted in the score.
There are 2 benefits to implement this rule in KataGo.
The one @alreadydone mentioned is that no AI engine nowadays supports the rule, but Chinese amateurs are dying to analysis Chinese ancient games. And the rule are still used in some Chinese amateurs games. 
The other one is the original rule of Go is simplist and most convenient mathamatically. With this rule, the Tromp-Taylor rules can be also simplified, since the score is just counting stones alive on the board in the end of games.
Thanks a lot. @lightvector

**Comment by alreadydone** [comment]
Re: simplicity
Arguably no-pass Go (the first player without legal moves loses) has the simplest rule, but it's a very different game than the Go we play today. The next simplest rule is probably Tromp-Taylor with group tax, or more correctly, TT rules without counting empty points that only reach one player's color. Miraculously, this rule is mostly equivalent to [no-pass Go with prisoner return](https://senseis.xmp.net/?PrisonerReturn) which is also super simple mathematically and fits combinatorial game theory naturally.

**Comment by lightvector** [comment]
@alreadydone 
LZ converted weights work quite well. On 13x13, it's about 140 Elo stronger than KataGo when both have 1600 visits, with a winloss record of 563 - 255 in the test match I did.

The converted weights are still 40 block and 256 channels, right? If I multiply KataGo visits by 4 up to 6400, still using 15 blocks 192 channels, then it looks like a pretty even matchup. In that case, they're almost equal in strength based on the test run I did. KataGo winning 309-291.

**Comment by alreadydone** [comment]
@lightvector Thanks for doing the tests! Congrats for KataGo winning the time-parity test despite being trained with much less resource!

**Comment by lightvector** [comment]
Games attached, in case anyone's curious.
[lz-v-kata13x13-1600.txt](https://github.com/lightvector/KataGo/files/2949052/lz-v-kata13x13-1600.txt)
[lz-v-kata13x13-1600-4800.txt](https://github.com/lightvector/KataGo/files/2949053/lz-v-kata13x13-1600-4800.txt)

**Comment by bernds** [comment]
These contain invalid moves in the SGF: if LZ fills its own territory as Black, there are W[tt] nodes from KataGo.

**Comment by bernds** [comment]
I looked at it again, and it seems [tt] is an FF[3] thing, retained for compatibility in FF[4]. I just hadn't encountered this before and thus q5go currently doesn't handle it well.
I still think it would be better not to do this - what happens on larger boards, does it use the [] syntax?

**Comment by lightvector** [comment]
I don't know. I didn't write Gomill! :)

Maybe talk to the author of the library? Looks like there's a contact address at the bottom of this page: https://mjw.woodcraft.me.uk/gomill/ and also a Github here https://github.com/mattheww/gomill/

**Comment by lightvector** [comment]
You'll probably encounter this elsewhere too, I'm surprised you haven't yet. Some of the tests for LZ or MiniGo I think I've heard people using "ringmaster" in some cases, which is also a script from the Gomill library.

**Comment by lightvector** [comment]
Going ahead and closing this issue, as it seems everything here is handled. Wheee. :)

**Comment by TFiFiE** [comment]
The paper is (still) missing footnote 33, which I suspect would have covered what combination of **z** and **Q** to train the value prediction on (like what's in https://github.com/LeelaChessZero/lc0/issues/84#issuecomment-477224886).

**Comment by lightvector** [comment]
Thanks for pointing that out. There is no missing footnote at all, it's just a numbering issue. I'm not using Q at all either, I would absolutely have mentioned that as a section in the paper if I did since that would be a big difference from any other prior bot (AZ, ELF, LZ, etc).
