### ISSUE TITLE
Multiple gpus load only 50% in opencl version 

### ISSUE THREAD

**Issue by yzyray** [lightvector/KataGo#302]
4gpus 
opencl:
![微信图片_20200820104011](https://user-images.githubusercontent.com/49384584/90710719-8e337280-e2d1-11ea-96a3-7358cfa2dc62.png)
cuda:
![微信图片_20200820104048](https://user-images.githubusercontent.com/49384584/90710764-a3100600-e2d1-11ea-94ec-0b6995110c36.png)
 config:
![微信图片_20200820104119](https://user-images.githubusercontent.com/49384584/90710790-b327e580-e2d1-11ea-9fb8-13bc0e9b6ebe.png)

2gpus
opencl:
![微信图片_20200820104208](https://user-images.githubusercontent.com/49384584/90710842-cfc41d80-e2d1-11ea-8580-271e3a669711.png)
cuda:
![微信图片_20200820105547](https://user-images.githubusercontent.com/49384584/90711597-b8862f80-e2d3-11ea-8f5f-132b615a9eea.png)
config:
![微信图片_20200820104319](https://user-images.githubusercontent.com/49384584/90710910-fbdf9e80-e2d1-11ea-91e1-c06866ab3613.png)

1gpu
opencl:
![微信图片_20200820104357](https://user-images.githubusercontent.com/49384584/90710992-33e6e180-e2d2-11ea-9532-883e5f4c1d85.png)
cuda:
![微信图片_20200820104403](https://user-images.githubusercontent.com/49384584/90710996-35b0a500-e2d2-11ea-9d98-294831873abb.png)
config:
![微信图片_20200820104410](https://user-images.githubusercontent.com/49384584/90710979-292c4c80-e2d2-11ea-9721-1751966e30bb.png)
GPU is RTX 2060S and its all the same board status,Is there anythine special in config files should be modified for multiple gpus in opencl version,or just opencl version's weakness?

**Comment by lightvector** [comment]
Please ignore the reported GPU usage, it is mostly useless for making decisions. Instead, what you want to pay attention to is the actual visits per second you get. If hypothetically the reported GPU usage were even lower than it was now, but the visits per second were better than what it is now, that would be a *good* thing, not a bad thing.

What actual visits per second are you getting on OpenCL? Right now, it is expected to be not quite as good as CUDA if you have tensor cores, but it should be much closer than before, when the OpenCL code didn't even support tensor cores at all.

**Comment by lightvector** [comment]
Similarly, if you have been trying different settings to see if you get an improvement, in all of them you should be probably not be looking at all at GPU percent usage, again pay attention to only whether the improvement improves the actual visits per second, because that's what ultimately matters.

And of course, if you have any expertise in optimizing GPU code or you know anybody with expertise who could help improve the OpenCL implementation, it would be appreciated. :)

**Comment by yzyray** [comment]
The actual visits per second is much much lower than cuda version,if use two or four gpus, one gpu is a little higher than cuda version.
I have tested in 4*2080ti or 4*2060s,if one gpu is 1000visits/s, two gpus cuda 1900-1950 vistis/s four gpus cuda  3800-3900 visits/s but two gpus opencl only 1200-1400 vistis/s four gpus opencl 1300-1600 visits/s
later i'll run some benchmark and put results up.

**Comment by yzyray** [comment]
2gpus
cuda:
![4gpucudabenchmark](https://user-images.githubusercontent.com/49384584/90718941-bcbb4880-e2e5-11ea-8293-d8ffcb3bcf57.png)
opencl:
![2gpuopenclbenchmark](https://user-images.githubusercontent.com/49384584/90718944-bfb63900-e2e5-11ea-97bc-8af92564df33.png)
4gpus
cuda:
![4gpucudabenchmark](https://user-images.githubusercontent.com/49384584/90718967-ccd32800-e2e5-11ea-8036-545fc851e1c1.png)
opencl:
![4gpuopenclbenchmark1](https://user-images.githubusercontent.com/49384584/90718972-cfce1880-e2e5-11ea-8b8c-86034de4d76e.png)
![4gpuopenclbenchmark2](https://user-images.githubusercontent.com/49384584/90718983-d2c90900-e2e5-11ea-8633-024e5a8aeab2.png)
I notice this issue in servral computers,if has more than one gpu cuda is more Efficientive than opencl ,even for 1080ti.

**Comment by lightvector** [comment]
Thanks for posting the info!

Okay, I'm wrong, sorry about that. :) In that case, in combination with the visits per second essentially not improving at all, I guess the GPU usage does suggest something interesting (I have a hard time trusting usage % sometimes because I've sometimes run into other cases where it's misleading).

It seems like there must be some sort of false dependency or mutual exclusion in the OpenCL implementation that makes it so that only one GPU can be used at a time, even though there are 4 threads each one for a separate GPU. I'll investigate when I get the chance.

**Comment by lightvector** [comment]
Seems like it might be something like this:
https://forums.developer.nvidia.com/t/cuda-opencl-runs-multiple-gpus-sequentially/22694/16

If so, maybe it's possible to work around.

**Comment by yzyray** [comment]
If there is a computer with multiple AMD gpus,may be helps.

**Comment by lightvector** [comment]
Does this branch fix the problem for you? https://github.com/lightvector/KataGo/pull/304

**Comment by lightvector** [comment]
Yay, thanks for the test. Is there anything else to do here, or is this issue resolved?

**Comment by yzyray** [comment]
> Yay, thanks for the test. Is there anything else to do here, or is this issue resolved?

Thanks very much,I think its resolved.
