### ISSUE TITLE
Regarding memory usage

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#303]
Thank you for providing great software.

Probably a rudimentary question, thank you.
Regarding memory, I have the following questions when setting up KataGo for Mega Pack.
”Kata Go will cache up to about 3GB of positions in memory (RAM), in addition to whatever the current search is using.Spec a max in GB or leave blank for default''

Perhaps "By default it uses 3GB of memory, but if you want to use more, please specify a number"
I think that means.
So I tried to specify "5," but I couldn't feel any noticeable change compared to the default "3." ..
Please tell me what kind of change will be brought about by changing this value.
I asked a question in Mega Pack Issues, but I couldn't get a clear conclusion, so I asked here.

**Comment by lightvector** [comment]
3 GB is enough to store somewhere around 2 million neural net evaluations, or 1 million if you have ownership visualization enabled, so the size of the cache will start to matter once you have done in total a significant fraction of that many playouts across many different positions in total, as you scroll back and forth between those positions in an interactive analysis.

There may also be some benefit even well before that due to fewer hash collisions and therefore more reliable hitting of the cache on transpositions, speeding up search in positions where the order of moves matters very little. But mostly this will be hard to notice unless you are using 100ks of playouts per search, and even then the effect may be small.

The other thing to realize is that the cache is sized to always be a power of 2. It picks the largest power of 2 that leads to a cache size *less* than your limit. So if you give a limit that is less than double that of another limit, it might not actually result in a larger cache at all! It will depend on whether your increase crosses the actual threshold that allows for the cache size to be doubled or not. So, depending on how the math falls out, which I can't do in my head, possibly 3GB -> 5GB actually gives the same cache size.

**Comment by hope366** [comment]
Thank you for the surprisingly polite answer.
It seems that I could not understand everything because I lacked specialized knowledge, but I would like to make an effort to understand it.
I usually only search about 10k per move in my lizzie review. Also, it's rare to analyze the entire game, and most often end up with a partial analysis.
In such a situation, 3GB is a necessary and sufficient number.

**Comment by lightvector** [comment]
Ah yeah sure, if you're only doing 10k visits per move, then a larger cache isn't that helpful. Do you have further questions I can help answer about this, is this resolved for now?

**Comment by hope366** [comment]
Thank you for telling me something professional.
It was very interesting that 3GB->5GB would actually give the same cache size as the cache size is adjusted to a power of 2.
Thank you very much!
