### ISSUE TITLE
GPU version KataGo doesn't work with MX350

### ISSUE THREAD

**Issue by HaochenLiu** [lightvector/KataGo#306]

**Comment by lightvector** [comment]
Which version, what operating system, what error messages?

**Comment by HaochenLiu** [comment]
katago-v1.6.0-gpu-cuda10.2-windows-x64.zip
g170-b40c256x2-s5095420928-d1229425124.bin.gz

I use Lizzie and have no error message. The log and KataGoData folder are not created.

**Comment by lightvector** [comment]
Please give more details, more details, as many as you can that would help figure out the problem. Lizzie is not a good way to test, because it will hide error messages even if there are error messages. What happens if you run it directly in a command prompt? What is the actual command line you are using, maybe you have a typo in how you are configuring it in Lizzie? Did you install CUDA and CUDNN? Did you make sure to install CUDA 10.2, rather than CUDA 11, when you installed CUDA? If you just recently installed CUDA and CUDNN, did you reboot your computer after installing it? Did earlier versions of KataGo works for you or is this the first time you're trying this?

Your issue might have nothing to do with MX350. Because there are many possibilities for what is wrong, and it could potentially require a lot of back-and-forth questions and answers specific to your configuration, you are welcome to join here and ask in the help channel:
https://discord.gg/SvhzhfS

Unless, of course, in the process of answering the above questions, you realize yourself what's wrong (e.g. you installed CUDA 11, which KataGo has not upgraded to yet).

**Comment by lightvector** [comment]
Also, by the way: you might consider trying the OpenCL version? 

If it is actually something specific to your GPU or drivers, but otherwise your GPU is working, there is a chance that it will simply just work, whereas the CUDA version is not recommended except to people willing to do more technical setup and benchmarking (including correct setup of CUDA), as noted in the release notes here: https://github.com/lightvector/KataGo/releases/tag/v1.6.0

**Comment by lightvector** [comment]
Going ahead and closing this, but please let me know if you need additional help. I'd recommend starting with the OpenCL version - as mentioned at https://github.com/lightvector/KataGo#opencl-vs-cuda-vs-eigen there is no reason for most users to use the CUDA version, and as you found, compatibility can sometimes be tricky.
