### ISSUE TITLE
Would some kind of LSTMs make sense for go?

### ISSUE THREAD

**Issue by merlinpan** [lightvector/KataGo#313]
Just a totally naive thought. On a simpler basis, would, say, a network with inputs that is intended to take "previous iteration results" (for example, the estimated b/w occupancy of the whole board on the last move, the last move's PV estimates, etc.) make a more efficient network?

**Comment by lightvector** [comment]
I would guess probably not much help, not if you include only such volatile and "top-level" information, because the correct move to make, the expected ownership of the board, etc, depends so massively on what the opponent just did. For example, in a fight, especially in the opening, it is very common for two paths to lead to very different ownership, even if each one is approximately equally good, so the useful correlations here are probably too weak to help out the immense work the neural net always has to perform and re-judge anyways.

If you include full *rich* information about the game state, such as a large-channel representation of the board, in what you carry over, then yes, it can help. We see this in MuZero, where they gained a small amount of strength for a given size of the network by passing a rich encoding with a large number of channels along in the search.

The downsides are that you've blown up the memory costs. If each node used to cost 19*19 floats for the policy = 1.4 kb, and you want to search millions of nodes... but now instead you now carry over 19*19*256 floats... well... you can see how there's maybe an issue. Also, training becomes harder and more complex, and one notes that MuZero didn't scale indefinitely, because of imperfect stability in its updating of the encoding.

So, I wouldn't consider this a good idea right now, not until a far better method is found.

**Comment by lightvector** [comment]
This is just my intuitive guess of course, I haven't tried it.

And of course, a better method won't happen without research and experimentation to find a better method. So, to be clear: I'd find it cool to see what academic research if any develops in this area in the future, and would of course not discourage experiments along these lines. It's not an area I think is as good as it needs to be for real use in this case, but certainly seems like there could be things here to improve.

**Comment by iopq** [comment]
Note that there's little strength difference using 2GB or 4GB or 8GB in KataGo because the cache is often only a tiny bit useful after the opponent makes a move.

If you include the previous information and it does use a few GB more, but has a small strength increase, it could be a viable way to scale hardware
