### ISSUE TITLE
About reading sgf files

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#319]
I wrote it in lizzie's Issues, but it's also about KataGo, so I'll post it here as well.

This is a problem when reading Fox Go's sgf file with evaluation values ​​and explanations with lizzie-v0.7.3.

・ Katago-v1.4.2-cuda10.1-windows-x64
・ Katago-v1.4.2-opencl-windows-x64
・ Katago-v1.4.5-cuda10.2-windows-x64
・ Katago-v1.4.5-opencl-windows-x64
・ Katago-v1.5.0-opencl-windows-x64
・ Katago-v1.6.1-gpu-opencl-windows-x64
・ Leela-zero-0.17-win64

If these are set, the sgf file with evaluation value and explanation will be read successfully.

・ Katago-v1.5.0-cuda10.2-windows-x64
・ Katago-v1.6.1-gpu-cuda10.2-windows-x64

If you open an sgf file with evaluation values ​​and explanations with these set, lizzie will freeze.

After successfully opening the sgf file with evaluation values ​​and explanations, even if you change to the above two engines in the engine settings, you can analyze normally.

Since I am using Google Translate, it may be difficult to read, but please forgive me.

**Comment by lightvector** [comment]
This is very likely not a KataGo issue, and I think it is extremely unlikely that OpenCL vs CUDA, or the version of KataGo has anything to do with it. OpenCL vs CUDA, and also 1.4.5 vs 1.5.0 make no changes that would have an impact on this. Please keep in mind at (to the best of my knowledge), KataGo never even sees the SGF file. Lizzie is responsible entirely for parsing the SGF file, and then telling KataGo what moves to put on the board.

I would guess that the only reason you observe such differences between KataGo versions and between OpenCL and CUDA is either:
* Possibly due to random noise - possibly randomly sometimes Lizzie experiences the bug, and randomly sometimes it doesn't, and you happened to run into the times where Lizzie didn't on those versions of KataGo, but it was random chance rather than the KataGo versions having anything to do with it.
* Possibly due to loading times. Some versions of KataGo maybe either slightly slower or faster to load than others, so it will report back to Lizzie with a different latency, which could potentially trigger different orders of things happening in Lizzie to trigger a problem or not. If this is the case, you might also get variable results when changing size of neural net you're using.

Anyways, I'll reiterate though: very likely KataGo has nothing to do with it - KataGo never even sees the SGF file.

**Comment by kaorahi** [comment]
ref. https://github.com/featurecat/lizzie/issues/752#issuecomment-695796094

**Comment by hope366** [comment]
Thank you for your reply.
Some parts of lizzie are unstable, and what was always working normally may suddenly stop working. This phenomenon may be similar. I would like to verify various things again.
Thank you.
