### ISSUE TITLE
Suspicious noResultValue and score in fillValueTDTargets

### ISSUE THREAD

**Issue by reinerp** [lightvector/KataGo#33]
The fillValueTDTargets function appears to be accumulating time-decayed averages of the `winValue`, `lossValue`, `noResultValue`, `score` parameters, to use as training targets. However, the arithmetic for `noResultValue` and `score` use `=` rather than `+=`, which means that the last value wins and no accumulation takes place. Typo or intentional?

https://github.com/lightvector/KataGo/blob/2d3e8324207f8d27ce070af4bd61770ef09a1779/cpp/dataio/trainingwrite.cpp#L261

**Comment by lightvector** [comment]
Good catch, thanks!
Luckily, it should not affect any of the current KataGo training, since the time-decayed values are unused the current training loop other than the final game result, which should in any case be the last one written, with full weight.
But this bug could certainly affect experimental tests including one that I ran in the past trying to train to predict shorter-term targets, so I'll fix this and make a note to re-test such ideas in the future.

**Comment by lightvector** [comment]
Fixed in https://github.com/lightvector/KataGo/commit/9a571359c52205648ac15fa20fbba1cb51641b64

Done!
