### ISSUE TITLE
Using symmetry

### ISSUE THREAD

**Issue by leobattin** [lightvector/KataGo#333]
Hi,

Is the training process taking into account the symmetry of the board ?

I noticed a while ago that the engine was suggesting symmetrically identical moves but giving them non-identical win-percentage, so it would appear it does not...

Wouldn't it improve performance of both training and running Katago if these symmetries were taken into account ?

For what it's worth, as I'm not a very good programmer, my idea would be to create a function which performs board rotations: any input of the 4 possible symmetrical positions of a board would give the same resulting position, given some rule. This function would be called before feeding the position to the net.

Or maybe I'm not making any sense, in which case I would be more than happy to be told why ^_^

**Comment by lightvector** [comment]
Training already takes into account the symmetry of the board, and there isn't much further improvement to be done. Every time any piece of data is seen, it is randomly mirrored 8 possible ways when training the neural net, which massively improves neural net's training stability.

Even though the data fed to the neural net is unbiased, the neural net is not constrained to be symmetric - it is allowed over the course of its learning to be asymmetric if it wants, because there is nothing in its architecture that forces symmetry. This is what you are seeing.

And it is also highly beneficial for learning - forcing the neural net to be symmetric at every point would hamper its ability to optimize and learn. This is intuitively related to the way that in many constrained optimization problems, it is often beneficial to allow constraints to be violated over the course of optimization to make the problem smoother and avoid local minima. Also, all known ways of making neural nets rotationally equivariant right now either waste a bunch of the neural net's internal capacity or have a big computational cost (brief intuition: sometimes the most efficient way to compute something symmetric involves composing together variable numbers of individually-asymmetric components in different orientations, so enforcing symmetry or any particular cardinality of symmetry forces you to be inefficient).

**Comment by leobattin** [comment]
Will need to read this a few times over, but I think I get the big picture. I was supecting that I was being too naive here :) 
Even if I don't grasp the technical details, the implications of your answer are immensely interesting to me, and hopefully to others who will read this as well. Thank you for taking the time to answer, and kudos on the great work!

**Comment by leobattin** [comment]
Quick question though : If we only consider, say, the few first moves, or event the first move, wouldn't it save a lot of computational power and allow more in depth search if the bot's thinking was constrained to a quarter of the board ? Or the things you talked about still apply ?

**Comment by lightvector** [comment]
It would save a bit of compute power on the first few moves to also apply it to the search, yes. I think this is not worth doing. It increases the complexity of the code, including requiring careful corresponding adjustments to how the data is written and normalized.

Since the board is only typically symmetric for move 1, move 2 (if move 1 was 4-4 point) and move 5 (typically only if moves 1,2,3,4 were all 4-4 points) and usually is not symmetric for any other move of the game, the gain would only be something like a 1% speedup over the whole game naively. Adding code complexity for a 1% speedup is not very exciting. 

And the gain becomes even less once you add in smarter time management, because smarter time management would heavily decrease the time you would spend on early opening moves. It's not like thinking longer on move 1 is going to find a better move - the bot is going to play a 4-4 or a 3-4 point regardless, and for the subsequent moves, deep search is not going noticeably alter the bot's instincts from seeing that same position again and again for millions of games. So you might as well play fast and save the thinking for later. Similarly, it becomes almost no gain at all if you add in an opening book, because the board will be asymmetric by the time you get out of book.

**Comment by leobattin** [comment]
Makes sense. Thanks!

**Comment by battinleo** [comment]
https://lightvector.github.io/katagostudies/202607-symmetry/ in depth article about the topic. Thanks for writing it.
