### ISSUE TITLE
Analysis display in the case of a large difference in points

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#337]
I raise the issue that can occur when specifying KataGo as the engine in Lizzie for analysis, when the point difference is large.
Take a look at the screenshot below.
The candidate move with the greatest number of searches and point differential is M-15, but there is no blue mark there. You can also see many candidate moves that look like noise with a search count of 1-5.
Setting the analysisWideRootNoise to a value like 0.01 doesn't seem to make much difference.
I couldn't determine if this is an issue on Lizzie's side or KataGo's side, so I posted this on both Issues. if it's an issue on KataGo's side, Is it possible to fix these problems by changing the settings in the cfg file?

![ff](https://user-images.githubusercontent.com/63999713/97438068-a83fa000-1967-11eb-982c-d18b046f563c.png)

**Comment by lightvector** [comment]
There should be no bug in KataGo here, it will be marking either M15 or J15 here as the top move, since they are both high-visits here and both have almost equally high scores. Sometimes other factors will make KataGo mark as the top move the non-top-playouts move, but it will never be as extreme as you show unless you deliberately misconfigure KataGo and put in lots of weird settings.

Almost certainly you have something misconfigured in Lizzie to make it color moves based on some function it computes on its own, instead of trusting what the bot says is the best move. Probably some option like "color the move with the highest winrate, ignoring how many playouts it has or what its score is".

**Comment by lightvector** [comment]
Yep, and it looks like that's an option in Lizzie. I'd say it's outright a bug that the option even exists in Lizzie. It's almost never what you want, and due to the noisiness of MCTS evaluations on low playouts, it doesn't work well with *any* modern bot precisely because of issues like this.

**Comment by hope366** [comment]
Thank you for your reply.
Lizzie has an option to "color by win rate instead of number of attempts", which seems to have been enabled.
I think confusion can occur when the point difference is very large, like this one.
Sometimes the candidate move with the largest number of searches is not necessarily the one with the largest margin of victory, so maybe this option is there to take that into account.

**Comment by lightvector** [comment]
No, I think it is simply a bad option and you should never enable it.

If the move with the largest number of visits is not the best move, then it is up to the bot to determine that. You may notice that *both* LZ and KataGo already will sometimes have the "blue" move be on a move that doesn't have the largest number of visits, even if you don't have this option enabled! This is because there is already a mechanism for the bot to report what it believes the best move is, taking everything into account, even overriding the "max-visits" rule when the bot judges it to be appropriate.

In such a case, the 2-visit move is almost certainly not "the largest margin of victory", it is simply noise. A GUI should not be in the business of confusing users by misreporting the bot's judgment of the best move according to a criterion that makes it possible to see a 2-visit move as "best" compared to moves that have thousands of visits... especially when the bots it would be used with *already* will report on their own when they think a non-top-visits-move isn't just noise and *can* be chosen.

**Comment by hope366** [comment]
Thank you for the detailed explanation.
Please take a look at the screenshot below.
The blue candidates do not have the highest number of searches and wins. In this case, does KataGo consider the green candidate move to be the best move?
![dd](https://user-images.githubusercontent.com/63999713/97604941-6854e780-1a51-11eb-9a5b-d63bd36a07e6.png)

**Comment by lightvector** [comment]
No. Assuming you have Lizzie configured correctly and non-buggily, it will always report as blue the move that KataGo has indicated as its top preference. So in this situation, KataGo would prefer the blue move if it had to choose right now with no further ability to search.

It has a very similar number of playouts, slightly worse predicted winrate, but slightly better predicted score, and KataGo cares about score as well as winrate - and catching up on score without paying as much attention to winrate alone in handicap games can sometimes even be a good strategy for winning, since when all winrates are very extreme, small differences in winrate for you may not be reflective of the winning chances for a weaker opponent.

Of course, the preference may change with more search.

**Comment by hope366** [comment]
Maybe it's because I wanted to check your reply quickly, but it seems I woke up after only 4 hours^^!
I seem to have overlooked the slightly higher prediction score for the blue candidate hand.
The clear explanations helped me to understand it better.
Thank you very much.
