### ISSUE TITLE
katago do not recognize critical move

### ISSUE THREAD

**Issue by jungsup824** [lightvector/KataGo#340]
![katago problem](https://user-images.githubusercontent.com/34597284/98420034-4c8cb980-20c1-11eb-9820-d9cd3a2e1487.png)
As you can see in the attached, white winning ratio was around 80% but after black 160 move, it became 30%. Katago did not recognize move 160 even i am waiting for more than 1 hour. I My graphic card is RTX2070 super. I played this game with a  Chinese in Tygem. I have encountered this kind of problem a several times when I am playing with Chinese AI.

**Comment by jungsup824** [comment]
![katago problem1](https://user-images.githubusercontent.com/34597284/98420811-f0c33000-20c2-11eb-92e9-1606ed7f4ccd.png)
I am sorry move 151 not 160.
I am using cuda10.2

**Comment by lightvector** [comment]
Thanks. Firstly, please be aware that in practice no matter how strong KataGo becomes, there will *always* be misevaluations and missed moves in some positions. No Go AI is anywhere near yet to solving 19x19 (even 9x9 is not entirely for sure yet!), so it will always be the case in bot versus bot games that something will be misevaluated by at least one side. Because, the percentage starts near 50% but must eventually reach 0% or 100%, therefore it must always be the case either one side or the other (or sometimes both!) will find themselves losing many % in a way they didn't expect.

If you would like, you can try adding something like `analysisWideRootNoise=0.04` or `wideRootNoise=0.04` parameters in the config. They will make the search noticeably wider and explore more moves, and reduce the likelihood of entirely missing critical moves. The tradeoff will be that the search on other moves will be less deep, so that will also increase the likelihood of smaller errors due to generally less deep search and less good evaluation. The overall effect will usually be to make the strength weaker, but if you prefer less commonly losing due to missing a single major move and instead more commonly losing due to gradually losing ground in many small errors, you can try these parameters.

Lastly, although it will always be the case that there will be some missed moves, if you would like, you may provide an SGF for the full game and I can consider adding it to future training to fix this particular shape. Can you post one here?

**Comment by jungsup824** [comment]
Thank you very much for your kind explanations. 
[katago problem.zip](https://github.com/lightvector/KataGo/files/5505637/katago.problem.zip)

Please kindly review the attached sgf file and I hope it will be fixed in the future update.
Best regards,
Jung Sup

**Comment by lightvector** [comment]
Thanks!
