### ISSUE TITLE
Questions about staticScoreUtility, dynamicScoreUtility

### ISSUE THREAD

**Issue by isseebx123** [lightvector/KataGo#344]
Can you explain staticScoreUtility, dynamicScoreUtility?
``` cpp
double Search::getScoreUtility(double scoreMeanSum, double scoreMeanSqSum, double weightSum) const {
  double scoreMean = scoreMeanSum / weightSum;
  double scoreMeanSq = scoreMeanSqSum / weightSum;
  double scoreStdev = getScoreStdev(scoreMean, scoreMeanSq);
  double staticScoreValue = ScoreValue::expectedWhiteScoreValue(scoreMean,scoreStdev,0.0,2.0,rootBoard);
  double dynamicScoreValue = ScoreValue::expectedWhiteScoreValue(scoreMean,scoreStdev,recentScoreCenter,searchParams.dynamicScoreCenterScale,rootBoard);
  return staticScoreValue * searchParams.staticScoreUtilityFactor + dynamicScoreValue * searchParams.dynamicScoreUtilityFactor;
}
```

As far as I understand, I know that scoreUtility is used in the PUCT formula. What changes can you expect when you adjust the scale and center arguments in the expectedWhiteScoreValue function?

Among the contents of the paper, there seems to be an explanation related to the center argument.
> At the start of each search, the utility is re-centered by setting x0 to the mean ˆµs of the neural net’s predicted score distribution at the root node.

What does this do?

Finally, I have one more question.
In the configuration file below, staticScoreUtilityFactor is set to 0.0 and dynamicScoreUtilityFactor is set to 0.3.
https://github.com/lightvector/KataGo/blob/master/cpp/configs/training/selfplay8b20.cfg#L148
```
staticScoreUtilityFactor = 0.00
dynamicScoreUtilityFactor = 0.30
```

But when actually playing, for example gtp_example.cfg, the default staticScoreUtilityFactor seems to be 0.1 and dynamicScoreUtilityFactor 0.3. Can you explain the reason for this different setting?
``` cpp
if(cfg.contains("staticScoreUtilityFactor"+idxStr))
  params.staticScoreUtilityFactor = cfg.getDouble("staticScoreUtilityFactor"+idxStr, 0.0, 1.0);
else if(cfg.contains("staticScoreUtilityFactor"))
  params.staticScoreUtilityFactor = cfg.getDouble("staticScoreUtilityFactor", 0.0, 1.0);
else
  params.staticScoreUtilityFactor = 0.1;
if(cfg.contains("dynamicScoreUtilityFactor"+idxStr))
  params.dynamicScoreUtilityFactor = cfg.getDouble("dynamicScoreUtilityFactor"+idxStr, 0.0, 1.0);
else if(cfg.contains("dynamicScoreUtilityFactor"))
  params.dynamicScoreUtilityFactor = cfg.getDouble("dynamicScoreUtilityFactor", 0.0, 1.0);
else
 params.dynamicScoreUtilityFactor = 0.3;
```

Sorry for asking so many questions and always thank you.

**Comment by lightvector** [comment]
Static makes KataGo like gaining points when the score is close to 0, and cares less for scores is far from 0. (example: the difference between win by 5 and win by 10 is much more important than the difference between win by 30 and win by 35).

Dynamic makes KataGo like gaining points compared to the predicted score now, and care less for scores very far from the predicted score now. (i.e. the difference between gain 5 points and gain 10 points is much more important than the difference between gain 30 points and gain 35 points).

They are basically the same except static is centered at 0, dynamic is centered at the score right now.

In selfplay we train using dynamic only. Always trying to gain points seems like a decent instinct train into the neural net. In actual play we add a bit of static so that KataGo cares a bit more near 0. But this is an arbitrary choice, you can set it to whatever you prefer based on the above description of behavior.

Now, you can read the paper again with this understanding if you care about the exact formula (or you can read the source code)
