### ISSUE TITLE
final_score outputs only W+ 

### ISSUE THREAD

**Issue by seopsx** [lightvector/KataGo#35]
I've been experiencing the following problem with both Sabaki and Lizzie: final_score command outputs always W+ (ie. W+7.5) even if Black has a lead/is winning according to the winrate. The points can differ but the lead is always for white.

OS: Ubuntu 18.04

**Comment by lightvector** [comment]
I'm guessing you tried to use that command in unfinished board positions where neither player has any territory surrounded. Then, white will probably have a positive final score due to komi.

My understanding of the final_score GTP command is that it is supposed to be used to score a finished game, i.e. return the score as if the position were scored as-is _under the rule set that the bot itself follows_. GTP leaves it unspecified what ruleset the bot can use, so like other zero bots, KataGo chooses to use Tromp-Taylor-like rules (https://senseis.xmp.net/?TrompTaylorRules). In Tromp-Taylor rules, the rules make no attempt to define life and death - all stones on the board are scored as if they were "alive", and territory is only counted if it is completely enclosed. So to finish the game, a player must close off all borders AND needs to play to capture and remove all stones they believe are dead from the board.

Unless you observe something different, I believe there should be no bug here. KataGo actually optimizes Tromp-Taylor rules in slight ways (it will actually not require capturing dead stones in certain special cases!), but for the most part you should expect final_score to return the score of a position if scored under rules that are more or less like Tromp-Taylor rules.
