### ISSUE TITLE
Error generating new customized config

### ISSUE THREAD

**Issue by GJH-HIT-ICT** [lightvector/KataGo#353]
I am new to Katago. I've just downloaded the windows version of Katago v1.4.5. I am trying to generate a customized config file following online instructions. However, the program abnormally exits during PERFORMANCE TUNING, without any logs or instructions. Any suggestions? 

I am using a RTX 3070, with cuda 10.2 and cudnn 7.6.5.

![Katago](https://user-images.githubusercontent.com/1468760/99898907-30536400-2ce0-11eb-9f12-63dbf660828e.PNG)

**Comment by lightvector** [comment]
Use the latest version of KataGo (1.6.1) rather than an older version, and use the OpenCL version instead of CUDA. As documented in a few places, the OpenCL version is the version everyone should use by default, and the CUDA version is only for people who are willing to to through extra technical trouble and setup and debugging who care about every bit of performance. 

And even then, it might actually be slower than the OpenCL, so you have to compare it vs OpenCL it on your specific hardware, which means that you always will want to set up the OpenCL version first anyways.

If you insist on using CUDA, then you'll need to install CUDA 11 and CUDNN 8. I think newer GPUs don't work with CUDA 10.*.

**Comment by lightvector** [comment]
Oops, actually 1.7.0 is the latest. Releases page here: https://github.com/lightvector/KataGo/releases

Hope that helps!

**Comment by GJH-HIT-ICT** [comment]
> Use the latest version of KataGo (1.6.1) rather than an older version, and use the OpenCL version instead of CUDA. As documented in a few places, the OpenCL version is the version everyone should use by default, and the CUDA version is only for people who are willing to to through extra technical trouble and setup and debugging who care about every bit of performance.
> 
> And even then, it might actually be slower than the OpenCL, so you have to compare it vs OpenCL it on your specific hardware, which means that you always will want to set up the OpenCL version first anyways.
> 
> If you insist on using CUDA, then you'll need to install CUDA 11 and CUDNN 8. I think the very newest nvidia GPUs don't work with CUDA 10.*.

Thanks. Swithcing to the lastest version does solve the problem.  Cuda and cudnn also work.
