### ISSUE TITLE
Issue tunning katago after mesa update (CL_BUILD_PROGRAM_FAILURE?)

### ISSUE THREAD

**Issue by mfpuentear** [lightvector/KataGo#357]
Getting error (see attached file) after a mesa update from 20.2.2 to 20.2.3. I have my doubts if it's due to a mesa update but it stop working.

Command used:
katago genconfig -model g170e-b20c256x2-s5303129600-d1228401921.bin.gz -output out

KataGo version: 1.6.1 and 1.7.0

Hardware: Radeon RX 570 Series (POLARIS10, DRM 3.39.0, 5.9.10-arch1-1, LLVM 11.0.0) (AMD) (score 11000101)

OS: Linux (Arch)

[tunning_output.txt](https://github.com/lightvector/KataGo/files/5599746/tunning_output.txt)

**Comment by lightvector** [comment]
I know in the past other people have reported issues with OpenCL Mesa drivers and some people have never been able to make them work at all, due to known open bugs in the driver itself when used with OpenCL programs. I made it an FAQ item here: https://github.com/lightvector/KataGo#issues-with-specific-gpus-or-gpu-drivers

Perhaps you have been lucky up until now for it to be working, and then it broke now due to update? In any case, the expectation in the first place is that if you use Mesa drivers then you should not count on its OpenCL to be stable. Do you have alternative possible drivers for that GPU?

**Comment by mfpuentear** [comment]
After trying alternative drivers it worked again, closing the issue

**Comment by PicoGeyer** [comment]
@mfpuentear Do you perhaps have info on what driver you used to solve the issue?
I'm on arch linux as well but using an older R9 280x card.
Did you just install opencl-amd ? Or did you have to install the propriety amdgpu-pro package?
