### ISSUE TITLE
1.7.0 can no longer read correct score of this game after 2nd pass

### ISSUE THREAD

**Issue by ivorget** [lightvector/KataGo#366]
Thanks for the great Go engine.

In this game, KataGo can correctly read the final score until it becomes confused after the 2nd pass (move 48). Komi is zero.

Tested with both g170 and g170e 10b networks. Running opencl on Intel HD.

SGF file is linked at bottom and here's a GTP excerpt starting with move 46:

```
play w c7
=

showboard
= MoveNum: 46 HASH: B8B8461FC8F284E7DB53A42BB4DB2C71
   A B C D E F G H J
 9 . . . . . . . . .
 8 . . . . . . . . .
 7 . . O3O O O . . .
 6 . O . O X O1O O O
 5 O O O X X X2X O X
 4 O X X X . X X X X
 3 X . . O O X O O .
 2 . X . . X . X O .
 1 . . . . X X . X .
Next player: Black
Rules: {"hasButton":false,"ko":"SIMPLE","komi":0.0,"scoring":"AREA","suicide":false,"tax":"NONE","whiteHandicapBonus":"N"}
B stones captured: 2
W stones captured: 3

final_status_list dead
= D3 E3 G3 H3 H2

final_score
= B+1.0    (this is correct)

play b pass
=

play w pass
=

final_score
= W+22.0   (wrong)

final_status_list dead
=
```

[KataGo_confused_afte_ 2nd_pass.sgf.txt](https://github.com/lightvector/KataGo/files/5699217/KataGo_confused_afte_.2nd_pass.sgf.txt)

**Comment by lightvector** [comment]
This is correct behavior under the ruleset that KataGo plays under. When playing with Chinese-like scoring, Go bots are generally trained with https://senseis.xmp.net/?TrompTaylorRules or similar variation of those rules. In particular, both players are required to capture the stones that they believe are dead before passing. If stones are not captured, they are scored as if alive, and empty regions bordering stones of both colors are treated as nobody's territory, exactly as they would be in a seki. 

Indeed, correctly distinguishing between dead stones versus seki stones in all cases is extraordinarily difficult to do if the bots do not play it out. By playing it out, hat there is never even the slightest need for outside adjudication of life/death , or detecting sekis, or dispute resolution after the end of the game. The scoring can then be very simple and completely mechanically automated.

In your example, White wins by 22 because Black has made the mistake of passing without capturing White's stones. After the second pass, the game is over, and Black has very little scoreable territory because most of what should be Black's territory is open and adjacent to the White stones that Black failed to capture and prove were dead.

**Comment by ivorget** [comment]
OK I guess I mistook Chinese-like scoring as Chinese then (which I realise is a collaboration between players IRL). At least black is Crazy Stone here and it counted itself as winning when passing. In that case I can just refer to the pre-pass score when appropriate. Thanks for the explanation.
