### ISSUE TITLE
The weight of kata1 becomes an error in lizzie

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#371]
When I tried to run the newly released "s510", "s512", and "s514" on kata1 with lizzie, the following error message appeared.
>Uncaught exception: Error loading or parsing model file kata1-b40c256-s5109387264-d1232289301.bin.gz: kata1-b40c256-s5109387264-d1232289301: model found unsupported version 10

s509 worked. Probably older versions will work.
Do you have any good advice?

**Comment by lightvector** [comment]
There is no release yet that supports these newest models, you need to custom-compile from Github. There was a release planned for last weekend but I had to delay due to work to deal with errors on the website due to the newly starting run, so the release is delayed a bit. I'll get to it when I can.

**Comment by lightvector** [comment]
If you'd like to compile yourself from Github, the tip of "master" branch should be able to run the models.

**Comment by hope366** [comment]
thank you very much!
