### ISSUE TITLE
Is it worth using NNUE to replace FPU?

### ISSUE THREAD

**Issue by CGLemon** [lightvector/KataGo#379]
An efficiently updatable neural network(NNUE) is pretty great ideal to improve the traditional chess engine. The result is the stockfish significant strong. It won TCEC season 18 and season 19.

Obviously, the NNUE adaption of the Go is not good ideal because there are more possible moves. But I think that it is an opportunity to use NNUE to replace FPU.  Its computation time is very short. It can provide rough value for non-expansion nodes.

Is it worth doing that?

**Comment by lightvector** [comment]
Have you considered about how NNUE works and do you have a serious proposal for how to make it work here?

It has very little to do with the number of possible moves. It's more about the fundamental nature of the game. In Chess it works for the same reason that hand-crafted evaluation functions work: we know that even extremely simple and shallow features (e.g. material values and simple piece-square and piece-piece relationships) can already provide a decent evaluation of the game. So at least _in retrospect_, it's not too surprising that a shallow neural net can do well.

Think about it in Go. How is a shallow neural net supposed to correctly judge the life and death status of a large dragon in the late midgame using only shallow features? There are a large number of possible patterns for eyes and partial eyespace values too numerous to exactly enumerate all the possibilities, and you have to trace that information all the way across the board (the eyes may be far apart) through a whole bunch of shapes that you have to judge whether they are connected or not (bamboo joints, hanging connections, etc), which are also too numerous to enumerate. I don't currently see how it can be done in just a few layers of incrementally-updatable features. 

Even if all you need is to compute FPU rather than an accurate evaluation, it seems likely to be worthless if you can't judge large group status - a dragon being live or unsettled dead is the difference between 1% winrate and 99% winrate, or the difference between a move there being the biggest move on the board, versus a waste of ko threats or even death in gote.

Do you have a proposal for what incremental architecture or feature set would be able to learn a set of topological connection shapes and trace them accurately across a large board, one that would work with limited functional form that you would be able to obtain from 2-3 neural net layers plus a choice of nonlinearity?

**Comment by CGLemon** [comment]
This is my mistake to ignore that the shallow network is difficult to evaluate the accurate value. In my original ideal, the Network is same ideal as the NNUE but changing the fully-connect to convolution in order to adapt itself to different board size. Finally, it will evaluate the final score of current player. But the value-based evaluation is seldom on Go even before the AlphaGo. The most methods are policy-based that because value-based evaluation based either nn-like or handicraft is hard to evaluate accurate value. And knowing that the Leela's 12-Conv network did not evaluate the accurate value either. I thought it is stupid idea that NNUE applied to Go. 

After all, Thank you for your proposal.

**Comment by Smooshy30** [comment]
HalfKP for Shogi was something like 170k inputs
For 2-stone relations, HalfPP on a 19x19 Go board is 361*360=129960 inputs, with the weights used for both sides
Inputs for 3-stone relations are out of the question, due to sheer increase in memory size of the network (~46 million inputs)
Hard to say if it will be practical to implement with such limitations
