### ISSUE TITLE
katago.exe cannot find "Nvidia GeForce MX150"

### ISSUE THREAD

**Issue by FinixLei** [lightvector/KataGo#383]
Hi, please see my operations as below. 
1. Downloaded ```katago-v1.7.0-gpu-opencl-windows-x64.zip```, then unzip it to ```C:\katago_1.7_gpu```
2. Copy weight file xxx.bin.gz to ```C:\katago_1.7.gpu```
3. Open a normal terminal window, and run ```katago.exe genconfig -model xxx.bin.gz -output gtp_custom.cfg```.
    Then input some configurations. 

After step 3, it outputs "**Finding available GPU-like devices...**", then terminated. 
Looks like it cannot find any GPUs. 
But open "TaskManager" of Windows, it shows there are 2 GPUs. 
- The first one is called "GPU 0", it is ```Intel(R) UHD Graphics 620```.
- The second one is called "GPU 1", it is ```NVIDIA GeForce MX150```.

Why katago.exe cannot find these 2 GPUs? Thanks.

**Comment by lightvector** [comment]
If it terminates with no further messages at all, then I think the problem is not about detecting the devices. If it simply found 0 devices, it would print that there aren't devices, and this would cause failures later, but I think it shouldn't terminate immediately. Instead what is probably happening is that when KataGo tries to call OpenCL, OpenCL crashes without any messages or warning, or something like that.

Given that you have an NVIDIA GPU, does the CUDA version work for you? (Note: you may need to install manually both CUDA and CUDNN if you haven't done so). Have you made sure your drivers are up to date? Do other OpenCL programs work for you, such as Leela Zero, or do they also fail?

**Comment by FinixLei** [comment]
I did not install CUDA. Will close this issue.
