### ISSUE TITLE
Can' compile KataGo under MacOS

### ISSUE THREAD

**Issue by zliu1022** [lightvector/KataGo#397]
Hi, 

Could anyone help me to take a look?
I can't compile KataGo under MacOS with the latest master branch.
No problem with the `cmake` command, but there's no katago executive progrom output.

macOS Catalina 10.15.7

Thanks

```
zliu@MacBook-Pro github % cd KataGo/cpp 
zliu@MacBook-Pro cpp % cmake . -DUSE_BACKEND=OPENCL
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building 'katago' executable for GTP engine and other tools.
-- -DUSE_BACKEND=OPENCL, using OpenCL backend.
-- Including Git revision in the compiled executable, specify -DNO_GIT_REVISION=1 to disable
-- Found Git: /usr/local/bin/git (found version "2.19.1") 
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenCL.framework (found version "1.2") 
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/zliu/github/KataGo/cpp
zliu@MacBook-Pro cpp % ls
CMakeCache.txt			cmake_install.cmake		distributed			neuralnet			runsearchtestsfp16.sh
CMakeFiles			command				external			program				runsearchtestslimited.sh
CMakeLists.txt			configs				game				runcmdtests.sh			search
Makefile			core				main.cpp			runoutputtests.sh		tests
README.md			dataio				main.h				runsearchtests.sh
```

**Comment by steve-biggs** [comment]
cmake does not make the program - it just makes the Makefile. After running cmake, you have to then run make.

**Comment by zliu1022** [comment]
Thank you.

But I still find some error. Would you like help me more?

![image](https://user-images.githubusercontent.com/3665494/106258666-19d60580-6259-11eb-908b-cb39b66519d5.png)

**Comment by steve-biggs** [comment]
It would appear that your C++ library version is too old. For example, look at the last error:

cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?

[This page](https://en.cppreference.com/w/cpp/numeric/math/isgreater) shows that `isgreater` was in since C++11 and this page shows that `greater` was in until C++14. This suggests that your C++ version is older than C++11. The KataGo docs say you need C++14 or later. You may or may not be able to get away with C++11 but it seems that older than C++11 is just too old.

FYI - C++11 was in gcc since version 4.8, released 2013, so it seems your compiler is older than that, which is pretty old. C++14 was in gcc since verison 5, released 2015.

What compiler are you using? gcc? intel? And what version? Are you able to easily upgrade the version? I don't know how upgrades work on MacOS but on my Linux distro (debian based) it's `sudo apt update && sudo apt upgrade`. Can you run an equivalent MacOS command?

**Comment by zliu1022** [comment]
Thank you!
I upgrade my gcc to latest version using `brew upgrade gcc`
```
Warning: gcc 10.2.0_2 already installed
zliu@MacBook-Pro cpp % brew search gcc
==> Formulae
gcc ✔                        gcc@5                        gcc@7                        gcc@9                        libgccjit
gcc@4.9                      gcc@6                        gcc@8                        i686-elf-gcc                 x86_64-elf-gcc
==> Casks
gcc-arm-embedded
```
I think this version of gcc is the latest one I can choose.

But the compiler error still exist. 

And I find it strange because this is not first time I compile Katago under MacOS, about 2020 Q1 I can easily compile KataGo, but now, it looks difficult.

**Comment by steve-biggs** [comment]
Hmm... Seems strange... This one is going a bit beyond me now. Probably needs referring to @lightvector

**Comment by zliu1022** [comment]
After I remove `/usr/local/include`, reinstall `xcode`, upgrade `brew`. 
And manually link some header file `zip.h`, `zipconf.h` and `libzip.dylib`.
Now I can compile katago! Great.

Thanks all.
I will close this issue.
