### ISSUE TITLE
Lost weights

### ISSUE THREAD

**Issue by GD-fix** [lightvector/KataGo#412]
In new distributed run (https://katagotraining.org/networks) were imported a huge number of no one needed ...b6c96... networks (because of imported here ...b10c128... one, that are stronger in this "bantamweight" category), but were not imported neither ...b30c320... nor ...b40c384... of much stronger "weight categories"...

**Comment by lightvector** [comment]
Haha, nobody lost these weights. They're all still here: https://d3dndmfyhecmj0.cloudfront.net/

Simply, there was a choice of which networks to import. We import a lot of the smaller networks early on because each successive smaller network differs quite a lot in strength from the next one. Once successive networks started becoming a lot more similar to each other, we skip networks, since there is little point for historical purposes to have networks that are too close together. Anyways, making sure you have one network at each reasonable spacing of strength: that's how you get such a pretty rating graph. All of it based on fresh new unbiased games. :)

![image](https://user-images.githubusercontent.com/11942395/107119904-830cd880-6858-11eb-8959-3fc9571246c1.png)

b30c320 is deliberately not uploaded because there is no point at which it ever clearly outperformed b40c256, and by the end was noticeably weaker even at equal visits, and definitely at equal time (because it is very slightly slower than b40c256).

b40c384 is deliberately not uploaded because for some users who want to contribute, it will cause them to run out of GPU memory, and because it is much slower and more expensive and too soon to switch to such a larger net anyways. We are planning to switch to b60c320 instead, when the time is right. It turns out that the memory cost depends only on the "c", so "c320" will be less taxing on memory than "c384", and additionally, an alteration has been made to the architecture of the net which will roughly cut in half the GPU memory needed.

**Comment by GD-fix** [comment]
New version of KataGo works with old (not imported) networks, , am I right?

**Comment by lightvector** [comment]
Yes, v1.8.0 supports all of g170's networks.
