### ISSUE TITLE
Comparison of the used for KataGo networks rate and the Elo rating

### ISSUE THREAD

**Issue by GD-fix** [lightvector/KataGo#420]
How do relate the rate, that was used for KataGo networks strength benchmark (https://user-images.githubusercontent.com/11942395/107119904-830cd880-6858-11eb-8959-3fc9571246c1.png), and the Elo rating (for example: https://www.nature.com/articles/nature24270/figures/3 or https://science.sciencemag.org/content/sci/362/6419/1140/F1.large.jpg)?

**Comment by lightvector** [comment]
They are not directly comparable, although you can get a sense of magnitude. As usual, the zero point is arbitrary, but I'd say that Elo ratings *differences* from different sources are often not off by more than a factor of 1.5 plus a small constant, if they were each computed sensibly and unbiasedly and with enough variety of opponents.

Anyways, you can see KataGo's at katagotraining.org:
```Graph is based on about 144,136 rating games using mid to high hundreds of playouts. Ratings might still be mildly inflated due to only playing other KataGo nets, but otherwise are fresh and unbiased and involve a variety of nets to avoid rock-paper-scissors. Vertical bars indicate approximately a 95% confidence interval.```
Currently, 500 playouts per move, plus whatever you get from tree reuse, and with LCB turned on, but also some opening temperature and random rules.

I leave it to you to read the caption and the body of the document for AlphaGo on your own to determine what they stated about their testing. :)

**Comment by GD-fix** [comment]
OK. I had read it some times ago (how it is possible with my NO big English knowledge). And how I had understand, the AlphaGo Elo rating was achieved from playing with some human champions, the AlphaGo Zero - with AlphaGo and the AlphaZero - with AlphaGo Zero.
And how it was achieved the rating of "human pros" (how I understand, the highest level of it is the human champions one), "ELF" and "LZ" in KataGo rate graph which "is based on about 144,136 rating games... only playing other KataGo nets"?

**Comment by lightvector** [comment]
No, AlphaGo's ratings in Deepmind's paper were determined by only internal matches against AlphaGo versions. They have nothing necessarily to do with any human ratings or any other ratings in any other system.

KataGo's ratings in the image you linked are determined only by matches against other KataGo nets. They also have nothing to do with human ratings or ratings in any other system. 

That's why I said you cannot directly compare them.

> And how it was achieved the rating of "human pros" (how I understand, the highest level of it is the human champions one), "ELF" and "LZ" in KataGo rate graph which "is based on about 144,136 rating games... only playing other KataGo nets"?

It is just a guess, it is not based on measurements. We know from anecdotal tests from LZ back in March 2018 that well-trained networks start to reach pro strength at 10 blocks size, and we know from some later tests that they tend surpass human strength at 15 blocks size.

**Comment by lightvector** [comment]
You can tell it's just a guess, because "Human pros somewhere around here?" using the word "somewhere" and a question mark which both indicate uncertainty, as well as giving a pretty wide range instead of indicating a precise point that corresponds to a precise human rating. :)

**Comment by GD-fix** [comment]
"... and we know from some later tests that they tend surpass human strength at 15 blocks size."
Without playing with champions?

**Comment by lightvector** [comment]
Sure, because arranging matches with "champions" is not a thing that LZ was able to do in March 2018. You work with the data that you have, not with the data you wish you had. :)

But yes, if you start winning some games against pros in the top 300 pros, and not losing any games against them in a few tests, and then you start talking about improvements on top of that of a thousand or more Elo (the top 300 human pro range is *not* as wide as that in Elo)...

... and users using AI to follow along with games also notice that the bots are pointing out clear mistakes even in title match games much more often than the move in the game surprising them and showing the winrate as inaccurate (even though it still happens occasionally, even with current bots), and even pros themselves start treating the AI's move as correct in commentary or review... 

...then it's pretty clear that somewhere along the way you've reached superhuman, even if there is a high uncertainty as to exactly where. LZ110 was around when some of this started, by the time LZ reached LZ157, it was very clear that it was very superhuman on strong single-machine hardware. LZ157 remained popular for quite a long time as a net people used for analysis.

**Comment by lightvector** [comment]
Also, if you want another reference point, AlphaGo Lee was about equivalent in size to 6 blocks x 256 channels. That puts it probably somewhere in between 10 blocks x 128 channels and 15 blocks x 192 channels. But also AlphaGo Lee used a *much* worse neural net architecture, so as a blind guess I'd peg it as being closer to the quality of LZ's 10 block nets.

So, that's another point of evidence showing that around 10 blocks with modern nets is enough to reach pro strength or even top pro strength, and going any larger quickly surpasses it.

**Comment by GD-fix** [comment]
What is the LZ157 network? 
How I know, the strongest 15 blocks LeelaZero network is the 15b_270_856k_q from https://leela.online-go.com/networks/?C=M&O=D...

AlphaGo Lee used convolutional network architecture and only AlphaGo Zero started to use residual (contained 20 residual blocks) network architecture (https://www.nature.com/articles/nature24270#Fig4). And convolutional network is equivalent to 1 block residual network, am I right?

**Comment by lightvector** [comment]
LZ157 is network 157 on this page: https://zero.sjeng.org/ - which is the official page. Around its time, 157 was a very popular size for users to use, because even when other networks became stronger, it was fast to run LZ157, it was official and easy to get since it was sometimes packaged with various things and didn't require manual download, and was still more than strong enough. It's a nice benchmark opponent for young Go AIs as well, being good until you become too much stronger than it.

A convolutional network with N layers not including the output head is approximately equivalent to a residual network with N/2 blocks. Because each block has 2 convolutional layers in it.

**Comment by GD-fix** [comment]
I didn't find any network "157" on this page. There are only the same archives (hashes) with the same networks as on mentioned by me page...

Thanks for clarification. I heard, that convolutional networks aren't so scalable with layers number growth,how are residual ones with blocks number growth. Am I right?

**Comment by lightvector** [comment]
Did you miss it?
![image](https://user-images.githubusercontent.com/11942395/109391370-bafdbd80-78e4-11eb-8119-a5a29e36055d.png)

Among official LZ networks that were accepted by gating, commonly people refer to them by this number rather than by hash.

**Comment by GD-fix** [comment]
There is leelaz-model-swa-24-192000.txt network (You can open this hash archive and see it). It's no so strong as 15b_270_856k_q is (You can test them with appropriate number of games)...

**Comment by GD-fix** [comment]
Its hash is 0c4ade7958b3441b9f13ecd06f99f11540e5e4d595127f7f3eb73f0c02b58d92...
