### ISSUE TITLE
Training goes idle in the merging step

### ISSUE THREAD

**Issue by jano-wol** [lightvector/KataGo#422]
Hi,
 
at the merging step of the training (introduced by "with TimeStuff("Merging"):" in the script shuffle.py) sometimes my training process stops.
I monitored the resource handling of the process and saw, that before the process stopped it took a huge amount of memory (15Gb RAM + 2Gb swap), calculated for a while, then it freed most of its memory and processor resources and went idle. 
After restart there is a chance that the merging step is successfully completed. In this case the resource handling is very similar, but the process does not go to idle at the end.   
 
On my config:
I am running the synchronized version of the training on my PC. This PC is not very strong (1 1060 GTX GPU, 16Gb RAM) but I am training the smallest model b2c16 (I am very satisfied with its strength!). I am surprised by the huge memory usage of the merging step, although I have to admit that I don't know what happens in this step.
The other training parameters are default:
NUM_THREADS_FOR_SHUFFLING=8
NUM_TRAIN_SAMPLES_PER_CYCLE=500000
BATCHSIZE=128 
SHUFFLE_MINROWS=80000
SHUFFLE_KEEPROWS=600000 

Did you see this problem before? Do you have any suggestions how to handle this problem?

**Comment by lightvector** [comment]
The shuffling step is forking 8 python processes in order to shuffle the dataset, which involves loading a bunch the data you've written out and shuffling it, and then writing it down.

I haven't seen this problem before, but I haven't run out of memory shuffling before - so I'm guessing for you it either failed that time when running out of memory, or it got stuck forever waiting on slow swap, or something like that.

You could try decreasing NUM_TRAIN_SAMPLES_PER_CYCLE (how many positions should it train on at a time?) and SHUFFLE_KEEPROWS (how many positions should it try to shuffle at a time for the training to use?). The latter should always be a small factor bigger than the former, but if you shrink them both, it would probably use less memory. You could also try decreasing the number of threads.

**Comment by jano-wol** [comment]
I reduced NUM_THREADS_FOR_SHUFFLING to 4 and it solved the problem. 
Thx for the advise :)
