### ISSUE TITLE
Compiling error 

### ISSUE THREAD

**Issue by jun63cn** [lightvector/KataGo#445]
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(459,31): error C2001: 常量中有换行符
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(460,66): error C2001: 常量中有换行符
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(463,3): error C2059: 语法错误:“}”
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(484,64): error C2001: 常量中有换行符
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(485,90): error C2001: 常量中有换行符
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(488,3): error C2059: 语法错误:“}”
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(511,1): error C2059: 语法错误:“}”
C:\Users\jun\Downloads\KataGo\cpp\dataio\sgf.cpp(484): fatal error C1075: “{”: 未找到匹配令牌

**Comment by lightvector** [comment]
Thanks, will look into this soon.

**Comment by lightvector** [comment]
Should be fixed now in the tip of master. Let me know if there are any more problems. Thanks for reporting!

**Comment by jun63cn** [comment]
It's works. Thanks , there is an error in stable branch: C:\Users\jun\Downloads\KataGo\cpp\distributed\client.cpp(64,70): error C2593: “operator =”不明确

错误(活动)	E0350	有多个运算符 "=" 与这些操作数匹配:	katago 
 C:\Users\jun\Downloads\KataGo\cpp\distributed\client.cpp	64

**Comment by lightvector** [comment]
It worked fine for me on both Windows and Linux, no errors, so I dug around a bit more. It appears that your error is this:
https://github.com/nlohmann/json/issues/2006
which appears to happen only on very specific versions of MSVC in specific cases in json object access. Theoretically, this should be fixed by upgrading the json library, so I did that now. Hopefully should be good now?

**Comment by jun63cn** [comment]
It' works fine .Thank you very much!
