### ISSUE TITLE
suggest to remove models from the source code to reduce the file size

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#45]
namely
```
g103-b6c96-s103408384-d26419149-info.txt
g103-b6c96-s103408384-d26419149.txt.gz
grun2-b6c96-s128700160-d49811312-info.txt
grun2-b6c96-s128700160-d49811312.txt.gz
grun50-b6c96-s156348160-d118286860.txt.gz
run4-s67105280-d24430742-b6c96-info.txt
run4-s67105280-d24430742-b6c96.txt.gz
```

**Comment by lightvector** [comment]
Are these actually causing issues for you? Although users will not use them, they are used for some tests that are extremely useful when developing and debugging KataGo, and they are only about 20MB. Removing them at this point would also only partially shrink the size of the GitHub repo since they are part of the commit history. (Which is why I've been very careful to only include 6-block networks in here, precisely to limit the disk usage).

**Comment by l1t1** [comment]
they may useful to real developer/contributor, and may not so useful to common users/fans who only want to build from source.

**Comment by lightvector** [comment]
Right, but they are also only 20MB, and because they are useful to devs/contributors, it seems to me overall useful to leave them in there.

**Comment by lightvector** [comment]
Closing this issue, at this point, I don't think I'm going to be removing them. Feel free to reply back if you think you have additional or new considerations that haven't been accounted for yet.

**Comment by l1t1** [comment]
i see
