### ISSUE TITLE
katago 1.2beta win32 version vcruntime140 error

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#46]
when i run with `katago gtp -model \model.txt -config gtp_example.cfg` on windows7 32b, it shows
the msgbox https://files.fm/u/q74jdhj8

**Comment by l1t1** [comment]
and after i **delete vcruntime140.dll and msvcp140.dll**, katago works.
```
D:\katago>katago gtp -model \model.txt -config gtp_example.cfg
KataGo v1.2-beta
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation)
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation)
Setting winograd3x3TileSize = 4
------------------------------------------------------
Tuning winograd transform for convolutions
Testing 183 different configs
Tuning 0/183 (reference) Calls/sec 272.101 L2Error 0  transLocalSize0=1 transLocalSize1=1 transLocalSize2=1
Tuning 1/183 Calls/sec 272.164 L2Error 0  transLocalSize0=1 transLocalSize1=1 transLocalSize2=1
Tuning 2/183 Calls/sec 353.701 L2Error 0  transLocalSize0=32 transLocalSize1=4 transLocalSize2=1
```

**Comment by l1t1** [comment]
it took about 20 min to test on my notebook (i34010u 4gmem), any method to skip the step?

**Comment by l1t1** [comment]
i compare those files in x86 and x64 zip, they are the same, so maybe the wrong bits files.
suggest to let user install them by themselves.
https://go.microsoft.com/fwlink/?LinkId=746572 
https://go.microsoft.com/fwlink/?LinkId=746571

**Comment by lightvector** [comment]
Thanks, you are right that the x86 version is the wrong bits, I deleted them and added a note to the README file within the zip that the user may need to install themselves. I kept the dll files still present in the x64 versions because in those versions they are the correct number of bits. If you are also able to test 64 bit on a 64 bit windows and you report that those are also causing problems, I will consider removing them in those cases too. Thanks!

For skipping the tuning, what alternative would you suggest? If they run using the reference config, there is a good chance to be WAY slower in visits per second forever, so the tuning is important. If I directly guess a higher-parameter tuning config that won't be so slow, then it might not work at all on OpenCL implementations that don't support those higher parameters.

**Comment by lightvector** [comment]
I'm going to consider this issue solved, as the 32 bit version no longer includes the 64 bit dlls. Please reply back if you think otherwise and I can re-open.

Additionally, in the latest release, the tuning, while still not fast, will at least be by default done only once for all board sizes, so I'm hoping this is okay. Thanks!
