### ISSUE TITLE
loadsgf command shows warning, how to solve it

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#47]
loadsgf test.sgf
WARNING: Loaded sgf has rules koSIMPLEscoreAREAsui0komi7.5 but GTP is set to rules koPOSITIONALscoreAREAsui1komi7.5
=
```
(;GM[1]FF[4]CA[UTF-8]
RU[Chinese]SZ[19]KM[7.5]TM[900]
PW[LZ_05db_ELFv2_p800]PB[h_15b_512k_v3200]WR[3195]BR[2678?]DT[2019-07-06]PC[(CGOS) 19x19 Computer Go Server]RE[B+Resign]GN[576490]
;B[dp]BL[899];W[pd]WL[897];B[pp]BL[897];W[dd]WL[893];B[cf]BL[897];W[qq]WL[889];B[qp]BL[893];W[pq]WL[885]
;B[nq]BL[892];W[nr]WL[882];B[fc]BL[889];W[op]WL[879];B[oq]BL[887];W[or]WL[875];B[mq]BL[887];W[oo]WL[873]
;B[rp]BL[887];W[lq]WL[871];B[mr]BL[886];W[rq]WL[870];B[qm]BL[885];W[po]WL[867];B[qo]BL[883];W[lp]WL[865]
;B[lr]BL[882];W[pm]WL[859];B[ql]BL[880];W[jq]WL[857];B[no]BL[878];W[pl]WL[854];B[pk]BL[876];W[qk]WL[850]
;B[nn]BL[874];W[nm]WL[846];B[rk]BL[872];W[qj]WL[844];B[rj]BL[872];W[qi]WL[841];B[ri]BL[870];W[mm]WL[839]
;B[ns]BL[867];W[ps]WL[834];B[lo]BL[866];W[qh]WL[829];B[ln]BL[864];W[sp]WL[824];B[qn]BL[862];W[so]WL[819]
;B[rh]BL[859];W[qg]WL[816];B[rg]BL[859];W[rf]WL[811];B[nk]BL[857];W[mk]WL[806];B[ok]BL[854];W[nl]WL[802]
;B[mj]BL[852];W[lk]WL[798];B[qf]BL[851];W[re]WL[792];B[pf]BL[850];W[oh]WL[787];B[ni]BL[849];W[nh]WL[781]
;B[mh]BL[846];W[nf]WL[775];B[kj]BL[842];W[kk]WL[769];B[jk]BL[840];W[jl]WL[763];B[lj]BL[838];W[il]WL[759]
;B[jn]BL[836];W[sl]WL[753];B[rl]BL[834];W[sm]WL[746];B[om]BL[832];W[ol]WL[743];B[pn]BL[832];W[on]WL[738]
;B[np]BL[830];W[om]WL[732];B[kl]BL[829];W[km]WL[724];B[lm]BL[827];W[ll]WL[716];B[mn]BL[827];W[ml]WL[710]
;B[kl]BL[826];W[oc]WL[703];B[rs]BL[824])


```

**Comment by lightvector** [comment]
There is no way to solve this because it is not intrinsically a problem. It is simply warning you of something that KataGo will be evaluating the game using slightly different rules than the SGF file claimed to want to use. 

It does look like your SGF file is buggy. Your SGF file claims "Chinese" rules. Human "Chinese" rules normally use simple ko, rather than superko. And a game between ELF and some other bot was almost certainly not played with "Chinese" rules, it was probably played with "Tromp-Taylor" rules.

**Comment by l1t1** [comment]
the lz match also show chinese rule
http://zero.sjeng.org/viewmatch/dd6cbbe58401ed5793e3c84c3bd07de58c4baf966097f41824fb317e095597cb.sgf

**Comment by lightvector** [comment]
Right, I would say those SGF files are also mislabeled. LZ self-play is definitely under Tromp-Taylor rules not Chinese rules. :)
