### ISSUE TITLE
katago Training using symmetry

### ISSUE THREAD

**Issue by jaewoo1120** [lightvector/KataGo#471]
katago Training
Isn't it more efficient to train katago to analyze only the upper right (4,4) and (3,4) coordinates?
I don't think we need to analyze the other three corners because the first moves are symmetrical anywhere.

And in one corner, katago only has to calculate (4,4) and (3,4).
Because others are not symmetrical or meaningful points.

Not just the first move. Wouldn't it be easier to get stronger if we let katago calculate just one place?(Remove the symmetrical parts.)

This article can be awkward because it's written on Google Translator.

**Comment by lightvector** [comment]
The board is almost never symmetrical after the first few turns, so that means in practice only about 1% of the possible board positions could be searched more efficiently. A gain of 1% is a gain, but it is not a very big gain at all, so I have not considered it worth the time to implement it so far.

**Comment by lightvector** [comment]
Also keep in mind that the first few moves are the *least* important to search efficiently. When was the last time you had a game whose winning or losing move was in the first 4 turns, and if only you had been able to read deeper on that move, you would have won instead? :)

No matter how long you think, you're still going to play either the 3-4 or the 4-4 anyways, thinking longer will not produce a move that wins the game, so the only gain here as far as I can tell is just a tiny time savings overall.

**Comment by jaewoo1120** [comment]
Thank you for your answer.
It's just my opinion, so you don't have to take it seriously.

Symmetry only helps with operations.
Wouldn't it be quite helpful on a computer with poor specifications?
The more Katago does the operation, the more reliable the Blue Spot is.
When Catago calculated, there were some figures that we could trust.
I think it will help a poor specification computer get there.

Additionally, if there are two changes that are different in order and have the same result when Catago proceeds, it would be helpful to calculate only one change.

This article can be awkward because it's written on Google Translator.

**Comment by lightvector** [comment]
Symmetry will only be helpful for a computer with poor specifications *on a move where the position is symmetric*. On all other moves, symmetry will be useless. The only symmetric positions in most games occur on moves 1-5. 

When you are reviewing or analyzing a game using a poor computer, how common is it that moves 1-5 are the critical moves for you to analyze? How often do you make a mistake on turn 1 of the game, or have the game outcome be decided by the corner move you play on your first turn or two and want to analyze that mistake?

The only case I can think of where symmetry would legitimately be convenient is for trying to solve small boards like 7x7 or 9x9. But you can also usually just play the first move or two manually and then the position is not symmetric or is less symmetric, so you're back to having no benefit.

> Additionally, if there are two changes that are different in order and have the same result when Catago proceeds, it would be helpful to calculate only one change.

This is an entirely different thing than rotational or positional symmetries, these are called "transpositions". KataGo already handles transpositions a little bit due to neural net caching, (you may notice in positions with lots of transpositions, the visits/s goes higher - that is a consequence of this). But yes, I agree that this is worth doing better. It's being worked on.

**Comment by lightvector** [comment]
Anyways, it seems like enough people have asked for symmetry handling at this point that I'll note it as something to implement for a future release.

Please keep in mind that that the answer to "would it help a lot" is still *no*... unless you frequently care about analyzing symmetric positions. If you frequently like to analyze the empty board position, then it might help for those analyses only. 

But I suppose at least it's aesthetically a nice thing to have, so let's add it. :)
