### ISSUE TITLE
what is Game Type in training games?

### ISSUE THREAD

**Issue by gowayeasy** [lightvector/KataGo#484]
Saw some very interesting types like asym, sgfpos, hintpos, fork, etc. what are they representing?

**Comment by Friday9i** [comment]
I don't know all the details, but in a few words:
- normal: a normal selfplay game (ie played with no handicap, a fair komi as evaluated by the net, equivalent high and low visits)
- sgfpos: game starts from a given sgf position (randomly from a list of various sgf files, ie positions and or games). When sgf file contains a game, it's from a random position of the game, with a probability exponentially decreasing with number of moves played
- hintpos: a list of positions badly played/evaluated by KataGo is provided (mainly by automatically analysing various games: from human players, deep visit games, games from other engines, ...), and these positions are used as starting positions to train KataGo, forcing it to play the moves it likes and those it doesn't like, for it to better understand that some badly evaluated moves can be good
- fork: to forces KataGo to play 2 or more moves, instead of simply its preferred one. So 2 or more games are generated, which help KataGo makes its mind on the best move
- hintfork: a combination of hintpos and fork ; -)
- asym & handi: asym means visits are asymmetric between black and white, generally (but not always I think) to compensate a handicap from either handicap stones and/or unfair komi. Handi means handicap, but I don't know the details of asym vs handi
- cleanup training: don't know the details, but seems clearly related to cleanup phase of the game ; -)

**Comment by gowayeasy** [comment]
This is a very clear answer. Thanks a lot, Friday9!

**Comment by kennychenfs** [comment]
@lightvector 
I think the explanation of these game types should be included in the documentation.

**Comment by lightvector** [comment]
Yeah, I could do that. Where would you recommend?

Note that the game type doesn't affect anything downstream in the training. It's purely a helpful label for display. In fact, the label itself is also somewhat arbitrary too right now since the underlying categories aren't mutually exclusive. For example, a game could be forked, but the fork might be the fork in the opening of a handicap game. A game might have asymmetric playouts, and simultaneously also be a game started from an SGF position. Etc. One could track a set of labels rather than arbitrarily breaking ties to pick a single label, but I didn't bother in the code with the extra clutter and complexity to track label set across games and forks given that the categorization doesn't affect anything beyond visual display.

**Comment by kennychenfs** [comment]
The people who will need to see these files are probably those who want to run KataGo themselves and adjust the parameters themselves, so I thought you could describe them in [SelfplayTraining.md](https://github.com/lightvector/KataGo/blob/master/SelfplayTraining.md). 
In addition, you could put some very simple explanations on the training site, like this.
![未命名](https://github.com/lightvector/KataGo/assets/37182101/29c339bc-f32f-479d-ad30-6f74dceadd30)
