### ISSUE TITLE
suggest to tune once for board x y an boardsize y x

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#49]
now it tunes twice

**Comment by lightvector** [comment]
Not fixing this, because "x y" and "y x" actually make a difference from the perspective of the GPU algorithms - because the board is in row-major order when passed to the neural net to be evaluated.

However, you might be interested in the releases page: https://github.com/lightvector/KataGo/releases/tag/v1.2-beta
> EDIT: Added another change where unless explicitly configured otherwise (in gtp.cfg), KataGo will share OpenCL tuning across all board sizes, since tuning can be a bit slow to do on every board size. Bumped the tag of this release.

I made this change already a day ago, you can re-download if you want to only tune once for ALL board sizes  together.

**Comment by l1t1** [comment]
the new version works, thanks you

**Comment by l1t1** [comment]
it seems katago will lookup the nearest size of tuning file.
eg. i set boardsize 2 9, it will pick up boardsize 7 9 tuning file that i did earlier
```
D:\katago>katago gtp -model model.txt.gz -config gtp_example.cfg
KataGo v1.2
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation) OpenCL 1.2
Loaded tuning parameters from: ./KataGoData/opencltuning/tune_gpuIntelRHDGraphics4400_x19_y19_c96_mv5.txt
Loaded model model.txt.gz
GTP ready, beginning main protocol loop
boardsize 2 9
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation) OpenCL 1.2
Loaded tuning parameters from: ./KataGoData/opencltuning/tune_gpuIntelRHDGraphics4400_x7_y9_c96_mv5.txt
```
