### ISSUE TITLE
Is there a way to train only with a specific game type or board size?

### ISSUE THREAD

**Issue by jaewoo1120** [lightvector/KataGo#494]
1. Can I let Katago play self-training games only with certain types of games?
For example, can you let Katago play games only in sgfpos or fork types or except for normal types?

2. Can I have katago play a self-training game using only a certain board size?
Likewise, is there a way to make katago play games by selecting the board size that he wants to play, such as using only board sizes such as 9x9 or 13x13 or excluding 19x19?

If there is, I think I can train katago more interestingly.
This article can be awkward because it is written with a translator.  :)

**Comment by lightvector** [comment]
You can do anything you like if you are running your own personal KataGo training. To do your personal run where you can try all the experiments you like, see: https://github.com/lightvector/KataGo/blob/master/SelfplayTraining.md. You can start with 6-block nets and work your way up, or you can download existing nets and data from https://d3dndmfyhecmj0.cloudfront.net/ and start from there rather than from scratch. 

If you are referring to public run at https://katagotraining.org/, no, you cannot and should not change it, please do not try. The public run is based on everyone using consistent parameters with everyone else so that we can have stable training.

**Comment by jaewoo1120** [comment]
Thank you for your answer.
I originally meant to upload to https://katagotraining.org, but I won't try.
