### ISSUE TITLE
one player resign and the other pass, the first one will move next step

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#51]
genmove w
= resign

genmove b
= pass

genmove w
= B6

genmove b
= B1

genmove w
= pass

**Comment by l1t1** [comment]
and double passed will move too

genmove w
= pass

genmove b
= pass

genmove w
? genmove returned null location or illegal move

genmove b
= G1

genmove w
= pass

genmove b
= pass

genmove w
? genmove returned null location or illegal move

**Comment by l1t1** [comment]
and i test a 5x5 borad, samilar question, does the next command knows current resign status?
```
boardsize 5
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation)
Loaded tuning parameters from: ./KataGoData/opencltuning/tune_gpuIntelRHDGraphics4400_x19_y19_c96_mv5.txt
=

genmove b
= C3

genmove w
= C2

genmove b
= B2

genmove w
= B3

genmove b
= D2

genmove w
= C4

genmove b
= D3

genmove w
= A2

genmove b
= B1

genmove w
= A4

genmove b
= B5

genmove w
= resign

genmove b
= D4

genmove w
= resign

genmove b
= C5

genmove w
= resign

genmove b
= B4

genmove w
= resign

genmove b
= A3

genmove w
= resign

genmove b
= E2

genmove w
= resign

genmove b
= A1

genmove w
= resign

genmove b
= A5

genmove w
= resign

genmove b
= C1

genmove w
= resign

genmove b
= pass

genmove w
= E5

showboard
= MoveNum: 2 HASH: 43DF920695C399A47003B29B17F7951E
   A B C D E
 5 X X X . O
 4 . X . X .
 3 X . X X .
 2 . X . X X
 1 X X X . .
```

**Comment by lightvector** [comment]
The "? genmove returned null location or illegal move" is definitely a bug. Fixed in https://github.com/lightvector/KataGo/commit/36f916bb3102ad58d1895e93dbd485dc3bf2c93c

The latest release has been updated from v1.2-beta to v1.2 including this change, feel free to try it out.

That's the only weird behavior I see that you have described. Playing moves after the end of the game is not so surprising, because you've *asked it* to play more moves past the end of the game, so of course it might play a move or pass again. Does this make sense, or do you see anything else strange after this fix?

**Comment by lightvector** [comment]
Closing, feel free to comment again if there's anything further to fi here.
