### ISSUE TITLE
Could you support open cuda configs auto by tuning?

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#52]
Just like LeelaZero, merge OpenCL and Cuda engines.
BTW, could tuning auto get best num of numSearchThreads and nnMaxBatchSize?

**Comment by alreadydone** [comment]
I think there is no CUDA engine in Leela Zero's official branch, only in Ttl's fork.

**Comment by ivysrono** [comment]
@alreadydone You  are right. I mean LZ open tensor auto by first tuning.

**Comment by merlinpan** [comment]
cuda doesn't seem to need that.  cuda is nvidia only, and they know the timing of all their cards internally.

**Comment by lightvector** [comment]
Yep, OpenCL has a GPU tuner in KataGo, and CUDA just goes with what NVIDIA has implemented.

For search threads, there is still no automatic tuning of number threads, and I am reluctant to add one, because unlike a pure performance improvement, this value has an actual impact on the rest of the user's system - setting it high could interfere with other things they run, measuring it at a time when other things are running could get a misleading value, etc.

However, with the new [v1.3 release](https://github.com/lightvector/KataGo/releases/tag/v1.3) the "benchmark" command (see notes on the [main readme page](https://github.com/lightvector/KataGo#how-to-use)) has hopefully been greatly improved in userfriendliness, and will test a variety of numbers of threads, and make a recommendation taking into account both speed and the strength cost of threads.

Closing this issue, but feel free to reply back if you think there is something more here to do and I could reopen. Thanks!
