### ISSUE TITLE
Broken link for 15 block network

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#522]
The link of 15 block network seems broken in https://github.com/lightvector/KataGo#other-questions .

~~~
$ curl https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html
curl: (6) Could not resolve host: d3dndmfyhecmj0.cloudfront.net
~~~

**Comment by lightvector** [comment]
Thanks. I took the site down because someone, whether deliberately or by accident, was overloading the bandwidth of the site (repeatedly downloading more than all of the data on that site). I'll consider restoring it at some point when I get some time to put it back up, maybe with some better mechanisms to limit such things.

**Comment by kaorahi** [comment]
Thanks for the reply. It is no problem for me as I already have a copy of the best 15 block network.

**Comment by ed1d1a8d** [comment]
https://katagotraining.org/networks/ seems to host a lot of the files, just with a `kata1` prefix instead of a `g170` prefix.
