### ISSUE TITLE
[question]can we train 60 blocks now?

### ISSUE THREAD

**Issue by 1067511899** [lightvector/KataGo#569]
When using command to train like this :
katago contribute -config contribute.cfg
It will download newest 40 blocks network file,and begin to train.
Is there anyway to train a 60 block network ?like kata1-b60c320-s4757446912-d2508467886  ?

Thanks.

**Comment by lightvector** [comment]
Yes, you are already helping to train a 60 block network. You can download it at https://katagotraining.org/.
The 40 block network you see downloaded is only used to generate data because it is faster to run and the data quality is still high enough for now to be useful. But 60 block network is always training on that data too, and is benefiting at the same time.
