### ISSUE TITLE
zb ownership maps

### ISSUE THREAD

**Issue by bvandenbon** [lightvector/KataGo#57]
Coming soon, to ZBaduk, ownership maps, powered by KataGo !

![afbeelding](https://user-images.githubusercontent.com/20482760/61919515-428b8980-af56-11e9-9352-4726060575c2.png)

**Comment by lightvector** [comment]
Ooooooh.

**Comment by bvandenbon** [comment]
It's available online now. + also added score estimations of KataGo.

![changes3](https://user-images.githubusercontent.com/20482760/64466689-953e9080-d113-11e9-9ee0-011cb45ab846.png)
![changes1](https://user-images.githubusercontent.com/20482760/64466690-95d72700-d113-11e9-8631-fb3c2599ed14.png)

Let me know if there is anything I can do for you. I'm in debt.

**Comment by bvandenbon** [comment]
Coming soon to ZBaduk, are charts that visualize the score throughout the game. This clearly shows how the standard deviation of the score narrows towards the end of the game.
_(powered by KataGo of course)_

![image](https://user-images.githubusercontent.com/20482760/70191059-dd138a80-16f7-11ea-960e-4bb9649ad592.png)

**Comment by lightvector** [comment]
I would advise you take great care using these standard deviation numbers unless you have done some work already to calibrate them and scale them. **The numeric value itself will be systematically biased far too high** if you intend to present it as a measure of the remaining uncertainty of the score for the game (such as might be achieved if KataGo were to self-play to finish the game with reasonable settings). Which is often what a typical user might assume.

Why is this? It's a little subtle, but hopefully I can explain:

What this number is currently defined to be is the square root of the sum of:
* (A) the variance of score over all the nodes in the MCTS tree
* (B) the average variance estimate at individual nodes from the neural net
This is analogous to the way the winrate is the average winrate over the MCTS tree, or the scoreMean is the average score estimate over the MCTS tree, etc. But variance behaves differently than the rest because *all errors increase the value rather than cancelling out*.

In any fight there are many frequent moves that must get a few playouts even though they lead to very bad outcomes - because making sure this or that tactic doesn't work is necessary. This is a big part of what reading/search is for. So across the entire tree, you get a nontrivial number of playouts in variations and subvariations that prove and refute various moves, with those nodes having erroneously high or low values relative to the "true" value of the position.

For winrate and scoreMean, usually both upward and downward errors are comparably likely, so they cancel out a lot, so the final estimate is quite good. For score variance, upward and downward errors *both increase the final result without cancelling* because both increase the variance. But the thing is, the refuted moves that contribute to these errors, despite increasing the variance measurement, *are not moves that ever get played in a real game* - if move X and Y are both tactically critical and so you search them both and find that X works and Y is a disaster, you will play X, and if you find that Y works and X is a disaster, you will play Y. So the refuted branch, although resulting in much higher variance in the "average across MCTS" sense, is not actually a thing that increases the variance of the of a real self-play game, because in no real self-play game will the disaster actually happen - or at least, disaster will be vastly rarer than the proportion of playouts it gets in the search. This makes (A) systematically too large.

A related secondary detail is that the neural net itself is usually a fair bit underconfident about the game result compared to what MCTS achieves, because MCTS has the benefit of being able to average over many many neural net evals and gain much more statistical power. You may have noticed that a bot that says 90%, against an otherwise even-strength opponent, usually is going to win *more* than 9 times out of 10 - this is a similar phenomenon. For score variance, the upward bias due to neural net uncertainty here is possibly more significant than for winrate since when the neural net does misevaluate, it knows often it means a whole group is dead that was thought to be alive, which is a big swing, whereas for winrate if you lose a few points and therefore the game, that's it, you don't "extra lose the game" if you lose by even more points after that. So (B) tends to be a bit high too.

If you've ever paid attention to what the score standard deviation number actually is you might have noticed that seemingly incongruous reports are common, things like winrate: 84% scoreMean: +10, scoreStdev 20.  If you stop and think about it... while not statistically impossible, that's a little weird - being 10 points ahead, thinking that the level of uncertainty is 20 points (with the commonly used two-stddev-error bar being **40** points), and yet thinking you're 84% to win.

To the best of my understanding, the above effects are why - the score stdev isn't quite what a typical user might think it is.

**Comment by lightvector** [comment]
It might be interesting at some point to run some test matches with some reasonable settings and to see empirically by what factor the "scoreStdev" value needs to be scaled down to get something resembling the actual the standard deviation of final score. It would of course depend on the match settings too.

**Comment by bvandenbon** [comment]
Thank you for these insights.
I am indeed starting to doubt if it is a good idea to release this feature to the public.
If anything, it needs some mentioning in the help-files.

_PS: the lines on the score chart above are actually : meanscore , meanscore+stddev/2 , meanscore-stddev/2. So, in a sense there is already a factor (i.e. 0.5) applied here. (by mistake)_

**Comment by lightvector** [comment]
It's mentioned here where kata-analyze is documented:
https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md

Is there I way that I should make this more prominent?

**Comment by bvandenbon** [comment]
> If anything, it needs some mentioning in the help-files.

I was refering to the ZBaduk help files.

**Comment by lightvector** [comment]
Ah. :)

**Comment by lightvector** [comment]
Personally, I think it's okay to use the value if it's communicated that the value is a relative measure of uncertainty but that it does not necessarily correspond to any specific prediction of the probability of getting a certain score range. That is - changes in the value do usually correspond to real changes in the uncertainty level of the final score - but the absolute numeric value is not necessarily indicative of anything in particular.

Alternatively, one could experiment a little in order to find an appropriate scaling factor that does actually make it correspond to the probability of landing in a particular score interval.

**Comment by lightvector** [comment]
Revisiting and cleaning up old stale issues, since things seem handled here.  Happy go. :)
