### ISSUE TITLE
LoadModelFile unimplemented

### ISSUE THREAD

**Issue by Dreamkeeper66666** [lightvector/KataGo#59]
Hello, I just compiled Kata and run the gtp command as follow:
<img width="797" alt="Screen Shot 2019-07-28 at 11 20 39 PM" src="https://user-images.githubusercontent.com/35905034/62009138-5f120680-b18e-11e9-952f-295b0d328d9f.png">
It seems that there is something wrong with the modelfile or the compiled Kata. Anyone knows how to solve the problem? Thanks a lot!

**Comment by lightvector** [comment]
You need to say what backend you want. You should have encountered the following warning when compiling:

`WARNING: Using dummy neural net backend, intended for non-neural-net testing only, will fail on any code path requiring a neural net. To use neural net, specify -DUSE_BACKEND=CUDA or -DUSE_BACKEND=OPENCL to compile with the respective backend.`

Or if you're on an older version (rather than tip of master), then it would be `-DUSE_BACKEND_CUDA=1` or `-DUSE_BACKEND_OPENCL=1`.

**Comment by lightvector** [comment]
(this warning and when you should specify these options would be when you're running CMake)

**Comment by Dreamkeeper66666** [comment]
> You need to say what backend you want. You should have encountered the following warning when compiling:
> 
> `WARNING: Using dummy neural net backend, intended for non-neural-net testing only, will fail on any code path requiring a neural net. To use neural net, specify -DUSE_BACKEND=CUDA or -DUSE_BACKEND=OPENCL to compile with the respective backend.`
> 
> Or if you're on an older version (rather than tip of master), then it would be `-DUSE_BACKEND_CUDA=1` or `-DUSE_BACKEND_OPENCL=1`.

Thanks for your answer! However, I just got stuck here for a long time
<img width="750" alt="Screen Shot 2019-07-29 at 9 35 28 AM" src="https://user-images.githubusercontent.com/35905034/62016345-3ae11480-b1e4-11e9-85b6-0387d2c09a5c.png">
Do you have any ideas about what's happening here? Thanks a lot

**Comment by lightvector** [comment]
Well, it's waiting for you to provide input according to GTP protocol.

https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

**Comment by Dreamkeeper66666** [comment]
> Well, it's waiting for you to provide input according to GTP protocol.
> 
> https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html

Okay, got it! Thank you!

**Comment by lightvector** [comment]
See also GnuGo documentation here for an example of GTP:
https://www.gnu.org/software/gnugo/gnugo_19.html

Basically, it's not going to do anything until you start telling it to do things. Or more likely, launch it to begin with from a GUI program (Sabaki, Lizzie, GoGui, etc) that knows how to speak GTP in order to tell it to do whatever the GUI program wants to do.

Glad to help. Please close this issue once it's working and you don't have any further questions.

**Comment by Dreamkeeper66666** [comment]
Thanks for your help! I am still trying to figure out how to run with Lizzie v0.6. Since I just downloaded the release directly, maybe they are not compatible. So do I have to compile the latest version of the source code? Or do I just need to change the config.txt? Thanks!

**Comment by lightvector** [comment]
For Lizzie you probably want to compile directly from the tip of the repo. The latest release is quite outdated at this point and only officially supports LZ, the unreleased tip supports multiple bots including KataGo.

**Comment by lightvector** [comment]
Closing this issue since everything seems to be handled. Reply back if there's anything else.
