### ISSUE TITLE
[Question] Efficiently run selfplay with analysis engine?

### ISSUE THREAD

**Issue by mikekyle** [lightvector/KataGo#595]
I would like to set up a number of opening positions and for each, ask Katago (with a certain config) to play out until the end of the game and return the sequence of moves.

I can do this in GTP by inputting the opening position move by move and then generating each following move. (My reasons for not doing this are - tools such as twogtp are not available in python 3 and so don't play nicely with other scripts I have, because I'm not sure it's a very efficient method & because I have become used to the convenience of the analysis engine)

I can also do this in the analysis engine by querying the initial position, waiting for a response and then adding this reposonse move to the next query and so on. However this use of the analysis engine seems suboptimal. I'm not sure if Katago will re-use it's reading from previous positions in this case?
Am I missing a nicer neater way to use the analysis engine for this purpose? Surely someone has done this before?

**Comment by lightvector** [comment]
You are right, KataGo will not re-use the reading from previous positions. However, the neural net cache will still have all the positions that were evaluated, and generally the neural net query is the limiting factor for the speed of search. So repeating the search on the very next move will likely be much, much faster than normal because even though the game tree has to be re-built, the neural net queries required will mostly have already been calculated, except for (of course) the new deeper queries required from the fact that you are one move deeper now.

**Comment by mikekyle** [comment]
Thanks very much. Am I correct in assuming that this applies either in gtp or in the analysis engine? So the two methods described will be roughly equivalent?

**Comment by lightvector** [comment]
No, GTP will actually keep the tree around for the next move. So GTP may be slightly more efficient if you are doing strictly sequential analysis of moves where you run each search one by one, so long as you do not perform any undos or send any commands that modify game properties in between.

On the other hand, GTP may easily be *less* efficient because the analysis engine can parallelize search across all different positions. So you can analyze a whole game at once rather than one position at a time, getting more efficient GPU batching. 

Additionally because you parallelize across positions (numAnalysisThreads), you can use fewer threads per individual position (numSearchThreadsPerAnalysisThread). This increases the strength of search, because in general, whenever the number of threads searching a single position at a time increases, holding final visits fixed.

**Comment by lightvector** [comment]
In your case, since you're having KataGo play out each game then you won't get the benefit of parallelizing analysis across the entire game, so for a single game I'd expect GTP to be faster. But if you are planning to run multiple such games, then the analysis engine could run multiple games at the same time in parallel, and again you could increase numAnalysisThreads and decrease numSearchThreadsPerAnalysisThread and likely get better play and better parallelization. Since again parallelization across games should be more efficient than parallelization within a single game because in the former everything is entirely independent whereas in the latter it isn't.

You'd have to do some experimentation yourself to know for sure given your hardware and settings.
