### ISSUE TITLE
Document the visualition

### ISSUE THREAD

**Issue by tychota** [lightvector/KataGo#6]
Hi ! Thanks for this repo.

How did you the nice visualisations of model outputs on a go board, like this one https://github.com/lightvector/KataGo/blob/master/images/readme/ladderinput3.png

Is it something easy to do with the tools included ?

**Comment by lightvector** [comment]
It should not be hard. Take a look at the `python/play.py`. This is a GTP engine in python that does NOT include any implementation of MCTS. It only uses the raw neural net policy to make moves. It's actually also lacking a full implementation of even the rules of Go - for example it completely ignores the komi sent by GTP and assumes that it is 7.5. It also hardcodes various other rules and such in a much more restrictive way than the C++ GTP engine does. So obviously there is some serious work to be done to make this python script better, so I'm hesitant to want to advertise it. :)

But anyways, it supports a bunch of GoGUI extensions (https://sourceforge.net/projects/gogui/) (https://github.com/Remi-Coulom/gogui) that GoGUI uses to displayed colored output. The visualizations are screenshots of the results from within GoGUI.

It looks like it should not be too hard to make the C++ GTP engine support lz-analyze, which should make it usable in some of the tools that have developed around LZ, like lizzie. I'll be investigating that either this or next weekend. Although that won't result in support for ownership and score visualization since these are not in LZ, it should also be a nice thing to add.

**Comment by tychota** [comment]
> Take a look at the python/play.py.  it supports a bunch of GoGUI extensions

Perfect, I will look at your link and open another issue if further question.
I close for now.

> It looks like it should not be too hard to make the C++ GTP engine support lz-analyze, which should make it usable in some of the tools that have developed around LZ, like lizzie.

Looks really nice.
