### ISSUE TITLE
"kata-analyze W ... allow ..." seems wrong in black's turn

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#602]
I expect to get only "E5" in the following commands. I got "C4" etc. actually in the first "kata-analyze". The second "kata-analyze" seems correct.

~~~
$ (echo "1 kata-analyze W interval 20 allow W E5 1"; sleep 1; \
   echo "2 kata-analyze W interval 20 allow W E5 1"; sleep 1) \
  | ./katago-cpu gtp -model net/kata_128x10.bin.gz -config gtp_my.cfg \
  | grep -o '^(info move ..|=.*)'
KataGo v1.10.0
Using TrompTaylor rules initially, unless GTP/GUI overrides this
Initializing board with boardXSize 19 boardYSize 19
Loaded config gtp_my.cfg
Loaded model net/kata_128x10.bin.gz
Model name: g170-b10c128-s1141046784-d204142634
GTP ready, beginning main protocol loop
=1
info move C4
info move C4
info move D4
info move D4
=2
info move E5
info move E5
info move E5
info move E5
info move E5
~~~

(version)

~~~
$ git log --oneline -n 1
20d34784 (HEAD -> master, upstream/master) Add benchmark command for gtp
~~~

Leela Zero works as expected.

~~~
$ (echo "1 lz-analyze W interval 20 allow W E5 1"; sleep 1; \
   echo "2 lz-analyze W interval 20 allow W E5 1"; sleep 1) \
  | ./leelaz -g -w network.gz 2> /dev/null \
  | grep -o '^(info move ..|=.*)'
=1
info move E5
info move E5
=2
info move E5
info move E5
info move E5
~~~

I noticed this when I tried "3n opening method for handicap games".
https://www.reddit.com/r/baduk/comments/sublre/i_have_created_an_opening_method_to_make_handicap/

**Comment by lightvector** [comment]
Thanks for the report. Pushed a fix in master branch to include in next release. The bug was due to analysis being requested for a player that is different than the player that is normally supposed to make the next move (normally black makes the first move), violating the normal game state. Which causes the game state and history to be recreated which results in clearing the setting of moves to allow that was set just instantaneously before.

**Comment by kaorahi** [comment]
Thanks for the fix! It works well now.
