### ISSUE TITLE
Can KataGo run in WSL2(windows subsystem for linux version2)?

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#611]
I just try to run katago in wsl2, win11, it get:
```
$ ./katago
./katago: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory
```

**Comment by lightvector** [comment]
It sounds like your Linux running within Windows doesn't have OpenCL installed, so presumably you need to install it? That might mean installing the Linux version of CUDA if you have an NVIDIA GPU, or it might mean the linux version of AMD's drivers or whatever if you have one of their GPUs, etc.

Either that, or sticking with the Windows version of KataGo, since as far as I understand, the Linux within WSL can still launch Windows programs to run under Windows.

I definitely don't know about the details of installing these things within Linux within Windows since that has nothing to do with KataGo, but surely you can search online for help if you run into difficulties?

**Comment by HackYardo** [comment]
Thanks a lot for your tips. My pc could run KG in wsl2, win11 now!
For someone else want to try it, he/she needs to install OpenCL, zlib, libzip, unzip and maybe others before run KG, here are all commands:
```bash
`win`, `wt`, `enter` # run wt

wsl ~ # run wsl in /home/username

# download and install unzip:
sudo apt install unzip

# download and install OpenCL for WSL2:
wget OpenCL_for_WSL2.deb 
# the above line is a pseudocode, see https://github.com/intel/compute-runtime/releases/tag/22.09.22577 for the truecode
sudo dpkg -i *.deb

# download and install zlib:
wget https://www.zlib.net/zlib-1.2.11.tar.gz
tar zxvf zlib-1. # try to click `tab` key
cd zlib-1.2.11
mkdir build
cd build
cmake ..
make
make test
sudo make install

# download and install libzip:
sudo apt-get install -y libzip-dev

# download and unzip KataGo execute file for Linux OpenCL:
wget https://github.com/lightvector/KataGo/releases/download/v1.10.0/katago-v1.10.0-opencl-linux-x64.zip
unzip katago-v1. # `tab`
cd katago- `tab`

# download the KataGo best model for weak pc:
wget https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b20c256x2-s5303129600-d1228401921.bin.gz

# make KataGo can be executed:
nautilus
# find `katago` and choose `Allow executing file as program`

# run:
./katago gtp -model kata1 `tab`

# wait until `GTP ready`:
showboard # you should see an empty Go board
play B K10
genmove W
final_score
quit # end katago

`ctrl d` # end wsl

exit or `alt f4`# end wt
```
