### ISSUE TITLE
Could I check SHA-256 or something other of KataGo?

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#614]
I download KataGo OpenCL Linux and then unzip it to a directory, but I find the `.zip` is only **30M**  and the `katago` in the directory is **128M**.
 > **128>>30**

Is this `katago` the same one in this repo? Why so big? The rate of unzip is bigger then `4`? What a big rate!?

**Comment by OmnipotentEntity** [comment]
$ file katago
katago: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=9ce7c1d739838676f46d27c2cbc08a510ece7e46, with debug_info, not stripped

It's compiled using the cmake profile `RelWithDebInfo`, so it's got debugging information in it, which is why it's so large.  It also doesn't have its symbols stripped, which can also make an executable much larger than normal.

**Comment by HackYardo** [comment]
I'm new to Linux(wsl2), and I learn a lot from your post.
I try `sha256sum`, it looks like the same as yours:
> 484bffe70359dd36f6a8e0aca7d14d6f81f5b721949c338215861bcbef127040
484bffe70359dd36f6a8e0aca7d14d6f81f5b721949c338215861bcbef127040  

I also try `strip` on a new git branch, it's fine too:
> 241d5d5103d6003e1f7fddde61903d3573d04ad72e2b17050ce3dd385d32e499
241d5d5103d6003e1f7fddde61903d3573d04ad72e2b17050ce3dd385d32e499  

Thanks a ton!

**Comment by HackYardo** [comment]
OMG, `git status` tells **nothing** about `strip katago`, fortunately I have a copy of my git local repo...
