### ISSUE TITLE
I really don't know what they are doing.

### ISSUE THREAD

**Issue by 1067511899** [lightvector/KataGo#618]
![image](https://user-images.githubusercontent.com/21253207/159161758-f1b36810-7514-4e01-8f60-e6335b38f2e4.png)
[3_6D82B129E625F947_b60c320-s5785632768_VS_b60c320-s5785632768().zip](https://github.com/lightvector/KataGo/files/8311205/3_6D82B129E625F947_b60c320-s5785632768_VS_b60c320-s5785632768.zip)

the 248,white passed,but the black continues to go,until 312,all those are meaningless.
![image](https://user-images.githubusercontent.com/21253207/159161874-eab713f2-f51b-48f8-884a-0d0e4f13042b.png)

I found several contribute games,they did meaningless movies.
so ,it's some bugs,or just a kind of function?

Thank you.

**Comment by lightvector** [comment]
These are not meaningless moves. KataGo trains under computer-friendly rules that require both players to prove that stones are dead by playing the moves to capture them. This guarantees that the game can be scored 100% mechanically and that game results are always grounded in the results of real play.

(Stones may be left uncaptured only when they are pass-dead, i.e. even if the opponent gets infinitely many moves the stone still cannot live and cannot kill anything around it. This is the case for move 164).

**Comment by lightvector** [comment]
See https://lightvector.github.io/KataGo/rules.html

**Comment by lightvector** [comment]
Also, your game appears to be this game: https://katagotraining.org/sgfplayer/training-games/30014854/

You can see the exact rules at the bottom of the page. This game actually used area scoring (i.e. Chinese scoring) instead of Japanese scoring like in your SGF. You can see it also has hasButton:True, so the reason for the first pass on move 248 was to claim the button to gain a extra 0.5 points. https://senseis.xmp.net/?ButtonGo

**Comment by 1067511899** [comment]
Thank you,I understand now.
