### ISSUE TITLE
Why analysis subcommand doesn't tune when boardsize changes? 

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#619]
GTP subcommand will tune when boardsize changes, and it takes a little time, two issues about it, #49 #171 
I just try analysis subcommand, it seems that it doesn't tune when boardsize chenges, and the GUIs based on it switch boardsizes quickly, i.e. KaTrain, Ogatak.
I wonder if GTP could do as the analysis does?

**Comment by lightvector** [comment]
Maybe. But the cost of making it quick at the start is that there is a mild performance cost for the entire rest of the process. On every individual convolutional layer, the neural net needs to apply an additional masking operation to emulate the correct board size, whereas if initialized with the board size known ahead of time, this step can be skipped.

For GTP doing the startup initialization makes sense because the GTP protocol is designed to have you declare a board size in advance and then play an entire game from there, searching only one position at a time. For the analysis engine, it doesn't make sense because the analysis engine is designed to accept many different positions all at the same time and search them simultaneously, and those positions could be all different board sizes.

**Comment by HackYardo** [comment]
Thank you very much. I see. There are two ways, one can't catch two deer at the same time. So I close the issue.  So I close it.
