### ISSUE TITLE
Is it considered to show the calculation times of neural network

### ISSUE THREAD

**Issue by anotheros** [lightvector/KataGo#621]
What is it like now 。
`info move E4 visits 1178 winrate 4802 prior 2211 lcb 4781 order 0 pv E4 E3 F3 D3 F4 P4 P3 O3 Q3 O4 K3 Q6 S6 E16 E17 info move P16 visits 1056 winrate 4796 prior 2206 lcb 4769 order 1 pv P16 P17 O17 Q17 O16 E16 E17 F17 D17 F16 K17 D14 B14 P3 info move E3 visits 264 winrate 4752 prior 944 lcb 4722 order 2 pv E3 D5 P16 P17 O17 Q17 O16 E17 H17 D15 C15 D14 info move E16 visits 262 winrate 4741 prior 1047 lcb 4709 order 3 pv E16 P4 P3 O3 Q3 O4 P16 P17 O17 Q17 O16 Q14`

After improvement

`info move E4 visits 1178 nnEvals 500 winrate 4802 prior 2211 lcb 4781 order 0 pv E4 E3 F3 D3 F4 P4 P3 O3 Q3 O4 K3 Q6 S6 E16 E17 info move P16 visits 1056 nnEvals 500  winrate 4796 prior 2206 lcb 4769 order 1 pv P16 P17 O17 Q17 O16 E16 E17 F17 D17 F16 K17 D14 B14 P3 info move E3 visits 264  nnEvals 200  winrate 4752 prior 944 lcb 4722 order 2 pv E3 D5 P16 P17 O17 Q17 O16 E17 H17 D15 C15 D14 info move E16 visits  262  nnEvals 200 winrate 4741 prior 1047 lcb 4709 order 3 pv E16 P4 P3 O3 Q3 O4 P16 P17 O17 Q17 O16 Q14`

**Comment by lightvector** [comment]
The number of neural net evaluations is only tracked at the global level, rather than within the search tree, so this output is not possible right now.

I also don't think it even makes sense to output. Different parts of the search tree may use the same cached neural net evaluations due to different orderings of moves leading to the same positions. (This was true even before graph search). So multiple moves may share the same neural net evaluations, so counting neural net evaluations individually per move doesn't make sense.

**Comment by anotheros** [comment]
thank you
