### ISSUE TITLE
Can I set rectangle boardsize before GTP main loop?

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#633]
#171 There is a method to set square boardsize: `./katago gtp -override-config defaultBoardSize=n`, can add a method like `./katago gtp -override-config defaultBoardSize=m,n`?

**Comment by Chenvincentkevin** [comment]
this website may help https://test.katagodistributed.org/

**Comment by Chenvincentkevin** [comment]
and adjust the board size to rectangular within the GUI

**Comment by lightvector** [comment]
@Chenvincentkevin - I think this doesn't answer HackYardo's question because they are aware already that KataGo can handle rectangular boardsizes. The test site you linked is also only a test run for very small boards - you can try its nets for very small rectangles like 3x7 and such, but for larger rectangles (e.g. 9x13) just use normal KataGo and don't use any nets from the test site. However, thanks for pinging this thread, I had missed this thread before!

@HackYardo - defaultBoardXSize, defaultBoardYSize

**Comment by lightvector** [comment]
Also, one strategy to find parameters like this is to search the source code. For example, if you search for "defaultBoardSize" in this repo using Github above, you immediately get a link to the exact part of the source code that handles reading the board size parameters, and exactly right there is defaultBoardXSize and defaultBoardYSize as well.

**Comment by HackYardo** [comment]
Thank you two so much! New trick learned!
