### ISSUE TITLE
Some queries on training by selfplay

### ISSUE THREAD

**Issue by Guyuena** [lightvector/KataGo#639]
I use the batch-size=256
the pacc1 always less 0.05 during training

model.py
self.top1_prediction = tf.equal(tf.argmax(model.policy_output[:, :, 0], 1), policy_target_idxs)
self.accuracy1_unreduced = tf.cast(self.top1_prediction, tf.float32)

train.py
"pacc1": tf.compat.v1.metrics.mean(metrics.accuracy1_unreduced, weights=target_vars.target_weight_used),

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/73576917/166847180-b66718f9-10a6-4b77-b52d-81f5fe1e3294.png">

**Comment by lightvector** [comment]
You already asked this question at https://github.com/lightvector/KataGo/issues/634, and haven't answered what data you're training on or what you're trying to do. For example, if you're training a brand-new net soon after random play, you simply won't ever get high pacc1, because barely-better-than-random play can't be predicted.

**Comment by lightvector** [comment]
Closing this as a duplicate. Please don't open multiple issues for the same question.
