### ISSUE TITLE
Does the Linux version of katago work on Android?

### ISSUE THREAD

**Issue by Hong-yu1999** [lightvector/KataGo#660]
I want to run katago engine on android, not sure if it is possible

**Comment by HackYardo** [comment]
- Operating systems, such as Android, Win11, MacOS doesn't make sense. Hardware Framework, such as AMD64 on PCs, ARM64 on phones, does matter.

- It is **already implemented** in aki65's [apk](https://aki65.github.io/). And the protocol is GTP, not [KataGo's parallel analyze engine](https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md), the reason here is [Android phones doesn't have enough GPU cores like PCs](https://github.com/aki65/aki65.github.io/issues/18#issuecomment-774546607).

- However, unfortunately, it is **not open to the public**. But I guess if someone [registers](https://github.com/lightvector/KataGo/issues/631) KataGo at Linux communities, people there will help to compile it into ARM devices like Android phones. 

- So, for Android phones, I recommend you to use Leela-Zero, Leela, Pachi, GNU Go instead of KataGo.

**Comment by HackYardo** [comment]
Hey, @Hong-yu1999 , just **follow KataGo's docs to compile Eigen KataGo in Ubuntu in Termux on Android**, it works fine!!!  

- There is no official release of KG for Android, KaTrain and others have been discussing it for many years and etc, I thought how hard it was to compile it...
- However, I really couldn't stand the fact that LeelaZero only allows a 19-way board that is too big to play Go games with my phone...
-  So, today, I tried to compile KataGo, and it worked once, and the VastGo, a Go GUI I code, can run KataGo on my phone, I'm **so happy** now!

**Comment by Hong-yu1999** [comment]
> Hey, @Hong-yu1999 , just **follow KataGo's docs to compile Eigen KataGo in Ubuntu in Termux on Android**, it works fine!!!
> 
> * There is no official release of KG for Android, KaTrain and others have been discussing it for many years and etc, I thought how hard it was to compile it...
> * However, I really couldn't stand the fact that LeelaZero only allows a 19-way board that is too big to play Go games with my phone...
> * So, today, I tried to compile KataGo, and it worked once, and the VastGo, a Go GUI I code, can run KataGo on my phone, I'm **so happy** now!

I heard that using termux to compile katago can make katago run in the Android environment. When I compile according to the Linux compilation steps, it reports such an error. I want to know what caused it?@HackYardo
![@}L99G)W0ACB _R8`RZNMMI](https://user-images.githubusercontent.com/57550948/196702129-490887da-034a-40f0-8abf-0f3f5d62c46e.png)

**Comment by HackYardo** [comment]
Perhaps you need a more detailed guide of running KataGo on Android, here it is:

step | why | cmds
--- | --- | ---
install [Termux](https://github.com/termux/termux-app/) | Android has no official terminal to compile something | 0
install [ubuntu in termux](https://github.com/MFDGaming/ubuntu-in-termux) | Termux is not a complete (Linux) operating system | 9
compile [KataGo engine](https://github.com/lightvector/KataGo/blob/master/Compiling.md#linux) | KataGo has no official Android(ARM Ubuntu) release | 9
download [KataGo models](https://katagotraining.org/networks) | modern Go AIs work with neural networks (models/weights) | 1

To see if everything works fine:
```
~ $ cd ubuntu-in-termux/
~/ubuntu-in-termux $ ./startubuntu.sh
root@localhost:~# path/to/KataGoCompiled/katago -h

Usage: ./katago SUBCOMMAND

---Common subcommands------------------

gtp : Runs GTP engine that can be plugged into any standard Go GUI for play/analysis.

...
```

Glossary:
- Ubuntu and Android are instances of Linux.
- Linux, Wimdows, Mac are three OS types.
- ARM and AMD(x86-64) are hardware frameworks. 
- Phones are ARM and Computers are AMD usually.
- `ctrl d` to exit Ubuntu or Termux, `quit` to exit GTP.
- GoTextProtocol is a standard for Go software communicating.

**Comment by Hong-yu1999** [comment]
I can't imagine your enthusiasm. Thanks for your help, I finally succeeded!
![1666357932486](https://user-images.githubusercontent.com/57550948/197204352-a7f14488-a8e1-478a-ae41-bc0140c7ded3.jpg)

In addition, if I want to use katago in my program, do I just need to prepare cfg files, model files, and katago?@HackYardo

**Comment by HackYardo** [comment]
It depends on what you will do with KataGo, application, database, server, or something else?
- If it's an application, you may need to learn some GUI frameworks like GTK, QML, Kivy, etc., in addition to the programming language. If you have several years of programming experience, know some JavaScript, Python, Java, C++, have done some medium to large projects (more than 5000 lines of code), I suggest contributing to an existing good project, such as Sabaki, KaTrain, LizzieYzy, q5Go, Ogatak and LizGoban, which perhaps make more sense for the Go community than starting another one.
- If you are an amateur like me and just want to get your project up and running as soon as possible, there are some shortcuts you can take, for example Plotly Dash, which supports JavaScript, Python, R, Julia and other languages, and it is cross-platform since it runs in browsers (since smartphones have browsers just like desktop computers). But after several years it still doesn't support multi-touch, after all, it's not the "right way" like GTK, it's just a "shortcut".

**Comment by HackYardo** [comment]
On the right way, you need cfg, bin.gz, exe, 3 files.
On the shortcut(Desktop), 3 files. 
On the shortcut(Mobile), you also need Termux and UbuntuInTermux, 5 files.

**Comment by Hong-yu1999** [comment]
I am a CS major student. I tried to write a program in Android studio to use katago, but failed all the time. I think it may be because I know too little about Android to really use it.(T_T)

**Comment by HackYardo** [comment]
- **Android native apps** are beyond my knowledge.
-  But if you use Termux and UbuntuInTermux to run KataGo on phones, you'd better use a **web framework**. Because it is not Android, it is Ubuntu actually. 
- You can also try **Kivy**, it supports Android native apps rather than web apps.
- For Android native apps' developing, you can try to talk with Sanderland(author of KaTrain [Kivy]) and Aki65(author of BadukAI [Android Studio]) on Discord or Github.

**Comment by HackYardo** [comment]
@Hong-yu1999  I'm sorry, perhaps BadukAI is Kivy too, since it is based on LazyBaduk, which uses Kivy: https://github.com/inclement/LazyBaduk#technical-details

**Comment by Hong-yu1999** [comment]
Well, thank you for your kind answer.
(*ゝω・)ﾉThanks!
