### ISSUE TITLE
Can katago run on Ubuntu16.04?

### ISSUE THREAD

**Issue by NingmengLLL** [lightvector/KataGo#661]
when I run katago on Ubuntu 16.04,  errors occur:
**version `GLIBC_2.27' not found,
version `GLIBCXX_3.4.22' not found**

but it seems that Ubuntu16.04 doesn't support GLIBC 2.27

**Comment by lightvector** [comment]
Are you trying the precompiled exes? If so, then given you're on linux, maybe try to compile it yourself so that it uses library versions you personally have installed on your system? On linux this hopefully isn't too hard:

`git clone https://github.com/lightvector/KataGo.git` 
then `cd KataGo` 
then do one of `cmake . -DUSE_BACKEND=OPENCL or cmake . -DUSE_BACKEND=CUDA or cmake . -DUSE_BACKEND=TENSORRT or cmake . -DUSE_BACKEND=EIGEN`, 
then `make`. 
If you're missing a dependency like libzip or whatever, google for the error, `sudo apt install` whatever the dependency is, and try again.

**Comment by lightvector** [comment]
(There's a chance you get some error or missing dependency that does actually make it harder, if so feel free to post what that is)
