### ISSUE TITLE
How to reproduce the KataGo paper's `Figure 4: 1600-visit Elo progression of KataGo vs. Leela Zero`

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#667]
Hi, I want to plot the Figure 4 (X-axis only) in https://arxiv.org/pdf/1902.10565, but it get wrong numbers many times, so I come here look for help.
From the paper, I guess that the formula should be:
engine | formula
--- | ---
KG | dataRow\*b\*c\*c/20/256/256
LZ | trainingGame\*b\*c\*c/20/256/256\*1600\*0.8\*361

The results are not good:
kata1-b6c96-s1248000-d550347:
value | source
--- | ---
550347 | https://katagotraining.org/networks/
~ 0.12e9 | the Figure 4
~ 2.32e5 | 550347\*6\*96\*96/20/256/256

LZ30:
value | source
--- | ---
1242298 | https://zero.sjeng.org/
~ 10e9 | the Figure 4
~ 8.97e9 | 1242298\*5\*64\*64/20/256/256\*1600\*0.8\*361

**Comment by lightvector** [comment]
**Leela Zero**

Making that graph was very messy. You need to download the Leela Zero data and estimate the number of data rows in the actual data, which is not a constant number since the number of data rows per game varies, especially because Leela Zero also had a mix of games with and without resignation.

Also the number of playouts Leela Zero used at different points in its run was different, it was changed several times. You can either dig through old Leela Zero Github discussions to look for the moments when changes were made, or you can download the data files and infer it through the numerical values of the policy target (you can sometimes do this by looking at what fractional values the policies are multiples of). If I recall, Leela Zero also used a visits limit for a lot of its run. For a playouts limit like ELF you can only do the approximation using the transposition caching of 20%, but for a visits limit you need to take into account average tree reuse, which you can do by looking at the sharpness of the policy target (i.e. the visit distribution).

Because some data was missing for Leela Zero, and because accounting for tree reuse is only a statistical estimate, I did my best but as noted in the paper, Leela Zero's numbers are only an approximation. I would not be overly surprised if they are still wrong by 30% or something like that, although I would hope the error is much less than that. Hopefully I didn't make a much larger estimation error, I did my best, but it was complicated. :)

---
**KataGo**

Your calculation for from KataGo is forgetting to count how many visits were used in the search, which is why you are getting a number that is way too small. Each data row was generated via MCTS with 600, or 1000 visits, which you forgot to multiply by. However, these are visits, not playouts, so there is tree reuse. And *also* due to playout cap randomization, there a nontrivial number of neural net evaluations were spent even though though they don't produce any data rows.

This is a bit messy to estimate, so instead of estimate it, I just took the *exact* numbers from log files, where i just recorded the exact number of queries to the neural net. Here is an old excel file that records this values that I extracted from the original logs, if you want it.
[g104cost.xls](https://github.com/lightvector/KataGo/files/9224788/g104cost.xls)

Note that this is for g104 run, this is the run in the paper. The g170/kata1 is even more efficient than the run the the paper, however I don't have corresponding logged data for the exact number of rows. However, you could estimate it - for each network size, b6c96, b10c128, etc, you could look at the average cost per data row for g170 for that network size, and then just approximate g170 as having the same cost per data row. I believe you should find that g170 is another between 1.5x and 2x more efficient than g104.

**Comment by HackYardo** [comment]
Well, it looks a bit tricky to reproduce the Figure 4. **What if backstep?** Can I use the conclusion of the paper and the data at *https://katagotraining.org/networks/* and *https://zero.sjeng.org/* to plot a figure?

**Comment by lightvector** [comment]
I'm not sure what you mean by "What if backstep?". I sent you a file with the data for the cost for g104, you can plot that data as you like. As for the "kata1" run, the name of the network contains the cumulative number of data rows in the run "d". Different data rows were generated by different sizes of network depending on how early it is in the run, so you need to do several calculations, but if you assume each data row for each different size of network had the same cost it did in g104 (which I think is a pretty good assumption) you can calculate how efficient that run was. You should NOT assume that it is 1.5x to 2x, that is only my guess and could be wrong, if you want to plot something you should actually do the calculation yourself and see.

**Comment by HackYardo** [comment]
![newplot](https://user-images.githubusercontent.com/57677458/182301133-d24fc5d8-321b-4952-a1ab-fe4d98b731c7.png)

(random is at (9000, 0))
This plot is absolutely a wrong one. It just use the origin data and do none calculation. And the Y axis doesn't make any sense. I will try to do some calculation, and if something worthy get and can be shared, I will back.
