### ISSUE TITLE
How may I display a specific range for win rate

### ISSUE THREAD

**Issue by s482** [lightvector/KataGo#676]
I would like to view more playing options in KataGo analysis. How can I display playing options with a specific change in win rate range for example from -3 to -10 changes?

**Comment by lightvector** [comment]
There isn't an option to do an exact range. However, you can try adjusting the wide root noise parameter to explore more or less as you wish. Depending on what command or GUI you are using, see the following. Does that help?

https://github.com/lightvector/KataGo/blob/master/cpp/configs/analysis_example.cfg#L33
https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg#L81

**Comment by HackYardo** [comment]
From my experience, the engine is responsible for providing the data and the interface is responsible for filtering and presenting the data, so this is a GUI issue and not an engine issue, maybe you should ask Sabaki, KaTrain, q5Go, Lizzie, LizGoban, LizzieYzy, Ogatak, BadukAI... Actually, I'm also working on a GUI named VastGo that emphasizes fun and data, but since I'm not a programmer, it would take many years before I can implement this feature...
