### ISSUE TITLE
Implemeting for other board games?

### ISSUE THREAD

**Issue by 51616** [lightvector/KataGo#7]
I am trying to implment AlphaGo algorithm on my own board game. Is this repo capable of changing the game if I already have the game environment + logic already?

**Comment by lightvector** [comment]
It would be doable, but take plenty of work. A bit less if the game has the property that the possible moves are almost a subset of the board locations, as in Go, or Hex,or Reversi, since if not, you might have to change possibly the representation of moves and within the code and the neural net architecture for outputting the moves. You'd also have to rewrite the input feature generation, modify some of the Go-specific optimizations in the search, get rid of the board ownership and score heads (unless your game has analogous concepts), rewrite the training data output format, and probably a small number of other things I'm forgetting.

Given that KataGo does implement a variety of Go-specific input features and training targets, unless your games is closely analogous, you might be better off writing your own or starting from a more game-neutral base (maybe Leela Zero? Someone did successfully map that one to Chess, which was how LC0 was born - otherwise not sure)

**Comment by alreadydone** [comment]
AlphaZero style projects that implement other games:
https://github.com/richemslie/galvanise_zero
https://github.com/suragnair/alpha-zero-general
https://github.com/pytorch/ELF

**Comment by 51616** [comment]
Thank you for the responses :)
