### ISSUE TITLE
precision of score at the end of a game.

### ISSUE THREAD

**Issue by bvandenbon** [lightvector/KataGo#70]
I was thinking about using KataGo for score estimation at the end of a game. (i.e. to determine a game result.)

But I've noticed that actually the score estimations of KataGo, can have slight deviations. e.g. in this game it settles for a score of "B+3.7", while it should obviously be a rounded value such as "B+3.5".

Any ideas ? - Right now it's tempting to just apply rounding in this kind of scenario, but naturally it makes me question the precision of this estimation. - Could it be a matter of the choice of the neural network ?

![afbeelding](https://user-images.githubusercontent.com/20482760/64479951-14d56980-d1bf-11e9-9c9e-655c1a757db4.png)

(ps: I use the scoremean value of the moves)

**Comment by lightvector** [comment]
Good observation! The neural network doesn't have a very strong incentive to make it perfectly accurate, because the error of 0.2 points is very small particularly if it doesn't affect the game result, and its "capacity" is better spent on making sure it's playing strong moves and making good judgments at times when it matters (during the actual game). So it's probably always going to be like this to some degree.

If you want to use the neural network to score the game and you know it's *right at the end* of the game, in a scoreable position, your best bet is probably to take the ownership prediction, and apply a threshold on the ownership for each individual board location, such as >95% -> 100%, and <5% -> 0%, and then count up the score yourself. Points in between those thresholds are likely to be seki liberties, so they should not be scored for either side. You may want to experiment a little for what threshold is most reliable in never missing a true point but also never including a seki liberty. Then, add up all the final ownership points yourself.

**Comment by lightvector** [comment]
Also, if the ownership score sum that you compute this way disagrees with the winrate on who is going to be winning the game, that's probably a good red flag for "this is a rare position that the net doesn't understand, something is weird and this position isn't auto-scorable".

**Comment by bvandenbon** [comment]
Great idea !
You're the best.

**Comment by lightvector** [comment]
Closing this issue as it seems to be handled? Feel free to comment again if not!
