### ISSUE TITLE
kata-analyze return = only without string result

### ISSUE THREAD

**Issue by songshizhao** [lightvector/KataGo#706]
kata-analyze return = only without string result
When using [kata-analyze interval n ownership true] return results again and again with a little difference.
I want to get current ownership report just once, How can I do it?

**Comment by lightvector** [comment]
What happens if you specify a large interval so that it will never report on its own, and then you stop the analysis manually by sending any other command? (e.g. stop, name, version).

**Comment by songshizhao** [comment]
I read the guid for gtp command：
lz-analyze [player (optional)] [interval (optional)] KEYVALUEPAIR KEYVALUEPAIR ...
kata-analyze [player (optional)] [interval (optional)] KEYVALUEPAIR KEYVALUEPAIR ...

interval is an optional input，but if i input cmd without interval only return =，such as 
kata-analyze ownership true

**Comment by songshizhao** [comment]
and what is the order of ownership result, top to bottom left to right row by row？

**Comment by lightvector** [comment]
Sorry, missed your reply to this issue earlier. Assuming you haven't already solved it yet, the oddity of these GTP commands is that they are intended for live reporting of results, so on their own they will not "complete" with a double newline (indicating the end of the GTP reply for that command) unless you issue another command. 
From https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md:
> This command is a bit unusual for GTP in that it will run forever on its own, but asynchronously if any new GTP command or a raw newline is received, then it will terminate.

That's why I suggested providing no interval, but then stopping the analysis manually after some time duration, by sending any arbitrary other command, or a newline, so that the command finishes and you get the output you wanted. But it looks like that might not work, you might just get no output at all. So I think if you are determined to using these commands, you should just tolerate the multiple outputs. Just issue a new command or a newline to stop the analysis after some point, and then if you don't like the multiple outputs, just ignore all of them except the last one.

If you want simply the ability to send single queries and get single results without worrying about statefulness, you could also consider the analysis engine: https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

For the ownership ordering, yep, that's right. More specifically, from https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md:
> Following is BoardHeight*BoardWidth many consecutive floats in [-1,1] separated by spaces, predicting the final ownership of every board location from the perspective of the current player. Floats are in row-major order, starting at the top-left of the board (e.g. A19) and going to the bottom right (e.g. T1).

**Comment by songshizhao** [comment]
my workingaround solution is 
give a small interval 
get the result once [for ownership]
call final_score to stop output interval result
---
Thanks for your explanation
