### ISSUE TITLE
how many stones can this give a pro on 4xV100?

### ISSUE THREAD

**Issue by hydrogenpi** [lightvector/KataGo#74]
how many stones can this KataGo give a pro on 4xV100?

**Comment by Friday9i** [comment]
I guess probably around 3 stones with 7.5 komi, which is a 2 stones advantage for black
Explanation: it's equivalent to a standard game with a 7.5 komi where white passes 2 times (black plays move 1, white 2 is a pass, black plays move 3, white 4 is a pass, black plays move 5: at this moment, black has 3 stones on the board and white has 0 and it's white turn to play, ie a 3-stones handi game)

**Comment by featurecat** [comment]
If you do test this against a pro, please upload the SGF :smile:

**Comment by lightvector** [comment]
Revisiting and cleaning up old stale issues, since a lot of stuff has happened between just this many months ago and now. :)

New fancy PDA has been around now for a while in the newJanuary - March 202 run and helps out, of course there's still more experimentation left that KataGo will probably not get around to in this run.
