### ISSUE TITLE
ownership result reversed after katago resign in a gtp game loop

### ISSUE THREAD

**Issue by songshizhao** [lightvector/KataGo#742]
in a game with handicap using gtp cmd
after katago output "= resign"
input "kata-analyze ownership true interval 20" 
the ownership result is reversed

**Comment by lightvector** [comment]
Can you elaborate further? I tried a test and it looks fine to me. I commented out the code that makes KataGo play a minimum number of moves before resigning in a handicap game, so that resigning would happen quickly, and it looks normal to me.

```
fixed_handicap 9
= D16 K16 Q16 D10 K10 Q10 D4 K4 Q4

genmove w
= C6

showboard
= MoveNum: 1 HASH: 842A4928C64BA5C9CC6DB452BBA5A8B7
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . X . . . . . X . . . . . X . . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . X . . . . . X . . . . . X . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . O1. . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . X . . . . . X . . . . . X . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .
Next player: Black
Rules: {"friendlyPassOk":false,"hasButton":false,"ko":"POSITIONAL","komi":7.5,"scoring":"AREA","suicide":true,"tax":"NONE","whiteHandicapBonus":"0"}
B stones captured: 0
W stones captured: 0

play b f3
=

genmove w
= B4

play b c3
=

genmove w
= resign

showboard
= MoveNum: 4 HASH: D13CF72607CD5CE34EA2655EAC9633AD
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . X . . . . . X . . . . . X . . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . X . . . . . X . . . . . X . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . O . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . O2. X . . . . . X . . . . . X . . .
 3 . . X3. . X1. . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .
Next player: White
Rules: {"friendlyPassOk":false,"hasButton":false,"ko":"POSITIONAL","komi":7.5,"scoring":"AREA","suicide":true,"tax":"NONE","whiteHandicapBonus":"0"}
B stones captured: 0
W stones captured: 0

kata-analyze ownership true interval 20
```

The final kata-analyze command returned near 0 winrate and highly negative numbers for score, as expected, since it is white's turn. And here is the ownership map when I copied the numbers into a spreadsheet and used some conditional formatting to color it:

![image](https://user-images.githubusercontent.com/11942395/212195840-83244c64-229f-4698-b9ff-25e21d27e4de.png)

Which also looks normal, it is mostly negative because black has all the handicap stones controlling the whole board.

**Comment by songshizhao** [comment]
my input is like:
-----------
...
place_free_handicap 19
genmove white
play D4
genmove white
play E16
...
...
------------
I played a whole game, nearly all the empty spcae has its owner 
ownership result is good during all of the above game time
and finally 
"genmove white" return "= resign"
then the ownership result cannot report the real situation this time.

**Comment by lightvector** [comment]
Resign is not a move, so the gamestate is still white's turn if white resigns.

**Comment by songshizhao** [comment]
> Resign is not a move, so the gamestate is still white's turn if white resigns.

you have to make katago(white) resign in a game, regardless the black chess continues or not
after this, check the ownership result
the result seem to be inverted (white own more space)

**Comment by lightvector** [comment]
Can you upload an example or a way to reproduce the problem? I'm unable to reproduce this problem, you can see that above I posted a transcript of a GTP log where KataGo resigned and the output looks normal to me.

**Comment by songshizhao** [comment]
> Can you upload an example or a way to reproduce the problem? I'm unable to reproduce this problem, you can see that above I posted a transcript of a GTP log where KataGo resigned and the output looks normal to me.

I don't know why katago resign so early in your post.
I use place_free_handicap cmd = 19 to start, katago still keep moving, no resign.
I can't provide example cause this is completely finished game with many many moves.
Sometimes katago uses '= pass' to end the game nstead of '=resign' even katago lost a lot

**Comment by lightvector** [comment]
It resigned so early because I commented out some code that normally KataGo uses in handicap games to play longer before resigning. But that doesn't matter, you don't need to edit the code. You can play an even game and just force KataGo to play some bad moves. Try this example instead:
```
boardsize 9
play B e5
play W a1
play B e7
play W a2
play B f3
genmove W
```
and then go a few more turns and KataGo will resign very soon because it's an even game, not a handicap game, but white has played some terrible moves and is hopelessly losing.

Can you provide an example of real output from kata-analyze that demonstrates the problem you are asking about?

**Comment by lightvector** [comment]
Here's a guess as to what could be happening: maybe your code, or your program, or whatever, currently assumes that the side to move will switch after every genmove command. For example:
```
...
play B some move ...
genmove W
= katago plays some move
kata-analyze...   <- now it is black's turn, so kata-analyze returns positive numbers for ownership, score, etc
play B some move ...
genmove W
= katago plays some move
kata-analyze...   <- now it is black's turn, so kata-analyze returns positive numbers for ownership, score, etc
play B some move ...
genmove W
= resign
kata-analyze...   <- now it is still WHITE'S turn because resign is NOT a move, so kata-analyze returns negative numbers for ownership, score, etc. 
                     However your program thinks that it is black's turn so it thinks those negative numbers mean that black is losing.
```
Because of resign, genmove is not guaranteed to change the side to move to be the opposite of the current side to move.

If the above doesn't explain it, it's possible of course that KataGo still has a subtle bug regarding the side to move in case of resignation, if you can report enough to show something I can reproduce, then I can fix it.

**Comment by songshizhao** [comment]
> Here's a guess as to what could be happening: maybe your code, or your program, or whatever, currently assumes that the side to move will switch after every genmove command. For example:
> 
> ```
> ...
> play B some move ...
> genmove W
> = katago plays some move
> kata-analyze...   <- now it is black's turn, so kata-analyze returns positive numbers for ownership, score, etc
> play B some move ...
> genmove W
> = katago plays some move
> kata-analyze...   <- now it is black's turn, so kata-analyze returns positive numbers for ownership, score, etc
> play B some move ...
> genmove W
> = resign
> kata-analyze...   <- now it is still WHITE'S turn because resign is NOT a move, so kata-analyze returns negative numbers for ownership, score, etc. 
>                      However your program thinks that it is black's turn so it thinks those negative numbers mean that black is losing.
> ```
> 
> Because of resign, genmove is not guaranteed to change the side to move to be the opposite of the current side to move.
> 
> If the above doesn't explain it, it's possible of course that KataGo still has a subtle bug regarding the side to move in case of resignation, if you can report enough to show something I can reproduce, then I can fix it.

Yes, you are right, my program works like you said.

Maybe I should reverse the ownership result after "resign".
