### ISSUE TITLE
Feature Request: play <multiple moves> and undo <count>

### ISSUE THREAD

**Issue by bvandenbon** [lightvector/KataGo#79]
I would like to add / propose a feature, which is a (minor) extension on the GTP spec.

**Motivation:**
If you run leela-zero on a remote server and you try to communicate to it using SSH, then you may experience a lot of delay in the communication. Effectively, when you navigate using a tree (e.g. lizzie, zbaduk, ...), and jump from one end of the game record to the other, that means executing a lot of `play` or `undo` commands to get there.

    play b a1 
    = 
    play w a2 
    =
    play b a3 
    =
    play w a19
    =

And to move to the front.

    undo
    =
    undo
    =
    undo
    =
    undo
    =

I have recently been measuring the response time of SSH communication, and often it is about ~10ms per executed command (waiting for the `=` ack). So, jumping 100 moves, effectively takes a full second.

Exceptionally I have seen delays of over 3 seconds in our server log files.

**Proposal:**
I would like to propose a single command to execute multiple play/undo commands.

i.e.

    play b a1 w a2 b a3 w a19
    =

and 

    undo 4
    =

Looking forward to your feedback.
Kind regards.

_PS: I posted the same question on the leela zero project, 
aiming to keep both command-sets the same._
https://github.com/leela-zero/leela-zero/issues/2523

**Comment by lightvector** [comment]
Why is it not sufficient to just send a long set of "play" and "undo"
commands *without* waiting for the response?
KataGo should be happy to accept a sequence of such commands, it will
simply perform them all as soon as it can, and send back all the responses
consecutively.

This is part of the GTP spec, see section 2.8 about no synchronization in
the protocol, and section 2.5 through 2.7 about the command "id" feature
specifically designed to allow for this type of asynchronous communication
so that the controller can know which response or error corresponded to
which command.
https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION00035000000000000000

So this would not require a GTP extension at all. And since Lizzie and
Zbaduk would have to be modified anyways to get them to use a new
GTP-extended command, one could instead just modify them to send commands
in sequence without waiting for responses in these cases.

**Comment by bvandenbon** [comment]
I used to do that with leelaz, but for some reason it would skip some moves
and get out of sync. Perhaps

**Comment by bvandenbon** [comment]
I don't want to tempt fate too much.

But it works fine so far.
And as expected, it is a huge improvement in terms of responsiveness.
