### ISSUE TITLE
Memory leaking in the current master branch (commits = 3383)

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#790]
When I compile the current master branch (commits = 3383), it shows memory leaking when it receives command "boardsize 19". Its memory usage will significantly increase after receiving this command.
Neither "clear_board" nor "clear_cache" command can prevent this phenomenon.
For my configuration, the program will crash by "bad allocation" after playing ~10 games.

**Comment by lightvector** [comment]
The bot should be deleted before it gets created again. Are you observing that this doesn't happen?
https://github.com/lightvector/KataGo/blob/master/cpp/command/gtp.cpp#L454-L462

Yes, the behavior has changed slightly to always recreate the bot instead of leaving the board state unaffected, but this was supposed to be intentional and not creating a leak. The reason for always creating a bot is because now certain parameters can decouple the size of the board and the size of the neural net, so rather than keep slightly messier logic to decide when recreating the bot, I just decided to always recreate.

It's possible that the memory use goes up because of memory fragmentation not allowing the freed memory from deletion to be perfectly reused for the new bot. But there should not be a leak - do you observe that the memory increases without bound if you keep resetting the board?

**Comment by lightvector** [comment]
Ah, okay I think I see the issue, it's not actually getting deleted there. Let me fix that.

**Comment by lightvector** [comment]
I think this is fixed now, and out of caution I restored the old behavior to not re-initialize the board if the size is the same, although supposedly under GTP both behaviors are acceptable. Please let me know if there are still any problems. Thank you for finding and reporting this so quickly!

**Comment by lightvector** [comment]
Commit here, https://github.com/lightvector/KataGo/commit/3017425b9acbc1018f27d161a36702176c817cfd, master branch is updated.

**Comment by sbbdms** [comment]
Sorry for the long delay...
Thanks! It is fixed by the latest modification according to the test.
