### ISSUE TITLE
train a new AI about cyclic topologies

### ISSUE THREAD

**Issue by NanachiKyubey** [lightvector/KataGo#808]
Is it possible to train a new AI that is more inclined to produce cyclic topologies to improve kataGo's inability to understand cyclic topologies?

My thoughts:
1. New AI and frozen KataGo play against each other. If the new AI moves make a cyclic topology, then it gets a small bonus. If it makes the cyclic topology and wins against frozen KataGo, it gets a big bonus.
2. until the new AI steadily pins frozen KataGo, capturing the loop topology bug in frozen KataGo.
3. KataGo and the new AI train against each other.

I would like to know if such an idea has already been tried and if there is any hope.

**Comment by lightvector** [comment]
I think KataGo is making decent enough progress in learning the problem already right now that continuing the current training approach is okay for now. Have you tried the most recent b18 networks? If you find that they still have big weaknesses on cyclic groups that are exploitable in real games, please post some SGFs! More examples are would be greatly appreciated for training!

The easiest way if you do want to automate it would probably be to just finetune and extend the network of the researchers' who published the original work on this weakness.

You could also try your approach, but a challenge is how you define what a "cyclic topology" is - there are a lot of tricky choices you would have to make about how to implement it. Do you have an algorithm to suggest for how to do that? Things you would have to consider: if you try to check whether there is a "cyclic topology" at the end of the game, then it doesn't work because if the cyclic group dies, it isn't there at the end of the game, also if the cyclic group lives and if the inner group is non-two-eyed (another important case), then also there is no large cycle at the end of the game. If you try to check before the end of the game, you run into issues that the cyclic group is often not strictly connected - you may have bamboo joints, and such. You may also need to avoid false positives, like it its very easy to make a "cyclic" group just by making any arbitrary dead group in the opponent's territory even if it doesn't actually make any big risk for misevaluation, it's mainly the case when the opponent's eyes get all or almost all poked out as well. Certainly all solvable, but it could take a lot of work to figure out all the details.

One challenge with any of these automated approaches is that they don't have quite the variety that human exploit-users can produce. That's something I definitely noticed, it's easy for an automated exploiter to fall into a single mode, and miss the other related modes that also cause misevaluations. Maybe you would need many, with randomness in how they are trained or incentivized.

**Comment by NanachiKyubey** [comment]
-  **More examples are would be greatly appreciated for training!**

There are many examples of such exploits in Chinese video sites, but they are only making videos to prove that "humans are better than AI", I don't think they are willing to contribute to the optimization of Go AI...

-  **The easiest way if you do want to automate it would probably be to just finetune and extend the network of the researchers' who published the original work on this weakness.**

So what are the results of training the paper ai against katago? I heard some folk rumors in China that for the general situation the win rate went down instead.

-  **You could also try your approach, but a challenge is how you define what a "cyclic topology" is**

I don't have any good ideas. Checking before the end of the game is a must. 
My idea is to train an image recognition AI as a checker, by supervised learning. If we go this route it will require a lot of human resources to score SGF files.

- **That's something I definitely noticed, it's easy for an automated exploiter to fall into a single mode, and miss the other related modes that also cause misevaluations.**

This is why I propose to start with a frozen KataGo and induce it under the cyclic topology. Even if it doesn't go well in the final adversarial training phase, at least we get a new AI that really likes to play cyclic topology and is not bad at Go.

**Comment by lightvector** [comment]
For the videos, are there SGF files available or are the SGFs easy to transcribe from the video? If they are against recent KataGo networks no more than 1-2 months old, they could be very useful, if you or others would be willing to transcribe them.

(Probably far less useful if they are against old KataGo networks, since generally the newer versions have already learned enough about cycle groups to easily detect most of the mistakes in games played by networks more than 1-2 months old - there has been a lot of gradual progress!).

**Comment by NanachiKyubey** [comment]
I can experiment more myself on the latest version, but it will take a little time.
