### ISSUE TITLE
katago has dead-alive bugs, is it possible to train a katago ai that specializes in solving dead-alive problems?（katago有死活的bug，能否训练一个专门解决死活题的katago ai？）

### ISSUE THREAD

**Issue by awsjgy** [lightvector/KataGo#847]
I think katago under normal rules has to be realized by rewriting the code in order to solve dead-live problems. Otherwise by modifying the rules of the gui interface, you can't achieve the practical effect of solving dead-alive problems.

I have thoughts that if I were to design a dead-live katago, the hard part to consider would be the hijacking, and the katago if it eats the specified piece.

And because katago is based on global computation, can we make a katago based on local computation, which is good for solving dead-live problems.

我觉得正常规则下的katago要想解决死活题，必须通过重新写代码来实现。否则通过修改gui界面规则，不能达到实际效果的解死活题。

我有思路，如果要设计一个死活katago，需要考虑的难点是打劫，还有如果吃指定棋子的katago。

还有因为katago是基于全局计算的，能否做一个基于局部计算的katago，这样有利于解决死活题。

**Comment by lightvector** [comment]
I think you already have an open issue at https://github.com/lightvector/KataGo/issues/841 that discusses the same topic. Please don't keep opening more issues about the exact same topic. I'll go ahead and close this one since it's a duplicate, feel free to repost your discussion here to there instead.
