### ISSUE TITLE
What is the differene between nnVisit/s and nnEvals/s?

### ISSUE THREAD

**Issue by ymkwon0618** [lightvector/KataGo#852]
1. What is the differene between nnVisit/s and nnEvals/s?

2. Which one is more closely related to Katago performance?

3. Below is Katago Benchmark test Results.
    Is TensorRT most strong?

       PC Spec : i5-12400F, RTX 4060 Ti, 16GB,  .\katago benchmark -config default_gtp.cfg -model KataGo40b.gz
         OpenCL  : 1484.78 visit/s 1239.38 Evals/s (16 Threads)
         CUDA     :    253.89 visit/s  219.28 Evals/s (20 Threads)
         TensorRT : 1956.56 visit/s  1780.69 Evals/s (32 Threads)

**Comment by lightvector** [comment]
They are both about equally related to performance. Visits is the number of search tree nodes explored, Evals is the number of queries to the neural net. These two numbers will usually be fairly similar, the difference is that sometimes an evaluation can be used for more than one visit because there are two sequences of moves that lead to the same position, so the evaluation of that single position may be used for both visits - one for each sequence.

You should use whatever is fastest, normally - so in your case yes it looks like TensorRT is fastest.
