### ISSUE TITLE
Will Finetuned 9x9 Neural Net continue to be trained and updated?

### ISSUE THREAD

**Issue by ASSLQL** [lightvector/KataGo#861]
it seems that there is still a lot of room for improvement, and the results of many states are ambiguous

**Comment by lightvector** [comment]
Yeah, unfortunately I'm not currently planning to train it further right now. 

The distance to optimal is still very, very far - even if it were trained for 10 times longer, what you say would likely continue to be true. It's already stronger and more accurate in analysis than any prior neural net on 9x9, and in direct play, with only a few thousands of playouts per move, almost never loses to other bots in practice, including other versions of KataGo.

So it's hard for me to justify spending more of my personal resources on it instead of other things, especially since most people don't even play 9x9 and don't care about such a bot. If you or a lot of people actually are interested, and if you or someone you know is an experienced software developer, maybe you can try experimenting with training it further on your own. :)

**Comment by ASSLQL** [comment]
I see. Thank you for your reply.
