### ISSUE TITLE
Question about rootInfo and ownership

### ISSUE THREAD

**Issue by zhongwang97** [lightvector/KataGo#894]
Hi, may I ask how to understand the meaning of `rootInfo` and `ownership`
if I have a query like `"moves": [["b", "D4"], ["w", "Q16"]], "analyzeTurns": [2]`

1. the `winrate` and  `scoreLead` in `rootInfo` and is the analysis result of WHITE play in `Q16` ?
2. the `ownership` in top level of response is the analysis result of WHITE play in `Q16` ?
3. if 1 and 2 is yes, is it possible to add `pv` to rootInfo?
4. if my understanding is wrong, how can I force KataGo to analysis the Q16 play and get its `winrate` /  `scoreLead` / `pv`

Thank you

**Comment by lightvector** [comment]
1. yes
2. yes
3. Look for the move info with order 0 - that's the top move and then you can look at its pv.

Note that the root winrate, score, ownership, etc. do NOT correspond to any specific pv. Similarly, the winrate, score, ownership on a given move do NOT correspond to the pv for that move. The way MCTS works, all of these values are fuzzy weighted *averages* of the values across the entire search tree, or across the entire subtree for a given move, whereas the pv is just one specific path through the subtree, which might not even have the majority of the visits or the weight by the time you reach several steps deep.

**Comment by zhongwang97** [comment]
OK, actually I didn't understand the MCTS part :joy:, but still thank you for your answer and explanation!

**Comment by lightvector** [comment]
Let me explain it a different way: suppose you get a move info for Q4 which has a PV of "Q4 P4 P3 D3 D5" and a winrate of 70%.

Wrong: "Q4 P4 P3 D3 D5 is judged to have a winrate of 70%."

Correct: "Q4 is judged to have a winrate of 70%." 

This is because even though "P4 P3 D3 D5" is the most likely possible followup to Q4, there could be many other possibilities too. All together all of these possibilities may have a lot of uncertainty, and 70% is the winrate given all of that uncertainty together, and "P4 P3 D3 D5" itself might be different than 70%.

The same applies for score, ownership, etc. Does that make sense?

**Comment by zhongwang97** [comment]
yes I got it, thank you for your explanation!
