### ISSUE TITLE
Analyze with a fixed visit number?

### ISSUE THREAD

**Issue by bsteuber** [lightvector/KataGo#91]
Hi, first of all let me say thanks for creating this great bot! 
KataGo now is the default engine on [AI Sensei](https://ai-sensei.com) and our users are really happy with it.

I've got one question, though:
We analyze games with a fixed visit number like 1000 visits per move, and we need the score and ownership numbers. We currently implement that by using kata-analyze from a script that tracks the output, sums up the visits and stops once that number is reached. This approach works, but it feels quite inefficient and involves guessing a good report interval. So we would rather have a way to specify a visit count, too. We can try patching KataGo for ourselves, but before we start I thought I'd ask:
- if there's another way to achieve what we want already
- if other people would be interested in this patch, too
- if you have any recommendations for implementing it

Thanks a lot :)

**Comment by lightvector** [comment]
It's not documented all that well yet, but you might be interested in the "analyze" subcommand. If you have some experience in "code diving" you might be able to look at cpp/analyze.cpp and figure out what the protocol is, otherwise I'll write some documentation in the next weeks - and review that code to see if there are any rough edges that make it hard to use, there might well be.

But in theory, it should do pretty much what you want, with a somewhat different API, based around JSON requests over stdin/stdout.

**Comment by lightvector** [comment]
It should also be quite a bit faster too for bulk-processing of positions, since it takes advantage of batching across multiple game states, if you want to analyze a whole game, rather than just one position.

**Comment by bsteuber** [comment]
That sounds nice, we will look into it.

lightvector <notifications@github.com> schrieb am Do., 19. Dez. 2019, 15:17:

**Comment by lightvector** [comment]
Let me know if I can help! I just had a look at your site for the first time, and it looks really cool. :)

As a side note in case you feel it's worth addressing (or not) - I have heard some more technical-minded players dislike the use of the word "influence" used by some tools and/or some online posts and articles to refer to KataGo's ownership predictions, preferring just to call it predicted ownership or predicted control. My understanding of their reasoning is that "influence" as understood by high-level go players is not really the same thing: the two are very highly correlated, but in some cases one may have a lot of influence over a particular region, in the normal "Go player" sense of the word of having a wide upper-hand in fights in that area due to facing walls or stones, yet also be predicted and expected to own very little of it or even to have it be owned by the opponent if the opponent invades, the profit mostly being realized in other side areas.

Anyways, thanks also for the support and enthusiasm! - tools like this are a big part of making raw engines actually useful to users. :)

**Comment by lightvector** [comment]
Just browsing back over old issues. As of later releases, the analysis subcommand should now have clear documentation here:
https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

Let me know if there are any other questions. Thanks!

**Comment by bsteuber** [comment]
Hi, thanks for writing the documentation. After some other large refactoring, we finally started using the analysis interface and it works like a charm!

We will soon release a version of our website where 50 visit analysis will be free :) 

Best regards,
Benjamin
