### ISSUE TITLE
unable to load library nvinfer_builder_resource.dll

### ISSUE THREAD

**Issue by changcheng967** [lightvector/KataGo#932]
KataGo v1.14.1 Using TrompTaylor rules initially, unless GTP/GUI overrides this TensorRT backend: 6: [libLoader.cpp::nvinfer1::rt::DynamicLibrary::Impl::Impl::290] Error Code 6: Internal Error (Unable to load library: nvinfer_builder_resource.dll)

After I run KataGo on Lizzieyzy, it shows this

I am using Win10，NVIDIA Geforce GTX 1660 SUPER

**Comment by lightvector** [comment]
Sorry I missed this issue for a while. Are you still having trouble, and did you install correct versions of CUDA and TensorRT? This error sounds like the kind of error that you would get if you haven't installed TensorRT, or if isn't installed correctly. You can also check if other versions of KataGo work for you rather than just the TensorRT version, and if you're absolutely sure you installed things perhaps it's just not finding the dll, in which case you can try searching your computer for the `nvinfer_builder_resource.dll` and copy that DLL to the same directory as the katago exe to make sure it gets found.

**Comment by tinyhare** [comment]
Because you use [katago-v1.14.1-trt8.6.1-cuda12.1-windows-x64.zip](https://github.com/lightvector/KataGo/releases/download/v1.14.1/katago-v1.14.1-trt8.6.1-cuda12.1-windows-x64.zip)

you need TensorRT8.6，download it from nvidia web page, you can get the .dll files. copy it to the same directory as katago.exe located.
https://developer.nvidia.com/tensorrt/download

[TensorRT 8.6 GA for Windows 10 and CUDA 12.0 and 12.1 ZIP Package](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/8.6.1/zip/TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0.zip)
