### ISSUE TITLE
Rule issue

### ISSUE THREAD

**Issue by yangheoncha** [lightvector/KataGo#984]
![SmartSelect_20240914-214628_YouTube](https://github.com/user-attachments/assets/d7c66655-c7bb-4eb4-b2ac-535817a2d1cd)
![20240914_215010](https://github.com/user-attachments/assets/ff134d2f-a39a-434a-9c50-8c75147db8e7)
![20240914_215616](https://github.com/user-attachments/assets/b2757358-4957-42b1-b709-86b001aa1e53)

In this game i marked whitestones are not dead but katago recognize dead.

I think rule that blackplayer cannot capture whitestones whiteplayer also so if blackplayer cannot make alive blackstones i marked can make draw.

And the engine remaked china golaxy judged 2.7 black win at this. I think golaxy set rule so blackplayer can win.

I think katago add rule that can.

update rule please.

Thank you make free.

**Comment by lightvector** [comment]
Can you provide an SGF file of the game?

**Comment by yangheoncha** [comment]
> Can you provide an SGF file of the game?

https://www.cyberoro.com/gibo_new/giboviewer/giboviewer.asp?gibo=https://open.cyberoro.com/gibo/202409/m8sin.sgf&gibonum=46783&bimg=SinJinS.jpg&wimg=LiChangH.jpg&site=

I am sorry i cannot make this to sgf file imsorry. 😢

**Comment by kendfrey** [comment]
There are a few intricacies in this game.
1. According to both Chinese rules with superko and also Japanese rules, the white group is locally dead, as the black group has one eye and the white group has none. White cannot force Black to continue playing the triple ko, so this is a false triple ko. See an explanation of false triple ko here: https://www.youtube.com/watch?v=lkhSoLLPDKQ
2. Korean rules apparently differ from Japanese rules in this situation, in that Korean rules do not have a pass-to-retake-ko concept in hypothetical play. I believe in this case, since the game is being played under Korean rules, this is a true triple ko that will result in a voided game (unless either player can manage to gain enough of an advantage on the rest of the board to sacrifice the triple ko and still win). This difference between Japanese and Korean rules is described briefly here: https://senseis.xmp.net/?KoreanRules
3. Later in the game, the outside black group gets surrounded, and only has one eye. White will be able to reduce its liberties and force Black to start the triple ko to avoid being captured. In this case, Japanese rules would once again lead to a voided game, matching Korean rules. Chinese rules *in practice* would probably also lead to a voided game, but if superko is enforced then it would be a ko fight.

KataGo's weaknesses:
1. KataGo is generally poor at recognizing when a locally false triple ko will inevitably become a true triple ko due to insufficient liberties on the outside, as in this game. In both this game and at least one other game I've analyzed, it thinks one player is winning until the triple ko is only a few moves from starting.
2. As far as I'm aware, KataGo always applies Japanese-style hypothetical play when using the simple ko rule, so if this game (or any other Korean rules game with a one-eye-vs-no-eye triple ko) is analyzed with such a ruleset, KataGo is likely to be completely wrong about the evaluation.

The SGF of Shin Jinseo vs. Lee Changho is available here: https://go4go.net/go/games/sgfview/117349

I've attached another game (originally played under Japanese rules) between two versions of KataGo that also demonstrates the first weakness: [katago_tripleko.sgf.txt](https://github.com/user-attachments/files/17003102/katago_tripleko.sgf.txt) (just remove the .txt, it's there so GitHub doesn't block the file)
In this game black can comfortably win by making two eyes with his group on the bottom side, ensuring the white group in the false triple ko is dead. Instead, he misplays, not realizing the triple ko has become inevitable.

**Comment by yangheoncha** [comment]
![SmartSelect_20240915-035608_Chrome](https://github.com/user-attachments/assets/a46f01ed-93e2-4dea-b411-97da732c19d4)

I watched live and someone who using golaxy said to live chat blackplayer 2.7 win my golaxy i saw like this 

I think our rule 
![20240914_215616](https://github.com/user-attachments/assets/d8138dab-1607-486d-8429-87b7b21a811a)

If these blackstones alive

![20240915_033339](https://github.com/user-attachments/assets/55f3ad87-bef9-4d59-9e58-ad2c185ccb7c)

These are no territory both 

![20240915_040838](https://github.com/user-attachments/assets/5a51deaa-7469-496d-859e-205bd39ca095)

So white can use infinite when it comes 

![20240915_041046](https://github.com/user-attachments/assets/8b38b325-7292-43ad-8584-8ae3710bc802)

But black can trade to win

![SmartSelect_20240915-041246_Chrome](https://github.com/user-attachments/assets/6fd6928c-5b8e-4780-a004-a7ed03bdc992)

I think golaxy set this rule so that can strong. I think this  territory judgement rule can change make more strong.

**Comment by yangheoncha** [comment]
![SmartSelect_20240915-082054_Chrome](https://github.com/user-attachments/assets/52931583-9ab2-4fcc-adc8-5fdacef92bab)
![SmartSelect_20240915-082336_Chrome](https://github.com/user-attachments/assets/51d3a9d4-b8b7-4808-9691-2b815f7ec376)
https://go4go.net/go/games/sgfview/31860

I clicked download sgf but can't so link need sign up&in.

I image machine perfect kindofthisgame.

Thankyou.

**Comment by yangheoncha** [comment]
> There are a few intricacies in this game.
> 
> 1. According to both Chinese rules with superko and also Japanese rules, the white group is locally dead, as the black group has one eye and the white group has none. White cannot force Black to continue playing the triple ko, so this is a false triple ko. See an explanation of false triple ko here: https://www.youtube.com/watch?v=lkhSoLLPDKQ (EDIT: After more analysis, I realized white has the option to turn it into a direct ko, so it's not completely dead)
> 2. Korean rules apparently differ from Japanese rules in this situation, in that Korean rules do not have a pass-to-retake-ko concept in hypothetical play. I believe in this case, since the game is being played under Korean rules, this is a true triple ko that will result in a voided game (unless either player can manage to gain enough of an advantage on the rest of the board to sacrifice the triple ko and still win). This difference between Japanese and Korean rules is described briefly here: https://senseis.xmp.net/?KoreanRules
> 3. Later in the game, the outside black group gets surrounded, and only has one eye. White will be able to reduce its liberties and force Black to start the triple ko to avoid being captured. In this case, Japanese rules would once again lead to a voided game, matching Korean rules. Chinese rules _in practice_ would probably also lead to a voided game, but if superko is enforced then it would be a ko fight.
> 
> KataGo's weaknesses:
> 
> 1. KataGo is generally poor at recognizing when a locally false triple ko will inevitably become a true triple ko due to insufficient liberties on the outside, as in this game. In both this game and at least one other game I've analyzed, it thinks one player is winning until the triple ko is only a few moves from starting.
> 2. As far as I'm aware, KataGo always applies Japanese-style hypothetical play when using the simple ko rule, so if this game (or any other Korean rules game with a one-eye-vs-no-eye triple ko) is analyzed with such a ruleset, KataGo is likely to be completely wrong about the evaluation.
> 
> The SGF of Shin Jinseo vs. Lee Changho is available here: https://go4go.net/go/games/sgfview/117349
> 
> I've attached another game (originally played under Japanese rules) between two versions of KataGo that also demonstrates the first weakness: [katago_tripleko.sgf.txt](https://github.com/user-attachments/files/17003102/katago_tripleko.sgf.txt) (just remove the .txt, it's there so GitHub doesn't block the file) In this game black can comfortably win by making two eyes with his group on the bottom side, ensuring the white group in the false triple ko is dead. Instead, he misplays, not realizing the triple ko has become inevitable.



> There are a few intricacies in this game.
> 
> 1. According to both Chinese rules with superko and also Japanese rules, the white group is locally dead, as the black group has one eye and the white group has none. White cannot force Black to continue playing the triple ko, so this is a false triple ko. See an explanation of false triple ko here: https://www.youtube.com/watch?v=lkhSoLLPDKQ (EDIT: After more analysis, I realized white has the option to turn it into a direct ko, so it's not completely dead)
> 2. Korean rules apparently differ from Japanese rules in this situation, in that Korean rules do not have a pass-to-retake-ko concept in hypothetical play. I believe in this case, since the game is being played under Korean rules, this is a true triple ko that will result in a voided game (unless either player can manage to gain enough of an advantage on the rest of the board to sacrifice the triple ko and still win). This difference between Japanese and Korean rules is described briefly here: https://senseis.xmp.net/?KoreanRules
> 3. Later in the game, the outside black group gets surrounded, and only has one eye. White will be able to reduce its liberties and force Black to start the triple ko to avoid being captured. In this case, Japanese rules would once again lead to a voided game, matching Korean rules. Chinese rules _in practice_ would probably also lead to a voided game, but if superko is enforced then it would be a ko fight.
> 
> KataGo's weaknesses:
> 
> 1. KataGo is generally poor at recognizing when a locally false triple ko will inevitably become a true triple ko due to insufficient liberties on the outside, as in this game. In both this game and at least one other game I've analyzed, it thinks one player is winning until the triple ko is only a few moves from starting.
> 2. As far as I'm aware, KataGo always applies Japanese-style hypothetical play when using the simple ko rule, so if this game (or any other Korean rules game with a one-eye-vs-no-eye triple ko) is analyzed with such a ruleset, KataGo is likely to be completely wrong about the evaluation.
> 
> The SGF of Shin Jinseo vs. Lee Changho is available here: https://go4go.net/go/games/sgfview/117349
> 
> I've attached another game (originally played under Japanese rules) between two versions of KataGo that also demonstrates the first weakness: [katago_tripleko.sgf.txt](https://github.com/user-attachments/files/17003102/katago_tripleko.sgf.txt) (just remove the .txt, it's there so GitHub doesn't block the file) In this game black can comfortably win by making two eyes with his group on the bottom side, ensuring the white group in the false triple ko is dead. Instead, he misplays, not realizing the triple ko has become inevitable.



> There are a few intricacies in this game.
> 
> 1. According to both Chinese rules with superko and also Japanese rules, the white group is locally dead, as the black group has one eye and the white group has none. White cannot force Black to continue playing the triple ko, so this is a false triple ko. See an explanation of false triple ko here: https://www.youtube.com/watch?v=lkhSoLLPDKQ (EDIT: After more analysis, I realized white has the option to turn it into a direct ko, so it's not completely dead)
> 2. Korean rules apparently differ from Japanese rules in this situation, in that Korean rules do not have a pass-to-retake-ko concept in hypothetical play. I believe in this case, since the game is being played under Korean rules, this is a true triple ko that will result in a voided game (unless either player can manage to gain enough of an advantage on the rest of the board to sacrifice the triple ko and still win). This difference between Japanese and Korean rules is described briefly here: https://senseis.xmp.net/?KoreanRules
> 3. Later in the game, the outside black group gets surrounded, and only has one eye. White will be able to reduce its liberties and force Black to start the triple ko to avoid being captured. In this case, Japanese rules would once again lead to a voided game, matching Korean rules. Chinese rules _in practice_ would probably also lead to a voided game, but if superko is enforced then it would be a ko fight.
> 
> KataGo's weaknesses:
> 
> 1. KataGo is generally poor at recognizing when a locally false triple ko will inevitably become a true triple ko due to insufficient liberties on the outside, as in this game. In both this game and at least one other game I've analyzed, it thinks one player is winning until the triple ko is only a few moves from starting.
> 2. As far as I'm aware, KataGo always applies Japanese-style hypothetical play when using the simple ko rule, so if this game (or any other Korean rules game with a one-eye-vs-no-eye triple ko) is analyzed with such a ruleset, KataGo is likely to be completely wrong about the evaluation.
> 
> The SGF of Shin Jinseo vs. Lee Changho is available here: https://go4go.net/go/games/sgfview/117349
> 
> I've attached another game (originally played under Japanese rules) between two versions of KataGo that also demonstrates the first weakness: [katago_tripleko.sgf.txt](https://github.com/user-attachments/files/17003102/katago_tripleko.sgf.txt) (just remove the .txt, it's there so GitHub doesn't block the file) In this game black can comfortably win by making two eyes with his group on the bottom side, ensuring the white group in the false triple ko is dead. Instead, he misplays, not realizing the triple ko has become inevitable.

Thank you.

**Comment by lightvector** [comment]
@kendfrey The pass-for-ko logic for the cleanup phase in KataGo is specific to *territory scoring*'s cleanup, not to the simple ko rule. If you set these positions to simple ko + area scoring, they seem to be a little better. Still far from ideal, probably due to a significant lack of training data on triple ko positions, but they are somewhat closer in winrate and score outputs to judging a draw.

If we want to improve it and the issue you pointed out about, probably it would go a long way to help if one could compose a synthetic dataset of different kinds of "real" and "false" kinds of triple-ko-like positions, for them to get learned, to toss into the training. In your attached game, in Japanese rules the net clearly does realize that it's substantially uncertain about something due to the way the winrate is not pinned at 99+%, so probably getting more data would significantly clarify these things.

As far as getting it to work for simple ko + korean-style territory scoring rather than simple ko + area scoring, I'm not excited about diving into the cleanup phase logic to implement the change to make it korean style territory scoring rather than japanese-style territory scoring. Does some know what changes would be needed to https://lightvector.github.io/KataGo/rules.html to make it work, and can analyze what difference in side effects and pathologies it might cause in the rules? In the meantime, I would recommend using area scoring as a crude workaround, which if we had the above synthetic triple ko training could probably be made trained to be decently accurate without needing any deep changes to rules.
