### ISSUE TITLE
cmake version 3.12.0 may have trouble finding CUDA on Google Colab

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#99]
Hi.

I am using KataGo v1.3 on Google Colaboratory.
Colab's default cmake is version 3.12.0 and it fails to compile.

    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    CUDA_cublas_device_LIBRARY (ADVANCED)
        linked by target "katago" in directory /content/drive/My Drive/KataGo/cpp

Updating cmake to v3.16.2 solved this issue.

**Comment by luckyangman** [comment]
according to：
sudo apt-get install libzip

 sudo  apt-get install  libzip-dev
 
 wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz

 cmake-3.16.2-Linux-x86_64.tar.gz

 
 tar zxvf cmake-3.16.2-Linux-x86_64.tar.gz


 sudo  mv  cmake-3.16.2-Linux-x86_64 /opt/cmake-3.16.2

 sudo   ln -sf /opt/cmake-3.16.2/bin/*  /usr/bin/

 sudo reboot

 cmake --version

**Comment by y-ich** [comment]
@luckyangman san,

Thank you for providing concrete script!

As cmake version requirement was discussed in #92, I wanted to point out that there is a case that current requirement does not work.

**Comment by lightvector** [comment]
I suspect the current requirement *does* work okay. My guess is just that CMake has improved their heuristics for where on your computer to search for the CUDA-related libraries to try to find them. For me, 3.12.3 works perfectly fine on a standard Ubuntu Linux installation with a "textbook" CUDA installation, so at least 3.12.3 has good enough heuristics for that case.

I'm not going to update the CMake requirement beyond 3.10.2 because 3.10.2 might be good enough for some users already, so I think there's no actual thing for me to implement or address here? But I guess you can leave this issue open anyways as a notice for users who have trouble having CMake find CUDA - that upgrading CMake might help.

**Comment by lightvector** [comment]
I updated the title to be more clear that cmake 3.12.0 is not bad, instead it's a specific issue with CUDA and/or Google Colab.

**Comment by y-ich** [comment]
@lightvector san,

Thank you for your clarification!
I close this issue since I think that Google will lead Colab KataGo users to this URL.
